;(function(){
var h;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ca=0;function da(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ea(a,b){null!=a&&this.append.apply(this,arguments)}ea.prototype.qa="";ea.prototype.append=function(a,b,c){this.qa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.qa+=arguments[d];return this};ea.prototype.toString=function(){return this.qa};var fa;function ga(){throw Error("No *print-fn* fn set for evaluation environment");}var ha=null;function ia(){return new r(null,5,[ja,!0,ka,!0,la,!1,na,!1,oa,null],null)}function s(a){return null!=a&&!1!==a}function pa(a){return s(a)?!1:!0}function t(a,b){return a[n(null==b?null:b)]?!0:a._?!0:u?!1:null}function qa(a){return null==a?null:a.constructor}function w(a,b){var c=qa(b),c=s(s(c)?c.Xa:c)?c.Wa:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}
function ra(a){var b=a.Wa;return s(b)?b:""+x(a)}function z(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
var ta=function(){function a(a,b){return sa.c?sa.c(function(a,b){a.push(b);return a},[],b):sa.call(null,function(a,b){a.push(b);return a},[],b)}function b(a){return c.a(null,a)}var c=null,c=function(d,c){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,0,c)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}(),ua={},va={};
function wa(a){if(a?a.J:a)return a.J(a);var b;b=wa[n(null==a?null:a)];if(!b&&(b=wa._,!b))throw w("ICounted.-count",a);return b.call(null,a)}function xa(a){if(a?a.K:a)return a.K(a);var b;b=xa[n(null==a?null:a)];if(!b&&(b=xa._,!b))throw w("IEmptyableCollection.-empty",a);return b.call(null,a)}function za(a,b){if(a?a.G:a)return a.G(a,b);var c;c=za[n(null==a?null:a)];if(!c&&(c=za._,!c))throw w("ICollection.-conj",a);return c.call(null,a,b)}
var Aa={},A=function(){function a(a,b,c){if(a?a.V:a)return a.V(a,b,c);var g;g=A[n(null==a?null:a)];if(!g&&(g=A._,!g))throw w("IIndexed.-nth",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.H:a)return a.H(a,b);var c;c=A[n(null==a?null:a)];if(!c&&(c=A._,!c))throw w("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,f){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),
Ba={};function C(a){if(a?a.S:a)return a.S(a);var b;b=C[n(null==a?null:a)];if(!b&&(b=C._,!b))throw w("ISeq.-first",a);return b.call(null,a)}function D(a){if(a?a.T:a)return a.T(a);var b;b=D[n(null==a?null:a)];if(!b&&(b=D._,!b))throw w("ISeq.-rest",a);return b.call(null,a)}
var Ca={},Da=function(){function a(a,b,c){if(a?a.O:a)return a.O(a,b,c);var g;g=Da[n(null==a?null:a)];if(!g&&(g=Da._,!g))throw w("ILookup.-lookup",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.N:a)return a.N(a,b);var c;c=Da[n(null==a?null:a)];if(!c&&(c=Da._,!c))throw w("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Ea(a,b,c){if(a?a.ra:a)return a.ra(a,b,c);var d;d=Ea[n(null==a?null:a)];if(!d&&(d=Ea._,!d))throw w("IAssociative.-assoc",a);return d.call(null,a,b,c)}var Fa={};function Ga(a,b){if(a?a.Ua:a)return a.Ua(a,b);var c;c=Ga[n(null==a?null:a)];if(!c&&(c=Ga._,!c))throw w("IMap.-dissoc",a);return c.call(null,a,b)}var Ha={};function Ia(a){if(a?a.ab:a)return a.ab();var b;b=Ia[n(null==a?null:a)];if(!b&&(b=Ia._,!b))throw w("IMapEntry.-key",a);return b.call(null,a)}
function Ja(a){if(a?a.bb:a)return a.bb();var b;b=Ja[n(null==a?null:a)];if(!b&&(b=Ja._,!b))throw w("IMapEntry.-val",a);return b.call(null,a)}var Ka={};function La(a,b,c){if(a?a.Va:a)return a.Va(a,b,c);var d;d=La[n(null==a?null:a)];if(!d&&(d=La._,!d))throw w("IVector.-assoc-n",a);return d.call(null,a,b,c)}function Ma(a){if(a?a.kb:a)return a.state;var b;b=Ma[n(null==a?null:a)];if(!b&&(b=Ma._,!b))throw w("IDeref.-deref",a);return b.call(null,a)}var Oa={};
function Pa(a){if(a?a.B:a)return a.B(a);var b;b=Pa[n(null==a?null:a)];if(!b&&(b=Pa._,!b))throw w("IMeta.-meta",a);return b.call(null,a)}var Qa={};function Ra(a,b){if(a?a.D:a)return a.D(a,b);var c;c=Ra[n(null==a?null:a)];if(!c&&(c=Ra._,!c))throw w("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var Sa={},Ta=function(){function a(a,b,c){if(a?a.Q:a)return a.Q(a,b,c);var g;g=Ta[n(null==a?null:a)];if(!g&&(g=Ta._,!g))throw w("IReduce.-reduce",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.P:a)return a.P(a,b);var c;c=Ta[n(null==a?null:a)];if(!c&&(c=Ta._,!c))throw w("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Ua(a,b){if(a?a.v:a)return a.v(a,b);var c;c=Ua[n(null==a?null:a)];if(!c&&(c=Ua._,!c))throw w("IEquiv.-equiv",a);return c.call(null,a,b)}function Va(a){if(a?a.A:a)return a.A(a);var b;b=Va[n(null==a?null:a)];if(!b&&(b=Va._,!b))throw w("IHash.-hash",a);return b.call(null,a)}var Wa={};function Xa(a){if(a?a.C:a)return a.C(a);var b;b=Xa[n(null==a?null:a)];if(!b&&(b=Xa._,!b))throw w("ISeqable.-seq",a);return b.call(null,a)}var Ya={};
function E(a,b){if(a?a.fb:a)return a.fb(0,b);var c;c=E[n(null==a?null:a)];if(!c&&(c=E._,!c))throw w("IWriter.-write",a);return c.call(null,a,b)}var Za={};function $a(a,b,c){if(a?a.u:a)return a.u(a,b,c);var d;d=$a[n(null==a?null:a)];if(!d&&(d=$a._,!d))throw w("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function ab(a,b,c){if(a?a.eb:a)return a.eb(0,b,c);var d;d=ab[n(null==a?null:a)];if(!d&&(d=ab._,!d))throw w("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function bb(a){if(a?a.sa:a)return a.sa(a);var b;b=bb[n(null==a?null:a)];if(!b&&(b=bb._,!b))throw w("IEditableCollection.-as-transient",a);return b.call(null,a)}function cb(a,b){if(a?a.Ba:a)return a.Ba(a,b);var c;c=cb[n(null==a?null:a)];if(!c&&(c=cb._,!c))throw w("ITransientCollection.-conj!",a);return c.call(null,a,b)}function db(a){if(a?a.Ca:a)return a.Ca(a);var b;b=db[n(null==a?null:a)];if(!b&&(b=db._,!b))throw w("ITransientCollection.-persistent!",a);return b.call(null,a)}
function eb(a,b,c){if(a?a.ua:a)return a.ua(a,b,c);var d;d=eb[n(null==a?null:a)];if(!d&&(d=eb._,!d))throw w("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function fb(a,b,c){if(a?a.cb:a)return a.cb(0,b,c);var d;d=fb[n(null==a?null:a)];if(!d&&(d=fb._,!d))throw w("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function gb(a){if(a?a.Ya:a)return a.Ya();var b;b=gb[n(null==a?null:a)];if(!b&&(b=gb._,!b))throw w("IChunk.-drop-first",a);return b.call(null,a)}
function hb(a){if(a?a.Fa:a)return a.Fa(a);var b;b=hb[n(null==a?null:a)];if(!b&&(b=hb._,!b))throw w("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function ib(a){if(a?a.Ga:a)return a.Ga(a);var b;b=ib[n(null==a?null:a)];if(!b&&(b=ib._,!b))throw w("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function jb(a){if(a?a.Ea:a)return a.Ea(a);var b;b=jb[n(null==a?null:a)];if(!b&&(b=jb._,!b))throw w("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function kb(a){this.yb=a;this.o=0;this.g=1073741824}kb.prototype.fb=function(a,b){return this.yb.append(b)};function lb(a){var b=new ea;a.u(null,new kb(b),ia());return""+x(b)}function mb(a,b){if(s(G.a?G.a(a,b):G.call(null,a,b)))return 0;var c=pa(a.M);if(s(c?b.M:c))return-1;if(s(a.M)){if(pa(b.M))return 1;c=nb.a?nb.a(a.M,b.M):nb.call(null,a.M,b.M);return 0===c?nb.a?nb.a(a.name,b.name):nb.call(null,a.name,b.name):c}return ob?nb.a?nb.a(a.name,b.name):nb.call(null,a.name,b.name):null}
function pb(a,b,c,d,e){this.M=a;this.name=b;this.ia=c;this.ja=d;this.la=e;this.g=2154168321;this.o=4096}h=pb.prototype;h.u=function(a,b){return E(b,this.ia)};h.A=function(){var a=this.ja;return null!=a?a:this.ja=a=qb.a?qb.a(H.b?H.b(this.M):H.call(null,this.M),H.b?H.b(this.name):H.call(null,this.name)):qb.call(null,H.b?H.b(this.M):H.call(null,this.M),H.b?H.b(this.name):H.call(null,this.name))};h.D=function(a,b){return new pb(this.M,this.name,this.ia,this.ja,b)};h.B=function(){return this.la};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return Da.c(c,this,null);case 3:return Da.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return Da.c(a,this,null)};h.a=function(a,b){return Da.c(a,this,b)};h.v=function(a,b){return b instanceof pb?this.ia===b.ia:!1};h.toString=function(){return this.ia};
function I(a){if(null==a)return null;if(a&&(a.g&8388608||a.Hb))return a.C(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new rb(a,0);if(t(Wa,a))return Xa(a);if(u)throw Error([x(a),x("is not ISeqable")].join(""));return null}function J(a){if(null==a)return null;if(a&&(a.g&64||a.ta))return a.S(null);a=I(a);return null==a?null:C(a)}function K(a){return null!=a?a&&(a.g&64||a.ta)?a.T(null):(a=I(a))?D(a):L:L}
function M(a){return null==a?null:a&&(a.g&128||a.Gb)?a.ba(null):I(K(a))}
var G=function(){function a(a,b){return null==a?null==b:a===b||Ua(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(M(e))a=d,d=J(e),e=M(e);else return b.a(d,J(e));else return!1}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.e=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);
default:return c.e(b,e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.h=c.h;b.b=function(){return!0};b.a=a;b.e=c.e;return b}();va["null"]=!0;wa["null"]=function(){return 0};Date.prototype.v=function(a,b){return b instanceof Date&&this.toString()===b.toString()};Ua.number=function(a,b){return a===b};Oa["function"]=!0;Pa["function"]=function(){return null};ua["function"]=!0;Va._=function(a){return a[aa]||(a[aa]=++ca)};function sb(a){return a+1}
var tb=function(){function a(a,b,c,d){for(var l=wa(a);;)if(d<l)c=b.a?b.a(c,A.a(a,d)):b.call(null,c,A.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=wa(a),l=0;;)if(l<d)c=b.a?b.a(c,A.a(a,l)):b.call(null,c,A.a(a,l)),l+=1;else return c}function c(a,b){var c=wa(a);if(0===c)return b.q?b.q():b.call(null);for(var d=A.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,A.a(a,l)):b.call(null,d,A.a(a,l)),l+=1;else return d}var d=null,d=function(d,f,g,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,
d,f,g);case 4:return a.call(this,d,f,g,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.j=a;return d}(),ub=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.q?b.q():b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,f,g,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,g);case 4:return a.call(this,d,f,g,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.j=a;return d}();function vb(a){return a?a.g&2||a.jb?!0:a.g?!1:t(va,a):t(va,a)}function wb(a){return a?a.g&16||a.Za?!0:a.g?!1:t(Aa,a):t(Aa,a)}function rb(a,b){this.d=a;this.l=b;this.g=166199550;this.o=8192}h=rb.prototype;h.A=function(){return xb.b?xb.b(this):xb.call(null,this)};
h.ba=function(){return this.l+1<this.d.length?new rb(this.d,this.l+1):null};h.G=function(a,b){return O.a?O.a(b,this):O.call(null,b,this)};h.toString=function(){return lb(this)};h.P=function(a,b){return ub.j(this.d,b,this.d[this.l],this.l+1)};h.Q=function(a,b,c){return ub.j(this.d,b,c,this.l)};h.C=function(){return this};h.J=function(){return this.d.length-this.l};h.S=function(){return this.d[this.l]};h.T=function(){return this.l+1<this.d.length?new rb(this.d,this.l+1):L};
h.v=function(a,b){return yb.a?yb.a(this,b):yb.call(null,this,b)};h.H=function(a,b){var c=b+this.l;return c<this.d.length?this.d[c]:null};h.V=function(a,b,c){a=b+this.l;return a<this.d.length?this.d[a]:c};h.K=function(){return L};
var zb=function(){function a(a,b){return b<a.length?new rb(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}(),N=function(){function a(a,b){return zb.a(a,b)}function b(a){return zb.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.b=b;c.a=a;return c}();Ua._=function(a,b){return a===b};
var Ab=function(){function a(a,b){return null!=a?za(a,b):za(L,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(s(e))a=b.a(a,d),d=J(e),e=M(e);else return b.a(a,d)}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.e=c;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.e(b,e,N(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.m=2;b.h=c.h;b.a=a;b.e=c.e;return b}();function P(a){if(null!=a)if(a&&(a.g&2||a.jb))a=a.J(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(t(va,a))a=wa(a);else if(u)a:{a=I(a);for(var b=0;;){if(vb(a)){a=b+wa(a);break a}a=M(a);b+=1}a=void 0}else a=null;else a=0;return a}
var Bb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return I(a)?J(a):c;if(wb(a))return A.c(a,b,c);if(I(a))a=M(a),b-=1;else return u?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(I(a))return J(a);throw Error("Index out of bounds");}if(wb(a))return A.a(a,b);if(I(a)){var c=M(a),g=b-1;a=c;b=g}else{if(u)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),Q=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.g&16||a.Za))return a.V(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(t(Aa,a))return A.a(a,b);if(a?a.g&64||a.ta||(a.g?0:t(Ba,a)):t(Ba,a))return Bb.c(a,b,c);if(u)throw Error([x("nth not supported on this type "),x(ra(qa(a)))].join(""));return null}function b(a,
b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.g&16||a.Za))return a.H(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(t(Aa,a))return A.a(a,b);if(a?a.g&64||a.ta||(a.g?0:t(Ba,a)):t(Ba,a))return Bb.a(a,b);if(u)throw Error([x("nth not supported on this type "),x(ra(qa(a)))].join(""));return null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,
e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),R=function(){function a(a,b,c){return null!=a?a&&(a.g&256||a.$a)?a.O(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:t(Ca,a)?Da.c(a,b,c):u?c:null:c}function b(a,b){return null==a?null:a&&(a.g&256||a.$a)?a.N(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:t(Ca,a)?Da.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),S=function(){function a(a,b,c){return null!=a?Ea(a,b,c):Cb.a?Cb.a([b],[c]):Cb.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=N(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.c(a,d,e),s(l))d=J(l),e=J(M(l)),l=M(M(l));else return a}a.m=3;a.h=function(a){var b=J(a);a=M(a);var d=J(a);
a=M(a);var l=J(a);a=K(a);return c(b,d,l,a)};a.e=c;return a}(),b=function(b,e,f,g){switch(arguments.length){case 3:return a.call(this,b,e,f);default:return c.e(b,e,f,N(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.m=3;b.h=c.h;b.c=a;b.e=c.e;return b}(),Db=function(){function a(a,b){return null==a?null:Ga(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;){if(null==
a)return null;a=b.a(a,d);if(s(e))d=J(e),e=M(e);else return a}}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.e=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return b;case 2:return a.call(this,b,e);default:return c.e(b,e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.h=c.h;b.b=function(a){return a};b.a=a;b.e=c.e;return b}();function Eb(a){var b="function"==n(a);return b?b:a?s(s(null)?null:a.ib)?!0:a.Lb?!1:t(ua,a):t(ua,a)}
var Gb=function Fb(b,c){return Eb(b)&&!(b?b.g&262144||b.Kb||(b.g?0:t(Qa,b)):t(Qa,b))?Fb(function(){"undefined"===typeof fa&&(fa=function(b,c,f,g){this.i=b;this.ya=c;this.Ab=f;this.wb=g;this.o=0;this.g=393217},fa.Xa=!0,fa.Wa="cljs.core/t24238",fa.gb=function(b,c){return E(c,"cljs.core/t24238")},fa.prototype.call=function(){function b(d,g){d=this;var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,d,k)}function c(b,d){return T.a?T.a(b.ya,d):T.call(null,
b.ya,d)}b.m=1;b.h=function(b){var d=J(b);b=K(b);return c(d,b)};b.e=c;return b}(),fa.prototype.apply=function(b,c){return this.call.apply(this,[this].concat(z(c)))},fa.prototype.a=function(){function b(d){var g=null;0<arguments.length&&(g=N(Array.prototype.slice.call(arguments,0),0));return c.call(this,g)}function c(b){return T.a?T.a(self__.ya,b):T.call(null,self__.ya,b)}b.m=0;b.h=function(b){b=I(b);return c(b)};b.e=c;return b}(),fa.prototype.ib=!0,fa.prototype.B=function(){return this.wb},fa.prototype.D=
function(b,c){return new fa(this.i,this.ya,this.Ab,c)});return new fa(c,b,Fb,null)}(),c):null==b?null:Ra(b,c)};function Hb(a){var b=null!=a;return(b?a?a.g&131072||a.mb||(a.g?0:t(Oa,a)):t(Oa,a):b)?Pa(a):null}var Ib={},Jb=0;
function H(a){if(a&&(a.g&4194304||a.Eb))a=a.A(null);else if("number"===typeof a)a=Math.floor(a)%2147483647;else if(!0===a)a=1;else if(!1===a)a=0;else if("string"===typeof a){255<Jb&&(Ib={},Jb=0);var b=Ib[a];if("number"!==typeof b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;Ib[a]=b;Jb+=1}a=b}else a=null==a?0:u?Va(a):null;return a}function Kb(a){return a?a.g&16384||a.Jb?!0:a.g?!1:t(Ka,a):t(Ka,a)}function Lb(a){return a?a.o&512||a.Cb?!0:!1:!1}
function Mb(a){var b=[];da(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Nb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}var Ob={};function Pb(a){return null==a?!1:a?a.g&64||a.ta?!0:a.g?!1:t(Ba,a):t(Ba,a)}function Qb(a){return s(a)?!0:!1}function nb(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(qa(a)===qa(b))return a&&(a.o&2048||a.za)?a.Aa(null,b):a>b?1:a<b?-1:0;if(u)throw Error("compare on non-nil objects of different types");return null}
var Rb=function(){function a(a,b,c,g){for(;;){var k=nb(Q.a(a,g),Q.a(b,g));if(0===k&&g+1<c)g+=1;else return k}}function b(a,b){var f=P(a),g=P(b);return f<g?-1:f>g?1:u?c.j(a,b,f,0):null}var c=null,c=function(c,e,f,g){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,f,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.j=a;return c}(),Sb=function(){function a(a,b,c){for(c=I(c);;)if(c)b=a.a?a.a(b,J(c)):a.call(null,b,J(c)),c=M(c);else return b}function b(a,
b){var c=I(b);return c?sa.c?sa.c(a,J(c),M(c)):sa.call(null,a,J(c),M(c)):a.q?a.q():a.call(null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),sa=function(){function a(a,b,c){return c&&(c.g&524288||c.ob)?c.Q(null,a,b):c instanceof Array?ub.c(c,a,b):"string"===typeof c?ub.c(c,a,b):t(Sa,c)?Ta.c(c,a,b):u?Sb.c(a,b,c):null}function b(a,b){return b&&(b.g&524288||
b.ob)?b.P(null,a):b instanceof Array?ub.a(b,a):"string"===typeof b?ub.a(b,a):t(Sa,b)?Ta.a(b,a):u?Sb.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Tb(a){return 0<=a?Math.floor.b?Math.floor.b(a):Math.floor.call(null,a):Math.ceil.b?Math.ceil.b(a):Math.ceil.call(null,a)}
var Ub=function(){function a(a){return a*c.q()}function b(){return Math.random.q?Math.random.q():Math.random.call(null)}var c=null,c=function(c){switch(arguments.length){case 0:return b.call(this);case 1:return a.call(this,c)}throw Error("Invalid arity: "+arguments.length);};c.q=b;c.b=a;return c}();function Vb(a){return Tb(Ub.b(a))}function Wb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
function Xb(a){var b=1;for(a=I(a);;)if(a&&0<b)b-=1,a=M(a);else return a}
var x=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new ea(b.b(a)),l=d;;)if(s(l))e=e.append(b.b(J(l))),l=M(l);else return e.toString()}a.m=1;a.h=function(a){var b=J(a);a=K(a);return c(b,a)};a.e=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.e(b,N(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.h=c.h;b.q=function(){return""};b.b=a;b.e=c.e;return b}();function yb(a,b){return Qb((b?b.g&16777216||b.Ib||(b.g?0:t(Ya,b)):t(Ya,b))?function(){for(var c=I(a),d=I(b);;){if(null==c)return null==d;if(null==d)return!1;if(G.a(J(c),J(d)))c=M(c),d=M(d);else return u?!1:null}}():null)}function qb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function xb(a){if(I(a)){var b=H(J(a));for(a=M(a);;){if(null==a)return b;b=qb(b,H(J(a)));a=M(a)}}else return 0}function Yb(a){var b=0;for(a=I(a);;)if(a){var c=J(a),b=(b+(H(Zb.b?Zb.b(c):Zb.call(null,c))^H($b.b?$b.b(c):$b.call(null,c))))%4503599627370496;a=M(a)}else return b}function ac(a,b,c,d,e){this.i=a;this.va=b;this.ga=c;this.count=d;this.k=e;this.g=65937646;this.o=8192}h=ac.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){return 1===this.count?null:this.ga};
h.G=function(a,b){return new ac(this.i,b,this,this.count+1,null)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return this};h.J=function(){return this.count};h.S=function(){return this.va};h.T=function(){return 1===this.count?L:this.ga};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new ac(b,this.va,this.ga,this.count,this.k)};h.B=function(){return this.i};h.K=function(){return L};
function bc(a){this.i=a;this.g=65937614;this.o=8192}h=bc.prototype;h.A=function(){return 0};h.ba=function(){return null};h.G=function(a,b){return new ac(this.i,b,null,1,null)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return null};h.J=function(){return 0};h.S=function(){return null};h.T=function(){return L};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new bc(b)};h.B=function(){return this.i};
h.K=function(){return this};var L=new bc(null),dc=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof rb&&0===a.l)b=a.d;else a:{for(b=[];;)if(null!=a)b.push(a.S(null)),a=a.ba(null);else break a;b=void 0}a=b.length;for(var e=L;;)if(0<a){var f=a-1,e=e.G(null,b[a-1]);a=f}else return e}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();
function ec(a,b,c,d){this.i=a;this.va=b;this.ga=c;this.k=d;this.g=65929452;this.o=8192}h=ec.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){return null==this.ga?null:I(this.ga)};h.G=function(a,b){return new ec(null,b,this,this.k)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return this};h.S=function(){return this.va};h.T=function(){return null==this.ga?L:this.ga};
h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new ec(b,this.va,this.ga,this.k)};h.B=function(){return this.i};h.K=function(){return Gb(L,this.i)};function O(a,b){var c=null==b;return(c?c:b&&(b.g&64||b.ta))?new ec(null,a,b,null):new ec(null,a,I(b),null)}function U(a,b,c,d){this.M=a;this.name=b;this.ha=c;this.ja=d;this.g=2153775105;this.o=4096}h=U.prototype;h.u=function(a,b){return E(b,[x(":"),x(this.ha)].join(""))};
h.A=function(){null==this.ja&&(this.ja=qb(H(this.M),H(this.name))+2654435769);return this.ja};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return R.a(c,this);case 3:return R.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return R.a(a,this)};h.a=function(a,b){return R.c(a,this,b)};h.v=function(a,b){return b instanceof U?this.ha===b.ha:!1};
h.toString=function(){return[x(":"),x(this.ha)].join("")};
var gc=function(){function a(a,b){return new U(a,b,[x(s(a)?[x(a),x("/")].join(""):null),x(b)].join(""),null)}function b(a){if(a instanceof U)return a;if(a instanceof pb){var b;if(a&&(a.o&4096||a.nb))b=a.M;else throw Error([x("Doesn't support namespace: "),x(a)].join(""));return new U(b,fc.b?fc.b(a):fc.call(null,a),a.ia,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new U(b[0],b[1],a,null):new U(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,
c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}();function hc(a,b,c,d){this.i=a;this.pa=b;this.r=c;this.k=d;this.o=0;this.g=32374988}h=hc.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){Xa(this);return null==this.r?null:M(this.r)};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};function ic(a){null!=a.pa&&(a.r=a.pa.q?a.pa.q():a.pa.call(null),a.pa=null);return a.r}
h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){ic(this);if(null==this.r)return null;for(var a=this.r;;)if(a instanceof hc)a=ic(a);else return this.r=a,I(this.r)};h.S=function(){Xa(this);return null==this.r?null:J(this.r)};h.T=function(){Xa(this);return null!=this.r?K(this.r):L};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new hc(b,this.pa,this.r,this.k)};h.B=function(){return this.i};h.K=function(){return Gb(L,this.i)};
function jc(a,b){this.Da=a;this.end=b;this.o=0;this.g=2}jc.prototype.J=function(){return this.end};jc.prototype.add=function(a){this.Da[this.end]=a;return this.end+=1};jc.prototype.F=function(){var a=new kc(this.Da,0,this.end);this.Da=null;return a};function lc(a){return new jc(Array(a),0)}function kc(a,b,c){this.d=a;this.s=b;this.end=c;this.o=0;this.g=524306}h=kc.prototype;h.P=function(a,b){return ub.j(this.d,b,this.d[this.s],this.s+1)};h.Q=function(a,b,c){return ub.j(this.d,b,c,this.s)};
h.Ya=function(){if(this.s===this.end)throw Error("-drop-first of empty chunk");return new kc(this.d,this.s+1,this.end)};h.H=function(a,b){return this.d[this.s+b]};h.V=function(a,b,c){return 0<=b&&b<this.end-this.s?this.d[this.s+b]:c};h.J=function(){return this.end-this.s};
var mc=function(){function a(a,b,c){return new kc(a,b,c)}function b(a,b){return new kc(a,b,a.length)}function c(a){return new kc(a,0,a.length)}var d=null,d=function(d,f,g){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}throw Error("Invalid arity: "+arguments.length);};d.b=c;d.a=b;d.c=a;return d}();function nc(a,b,c,d){this.F=a;this.ca=b;this.i=c;this.k=d;this.g=31850732;this.o=1536}h=nc.prototype;
h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){if(1<wa(this.F))return new nc(gb(this.F),this.ca,this.i,null);var a=Xa(this.ca);return null==a?null:a};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};h.C=function(){return this};h.S=function(){return A.a(this.F,0)};h.T=function(){return 1<wa(this.F)?new nc(gb(this.F),this.ca,this.i,null):null==this.ca?L:this.ca};h.Ea=function(){return null==this.ca?null:this.ca};
h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new nc(this.F,this.ca,b,this.k)};h.B=function(){return this.i};h.K=function(){return Gb(L,this.i)};h.Fa=function(){return this.F};h.Ga=function(){return null==this.ca?L:this.ca};function oc(a,b){return 0===wa(a)?b:new nc(a,b,null,null)}function pc(a,b){a.add(b)}function qc(a){for(var b=[];;)if(I(a))b.push(J(a)),a=M(a);else return b}function rc(a,b){if(vb(a))return P(a);for(var c=a,d=b,e=0;;)if(0<d&&I(c))c=M(c),d-=1,e+=1;else return e}
var tc=function sc(b){return null==b?null:null==M(b)?I(J(b)):u?O(J(b),sc(M(b))):null},uc=function(){function a(a,b){return new hc(null,function(){var c=I(a);return c?Lb(c)?oc(hb(c),d.a(ib(c),b)):O(J(c),d.a(K(c),b)):b},null,null)}function b(a){return new hc(null,function(){return a},null,null)}function c(){return new hc(null,function(){return null},null,null)}var d=null,e=function(){function a(c,d,e){var f=null;2<arguments.length&&(f=N(Array.prototype.slice.call(arguments,2),0));return b.call(this,
c,d,f)}function b(a,c,e){return function q(a,b){return new hc(null,function(){var c=I(a);return c?Lb(c)?oc(hb(c),q(ib(c),b)):O(J(c),q(K(c),b)):s(b)?q(J(b),M(b)):null},null,null)}(d.a(a,c),e)}a.m=2;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=K(a);return b(c,d,a)};a.e=b;return a}(),d=function(d,g,k){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,d);case 2:return a.call(this,d,g);default:return e.e(d,g,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);
};d.m=2;d.h=e.h;d.q=c;d.b=b;d.a=a;d.e=e.e;return d}(),vc=function(){function a(a,b,c,d){return O(a,O(b,O(c,d)))}function b(a,b,c){return O(a,O(b,c))}var c=null,d=function(){function a(c,d,e,m,p){var q=null;4<arguments.length&&(q=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,q)}function b(a,c,d,e,f){return O(a,O(c,O(d,O(e,tc(f)))))}a.m=4;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var p=J(a);a=K(a);return b(c,d,e,p,a)};a.e=b;return a}(),c=function(c,
f,g,k,l){switch(arguments.length){case 1:return I(c);case 2:return O(c,f);case 3:return b.call(this,c,f,g);case 4:return a.call(this,c,f,g,k);default:return d.e(c,f,g,k,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.m=4;c.h=d.h;c.b=function(a){return I(a)};c.a=function(a,b){return O(a,b)};c.c=b;c.j=a;c.e=d.e;return c}(),wc=function(){var a=null,b=function(){function a(c,f,g){var k=null;2<arguments.length&&(k=N(Array.prototype.slice.call(arguments,2),0));return b.call(this,c,f,
k)}function b(a,c,d){for(;;)if(a=cb(a,c),s(d))c=J(d),d=M(d);else return a}a.m=2;a.h=function(a){var c=J(a);a=M(a);var g=J(a);a=K(a);return b(c,g,a)};a.e=b;return a}(),a=function(a,d,e){switch(arguments.length){case 2:return cb(a,d);default:return b.e(a,d,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};a.m=2;a.h=b.h;a.a=function(a,b){return cb(a,b)};a.e=b.e;return a}(),xc=function(){var a=null,b=function(){function a(c,f,g,k){var l=null;3<arguments.length&&(l=N(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,f,g,l)}function b(a,c,d,k){for(;;)if(a=eb(a,c,d),s(k))c=J(k),d=J(M(k)),k=M(M(k));else return a}a.m=3;a.h=function(a){var c=J(a);a=M(a);var g=J(a);a=M(a);var k=J(a);a=K(a);return b(c,g,k,a)};a.e=b;return a}(),a=function(a,d,e,f){switch(arguments.length){case 3:return eb(a,d,e);default:return b.e(a,d,e,N(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.m=3;a.h=b.h;a.c=function(a,b,e){return eb(a,b,e)};a.e=b.e;return a}();
function yc(a,b,c){var d=I(c);if(0===b)return a.q?a.q():a.call(null);c=C(d);var e=D(d);if(1===b)return a.b?a.b(c):a.b?a.b(c):a.call(null,c);var d=C(e),f=D(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=C(f),g=D(f);if(3===b)return a.c?a.c(c,d,e):a.c?a.c(c,d,e):a.call(null,c,d,e);var f=C(g),k=D(g);if(4===b)return a.j?a.j(c,d,e,f):a.j?a.j(c,d,e,f):a.call(null,c,d,e,f);var g=C(k),l=D(k);if(5===b)return a.w?a.w(c,d,e,f,g):a.w?a.w(c,d,e,f,g):a.call(null,c,d,e,f,g);var k=C(l),m=D(l);
if(6===b)return a.Y?a.Y(c,d,e,f,g,k):a.Y?a.Y(c,d,e,f,g,k):a.call(null,c,d,e,f,g,k);var l=C(m),p=D(m);if(7===b)return a.ma?a.ma(c,d,e,f,g,k,l):a.ma?a.ma(c,d,e,f,g,k,l):a.call(null,c,d,e,f,g,k,l);var m=C(p),q=D(p);if(8===b)return a.Sa?a.Sa(c,d,e,f,g,k,l,m):a.Sa?a.Sa(c,d,e,f,g,k,l,m):a.call(null,c,d,e,f,g,k,l,m);var p=C(q),v=D(q);if(9===b)return a.Ta?a.Ta(c,d,e,f,g,k,l,m,p):a.Ta?a.Ta(c,d,e,f,g,k,l,m,p):a.call(null,c,d,e,f,g,k,l,m,p);var q=C(v),F=D(v);if(10===b)return a.Ha?a.Ha(c,d,e,f,g,k,l,m,p,q):a.Ha?
a.Ha(c,d,e,f,g,k,l,m,p,q):a.call(null,c,d,e,f,g,k,l,m,p,q);var v=C(F),y=D(F);if(11===b)return a.Ia?a.Ia(c,d,e,f,g,k,l,m,p,q,v):a.Ia?a.Ia(c,d,e,f,g,k,l,m,p,q,v):a.call(null,c,d,e,f,g,k,l,m,p,q,v);var F=C(y),B=D(y);if(12===b)return a.Ja?a.Ja(c,d,e,f,g,k,l,m,p,q,v,F):a.Ja?a.Ja(c,d,e,f,g,k,l,m,p,q,v,F):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F);var y=C(B),X=D(B);if(13===b)return a.Ka?a.Ka(c,d,e,f,g,k,l,m,p,q,v,F,y):a.Ka?a.Ka(c,d,e,f,g,k,l,m,p,q,v,F,y):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y);var B=C(X),ba=D(X);
if(14===b)return a.La?a.La(c,d,e,f,g,k,l,m,p,q,v,F,y,B):a.La?a.La(c,d,e,f,g,k,l,m,p,q,v,F,y,B):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B);var X=C(ba),ma=D(ba);if(15===b)return a.Ma?a.Ma(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X):a.Ma?a.Ma(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B,X);var ba=C(ma),ya=D(ma);if(16===b)return a.Na?a.Na(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba):a.Na?a.Na(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba);var ma=C(ya),Na=D(ya);if(17===
b)return a.Oa?a.Oa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma):a.Oa?a.Oa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma);var ya=C(Na),cc=D(Na);if(18===b)return a.Pa?a.Pa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya):a.Pa?a.Pa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya);Na=C(cc);cc=D(cc);if(19===b)return a.Qa?a.Qa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na):a.Qa?a.Qa(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na):a.call(null,c,d,e,
f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na);var ad=C(cc);D(cc);if(20===b)return a.Ra?a.Ra(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na,ad):a.Ra?a.Ra(c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na,ad):a.call(null,c,d,e,f,g,k,l,m,p,q,v,F,y,B,X,ba,ma,ya,Na,ad);throw Error("Only up to 20 arguments supported on functions");}
var T=function(){function a(a,b,c,d,e){b=vc.j(b,c,d,e);c=a.m;return a.h?(d=rc(b,c+1),d<=c?yc(a,d,b):a.h(b)):a.apply(a,qc(b))}function b(a,b,c,d){b=vc.c(b,c,d);c=a.m;return a.h?(d=rc(b,c+1),d<=c?yc(a,d,b):a.h(b)):a.apply(a,qc(b))}function c(a,b,c){b=vc.a(b,c);c=a.m;if(a.h){var d=rc(b,c+1);return d<=c?yc(a,d,b):a.h(b)}return a.apply(a,qc(b))}function d(a,b){var c=a.m;if(a.h){var d=rc(b,c+1);return d<=c?yc(a,d,b):a.h(b)}return a.apply(a,qc(b))}var e=null,f=function(){function a(c,d,e,f,g,F){var y=null;
5<arguments.length&&(y=N(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,f,g,y)}function b(a,c,d,e,f,g){c=O(c,O(d,O(e,O(f,tc(g)))));d=a.m;return a.h?(e=rc(c,d+1),e<=d?yc(a,e,c):a.h(c)):a.apply(a,qc(c))}a.m=5;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=M(a);var g=J(a);a=K(a);return b(c,d,e,f,g,a)};a.e=b;return a}(),e=function(e,k,l,m,p,q){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,p);default:return f.e(e,k,l,m,p,N(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.m=5;e.h=f.h;e.a=d;e.c=c;e.j=b;e.w=a;e.e=f.e;return e}();function zc(a,b){for(;;){if(null==I(b))return!0;if(s(a.b?a.b(J(b)):a.call(null,J(b)))){var c=a,d=M(b);a=c;b=d}else return u?!1:null}}function Ac(a){for(var b=Bc;;)if(I(a)){var c=b.b?b.b(J(a)):b.call(null,J(a));if(s(c))return c;a=M(a)}else return null}function Bc(a){return a}
var Cc=function(){function a(a,b,c,e){return new hc(null,function(){var m=I(b),p=I(c),q=I(e);return m&&p&&q?O(a.c?a.c(J(m),J(p),J(q)):a.call(null,J(m),J(p),J(q)),d.j(a,K(m),K(p),K(q))):null},null,null)}function b(a,b,c){return new hc(null,function(){var e=I(b),m=I(c);return e&&m?O(a.a?a.a(J(e),J(m)):a.call(null,J(e),J(m)),d.c(a,K(e),K(m))):null},null,null)}function c(a,b){return new hc(null,function(){var c=I(b);if(c){if(Lb(c)){for(var e=hb(c),m=P(e),p=lc(m),q=0;;)if(q<m){var v=a.b?a.b(A.a(e,q)):
a.call(null,A.a(e,q));p.add(v);q+=1}else break;return oc(p.F(),d.a(a,ib(c)))}return O(a.b?a.b(J(c)):a.call(null,J(c)),d.a(a,K(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,f,q){var v=null;4<arguments.length&&(v=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,v)}function b(a,c,e,f,g){var v=function y(a){return new hc(null,function(){var b=d.a(I,a);return zc(Bc,b)?O(d.a(J,b),y(d.a(K,b))):null},null,null)};return d.a(function(){return function(b){return T.a(a,
b)}}(v),v(Ab.e(g,f,N([e,c],0))))}a.m=4;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=K(a);return b(c,d,e,f,a)};a.e=b;return a}(),d=function(d,g,k,l,m){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,d,g,k);case 4:return a.call(this,d,g,k,l);default:return e.e(d,g,k,l,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.h=e.h;d.a=c;d.c=b;d.j=a;d.e=e.e;return d}(),Dc=function(){function a(a,b,c){var g=Ob;for(b=
I(b);;)if(b){var k=a;if(k?k.g&256||k.$a||(k.g?0:t(Ca,k)):t(Ca,k)){a=R.c(a,J(b),g);if(g===a)return c;b=M(b)}else return c}else return a}function b(a,b){return c.c(a,b,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),Fc=function Ec(b,c,d){var e=Q.c(c,0,null);return(c=Xb(c))?S.c(b,e,Ec(R.a(b,e),c,d)):S.c(b,e,d)},Gc=function(){function a(a,b,c,d,f,q){var v=
Q.c(b,0,null);return(b=Xb(b))?S.c(a,v,e.Y(R.a(a,v),b,c,d,f,q)):S.c(a,v,c.j?c.j(R.a(a,v),d,f,q):c.call(null,R.a(a,v),d,f,q))}function b(a,b,c,d,f){var q=Q.c(b,0,null);return(b=Xb(b))?S.c(a,q,e.w(R.a(a,q),b,c,d,f)):S.c(a,q,c.c?c.c(R.a(a,q),d,f):c.call(null,R.a(a,q),d,f))}function c(a,b,c,d){var f=Q.c(b,0,null);return(b=Xb(b))?S.c(a,f,e.j(R.a(a,f),b,c,d)):S.c(a,f,c.a?c.a(R.a(a,f),d):c.call(null,R.a(a,f),d))}function d(a,b,c){var d=Q.c(b,0,null);return(b=Xb(b))?S.c(a,d,e.c(R.a(a,d),b,c)):S.c(a,d,c.b?
c.b(R.a(a,d)):c.call(null,R.a(a,d)))}var e=null,f=function(){function a(c,d,e,f,g,F,y){var B=null;6<arguments.length&&(B=N(Array.prototype.slice.call(arguments,6),0));return b.call(this,c,d,e,f,g,F,B)}function b(a,c,d,f,g,k,y){var B=Q.c(c,0,null);return(c=Xb(c))?S.c(a,B,T.e(e,R.a(a,B),c,d,f,N([g,k,y],0))):S.c(a,B,T.e(d,R.a(a,B),f,g,k,N([y],0)))}a.m=6;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=M(a);var g=J(a);a=M(a);var y=J(a);a=K(a);return b(c,d,e,f,g,y,a)};
a.e=b;return a}(),e=function(e,k,l,m,p,q,v){switch(arguments.length){case 3:return d.call(this,e,k,l);case 4:return c.call(this,e,k,l,m);case 5:return b.call(this,e,k,l,m,p);case 6:return a.call(this,e,k,l,m,p,q);default:return f.e(e,k,l,m,p,q,N(arguments,6))}throw Error("Invalid arity: "+arguments.length);};e.m=6;e.h=f.h;e.c=d;e.j=c;e.w=b;e.Y=a;e.e=f.e;return e}();function Hc(a,b){this.n=a;this.d=b}
function Ic(a){return new Hc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Jc(a){a=a.f;return 32>a?0:a-1>>>5<<5}function Kc(a,b,c){for(;;){if(0===b)return c;var d=Ic(a);d.d[0]=c;c=d;b-=5}}var Mc=function Lc(b,c,d,e){var f=new Hc(d.n,z(d.d)),g=b.f-1>>>c&31;5===c?f.d[g]=e:(d=d.d[g],b=null!=d?Lc(b,c-5,d,e):Kc(null,c-5,e),f.d[g]=b);return f};
function Nc(a,b){throw Error([x("No item "),x(a),x(" in vector of length "),x(b)].join(""));}function Oc(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.d[0];else return b.d}function Pc(a,b){if(b>=Jc(a))return a.I;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.d[b>>>d&31],d=e;else return c.d}function Qc(a,b){return 0<=b&&b<a.f?Pc(a,b):Nc(b,a.f)}var Sc=function Rc(b,c,d,e,f){var g=new Hc(d.n,z(d.d));if(0===c)g.d[e&31]=f;else{var k=e>>>c&31;b=Rc(b,c-5,d.d[k],e,f);g.d[k]=b}return g};
function V(a,b,c,d,e,f){this.i=a;this.f=b;this.shift=c;this.root=d;this.I=e;this.k=f;this.o=8196;this.g=167668511}h=V.prototype;h.sa=function(){return new Tc(this.f,this.shift,Uc.b?Uc.b(this.root):Uc.call(null,this.root),Vc.b?Vc.b(this.I):Vc.call(null,this.I))};h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};
h.ra=function(a,b,c){if("number"===typeof b)return La(this,b,c);throw Error("Vector's key for assoc must be a number.");};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.H(null,c);case 3:return this.V(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return this.H(null,a)};h.a=function(a,b){return this.V(null,a,b)};
h.G=function(a,b){if(32>this.f-Jc(this)){for(var c=this.I.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.I[e],e+=1;else break;d[c]=b;return new V(this.i,this.f+1,this.shift,this.root,d,null)}c=(d=this.f>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Ic(null),d.d[0]=this.root,e=Kc(null,this.shift,new Hc(null,this.I)),d.d[1]=e):d=Mc(this,this.shift,this.root,new Hc(null,this.I));return new V(this.i,this.f+1,c,d,[b],null)};h.ab=function(){return A.a(this,0)};h.bb=function(){return A.a(this,1)};
h.toString=function(){return lb(this)};h.P=function(a,b){return tb.a(this,b)};h.Q=function(a,b,c){return tb.c(this,b,c)};h.C=function(){return 0===this.f?null:32>=this.f?new rb(this.I,0):u?Wc.j?Wc.j(this,Oc(this),0,0):Wc.call(null,this,Oc(this),0,0):null};h.J=function(){return this.f};
h.Va=function(a,b,c){if(0<=b&&b<this.f)return Jc(this)<=b?(a=z(this.I),a[b&31]=c,new V(this.i,this.f,this.shift,this.root,a,null)):new V(this.i,this.f,this.shift,Sc(this,this.shift,this.root,b,c),this.I,null);if(b===this.f)return za(this,c);if(u)throw Error([x("Index "),x(b),x(" out of bounds  [0,"),x(this.f),x("]")].join(""));return null};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new V(b,this.f,this.shift,this.root,this.I,this.k)};h.B=function(){return this.i};
h.H=function(a,b){return Qc(this,b)[b&31]};h.V=function(a,b,c){return 0<=b&&b<this.f?Pc(this,b)[b&31]:c};h.K=function(){return Gb(Xc,this.i)};var W=new Hc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Xc=new V(null,0,5,W,[],0);
function Yc(a,b){var c=a.length,d=b?a:z(a);if(32>c)return new V(null,c,5,W,d,null);for(var e=d.slice(0,32),f=32,g=(new V(null,32,5,W,e,null)).sa(null);;)if(f<c)e=f+1,g=wc.a(g,d[f]),f=e;else return db(g)}var Zc=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return a instanceof rb&&0===a.l?Yc.a?Yc.a(a.d,!0):Yc.call(null,a.d,!0):db(sa.c(cb,bb(Xc),a))}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();
function $c(a,b,c,d,e,f){this.t=a;this.W=b;this.l=c;this.s=d;this.i=e;this.k=f;this.g=32243948;this.o=1536}h=$c.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){if(this.s+1<this.W.length){var a=Wc.j?Wc.j(this.t,this.W,this.l,this.s+1):Wc.call(null,this.t,this.W,this.l,this.s+1);return null==a?null:a}return jb(this)};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};
h.P=function(a,b){return tb.a(bd.c?bd.c(this.t,this.l+this.s,P(this.t)):bd.call(null,this.t,this.l+this.s,P(this.t)),b)};h.Q=function(a,b,c){return tb.c(bd.c?bd.c(this.t,this.l+this.s,P(this.t)):bd.call(null,this.t,this.l+this.s,P(this.t)),b,c)};h.C=function(){return this};h.S=function(){return this.W[this.s]};h.T=function(){if(this.s+1<this.W.length){var a=Wc.j?Wc.j(this.t,this.W,this.l,this.s+1):Wc.call(null,this.t,this.W,this.l,this.s+1);return null==a?L:a}return ib(this)};
h.Ea=function(){var a=this.l+this.W.length;return a<wa(this.t)?Wc.j?Wc.j(this.t,Pc(this.t,a),a,0):Wc.call(null,this.t,Pc(this.t,a),a,0):null};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return Wc.w?Wc.w(this.t,this.W,this.l,this.s,b):Wc.call(null,this.t,this.W,this.l,this.s,b)};h.K=function(){return Gb(Xc,this.i)};h.Fa=function(){return mc.a(this.W,this.s)};
h.Ga=function(){var a=this.l+this.W.length;return a<wa(this.t)?Wc.j?Wc.j(this.t,Pc(this.t,a),a,0):Wc.call(null,this.t,Pc(this.t,a),a,0):L};
var Wc=function(){function a(a,b,c,d,l){return new $c(a,b,c,d,l,null)}function b(a,b,c,d){return new $c(a,b,c,d,null,null)}function c(a,b,c){return new $c(a,Qc(a,b),b,c,null,null)}var d=null,d=function(d,f,g,k,l){switch(arguments.length){case 3:return c.call(this,d,f,g);case 4:return b.call(this,d,f,g,k);case 5:return a.call(this,d,f,g,k,l)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.j=b;d.w=a;return d}();
function cd(a,b,c,d,e){this.i=a;this.da=b;this.start=c;this.end=d;this.k=e;this.g=166617887;this.o=8192}h=cd.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};h.ra=function(a,b,c){if("number"===typeof b)return La(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.H(null,c);case 3:return this.V(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return this.H(null,a)};h.a=function(a,b){return this.V(null,a,b)};
h.G=function(a,b){return dd.w?dd.w(this.i,La(this.da,this.end,b),this.start,this.end+1,null):dd.call(null,this.i,La(this.da,this.end,b),this.start,this.end+1,null)};h.toString=function(){return lb(this)};h.P=function(a,b){return tb.a(this,b)};h.Q=function(a,b,c){return tb.c(this,b,c)};h.C=function(){var a=this;return function(b){return function d(e){return e===a.end?null:O(A.a(a.da,e),new hc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
h.J=function(){return this.end-this.start};h.Va=function(a,b,c){var d=this,e=d.start+b;return dd.w?dd.w(d.i,S.c(d.da,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):dd.call(null,d.i,S.c(d.da,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return dd.w?dd.w(b,this.da,this.start,this.end,this.k):dd.call(null,b,this.da,this.start,this.end,this.k)};h.B=function(){return this.i};
h.H=function(a,b){return 0>b||this.end<=this.start+b?Nc(b,this.end-this.start):A.a(this.da,this.start+b)};h.V=function(a,b,c){return 0>b||this.end<=this.start+b?c:A.c(this.da,this.start+b,c)};h.K=function(){return Gb(Xc,this.i)};function dd(a,b,c,d,e){for(;;)if(b instanceof cd)c=b.start+c,d=b.start+d,b=b.da;else{var f=P(b);if(0>c||0>d||c>f||d>f)throw Error("Index out of bounds");return new cd(a,b,c,d,e)}}
var bd=function(){function a(a,b,c){return dd(null,a,b,c,null)}function b(a,b){return c.c(a,b,P(a))}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Uc(a){return new Hc({},z(a.d))}
function Vc(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Nb(a,0,b,0,a.length);return b}var fd=function ed(b,c,d,e){d=b.root.n===d.n?d:new Hc(b.root.n,z(d.d));var f=b.f-1>>>c&31;if(5===c)b=e;else{var g=d.d[f];b=null!=g?ed(b,c-5,g,e):Kc(b.root.n,c-5,e)}d.d[f]=b;return d};function Tc(a,b,c,d){this.f=a;this.shift=b;this.root=c;this.I=d;this.g=275;this.o=88}h=Tc.prototype;
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return this.N(null,a)};h.a=function(a,b){return this.O(null,a,b)};h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){return"number"===typeof b?A.c(this,b,c):c};
h.H=function(a,b){if(this.root.n)return Qc(this,b)[b&31];throw Error("nth after persistent!");};h.V=function(a,b,c){return 0<=b&&b<this.f?A.a(this,b):c};h.J=function(){if(this.root.n)return this.f;throw Error("count after persistent!");};
h.cb=function(a,b,c){var d=this;if(d.root.n){if(0<=b&&b<d.f)return Jc(this)<=b?d.I[b&31]=c:(a=function(){return function f(a,k){var l=d.root.n===k.n?k:new Hc(d.root.n,z(k.d));if(0===a)l.d[b&31]=c;else{var m=b>>>a&31,p=f(a-5,l.d[m]);l.d[m]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.f)return cb(this,c);if(u)throw Error([x("Index "),x(b),x(" out of bounds for TransientVector of length"),x(d.f)].join(""));return null}throw Error("assoc! after persistent!");};
h.ua=function(a,b,c){if("number"===typeof b)return fb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
h.Ba=function(a,b){if(this.root.n){if(32>this.f-Jc(this))this.I[this.f&31]=b;else{var c=new Hc(this.root.n,this.I),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.I=d;if(this.f>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Kc(this.root.n,this.shift,c);this.root=new Hc(this.root.n,d);this.shift=e}else this.root=fd(this,this.shift,this.root,c)}this.f+=1;return this}throw Error("conj! after persistent!");};h.Ca=function(){if(this.root.n){this.root.n=null;var a=this.f-Jc(this),b=Array(a);Nb(this.I,0,b,0,a);return new V(null,this.f,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function gd(){this.o=0;this.g=2097152}gd.prototype.v=function(){return!1};var hd=new gd;
function id(a,b){return Qb((null==b?0:b?b.g&1024||b.Fb||(b.g?0:t(Fa,b)):t(Fa,b))?P(a)===P(b)?zc(Bc,Cc.a(function(a){return G.a(R.c(b,J(a),hd),J(M(a)))},a)):null:null)}
function jd(a,b){var c=a.d;if(b instanceof U)a:{for(var d=c.length,e=b.ha,f=0;;){if(d<=f){c=-1;break a}var g=c[f];if(g instanceof U&&e===g.ha){c=f;break a}if(u)f+=2;else{c=null;break a}}c=void 0}else if("string"==typeof b||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof pb)a:{d=c.length;e=b.ia;for(f=0;;){if(d<=f){c=-1;break a}g=c[f];if(g instanceof pb&&e===g.ia){c=f;break a}if(u)f+=2;else{c=null;
break a}}c=void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else if(u)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(G.a(b,c[e])){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function kd(a,b,c){this.d=a;this.l=b;this.la=c;this.o=0;this.g=32374990}h=kd.prototype;h.A=function(){return xb(this)};h.ba=function(){return this.l<this.d.length-2?new kd(this.d,this.l+2,this.la):null};
h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return this};h.J=function(){return(this.d.length-this.l)/2};h.S=function(){return new V(null,2,5,W,[this.d[this.l],this.d[this.l+1]],null)};h.T=function(){return this.l<this.d.length-2?new kd(this.d,this.l+2,this.la):L};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new kd(this.d,this.l,b)};h.B=function(){return this.la};
h.K=function(){return Gb(L,this.la)};function r(a,b,c,d){this.i=a;this.f=b;this.d=c;this.k=d;this.o=8196;this.g=16123663}h=r.prototype;h.sa=function(){return new ld({},this.d.length,z(this.d))};h.A=function(){var a=this.k;return null!=a?a:this.k=a=Yb(this)};h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){a=jd(this,b);return-1===a?c:this.d[a+1]};
h.ra=function(a,b,c){a=jd(this,b);if(-1===a){if(this.f<md){a=this.d;for(var d=a.length,e=Array(d+2),f=0;;)if(f<d)e[f]=a[f],f+=1;else break;e[d]=b;e[d+1]=c;return new r(this.i,this.f+1,e,null)}a=Ra;d=Ea;e=nd;null!=e?e&&(e.o&4||e.Db)?(e=sa.c(cb,bb(e),this),e=db(e)):e=sa.c(za,e,this):e=sa.c(Ab,L,this);return a(d(e,b,c),this.i)}return c===this.d[a+1]?this:u?(b=z(this.d),b[a+1]=c,new r(this.i,this.f,b,null)):null};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return this.N(null,a)};h.a=function(a,b){return this.O(null,a,b)};h.G=function(a,b){return Kb(b)?Ea(this,A.a(b,0),A.a(b,1)):sa.c(za,this,b)};h.toString=function(){return lb(this)};
h.C=function(){return 0<=this.d.length-2?new kd(this.d,0,null):null};h.J=function(){return this.f};h.v=function(a,b){return id(this,b)};h.D=function(a,b){return new r(b,this.f,this.d,this.k)};h.B=function(){return this.i};h.K=function(){return Ra(od,this.i)};
h.Ua=function(a,b){if(0<=jd(this,b)){var c=this.d.length,d=c-2;if(0===d)return xa(this);for(var d=Array(d),e=0,f=0;;){if(e>=c)return new r(this.i,this.f-1,d,null);if(G.a(b,this.d[e]))e+=2;else if(u)d[f]=this.d[e],d[f+1]=this.d[e+1],f+=2,e+=2;else return null}}else return this};var od=new r(null,0,[],null),md=8;function ld(a,b,c){this.na=a;this.fa=b;this.d=c;this.o=56;this.g=258}h=ld.prototype;
h.ua=function(a,b,c){if(s(this.na)){a=jd(this,b);if(-1===a)return this.fa+2<=2*md?(this.fa+=2,this.d.push(b),this.d.push(c),this):xc.c(pd.a?pd.a(this.fa,this.d):pd.call(null,this.fa,this.d),b,c);c!==this.d[a+1]&&(this.d[a+1]=c);return this}throw Error("assoc! after persistent!");};
h.Ba=function(a,b){if(s(this.na)){if(b?b.g&2048||b.lb||(b.g?0:t(Ha,b)):t(Ha,b))return eb(this,Zb.b?Zb.b(b):Zb.call(null,b),$b.b?$b.b(b):$b.call(null,b));for(var c=I(b),d=this;;){var e=J(c);if(s(e))c=M(c),d=eb(d,Zb.b?Zb.b(e):Zb.call(null,e),$b.b?$b.b(e):$b.call(null,e));else return d}}else throw Error("conj! after persistent!");};h.Ca=function(){if(s(this.na))return this.na=!1,new r(null,Tb((this.fa-this.fa%2)/2),this.d,null);throw Error("persistent! called twice");};
h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){if(s(this.na))return a=jd(this,b),-1===a?c:this.d[a+1];throw Error("lookup after persistent!");};h.J=function(){if(s(this.na))return Tb((this.fa-this.fa%2)/2);throw Error("count after persistent!");};function pd(a,b){for(var c=bb(nd),d=0;;)if(d<a)c=xc.c(c,b[d],b[d+1]),d+=2;else return c}function qd(){this.X=!1}function rd(a,b){return a===b?!0:a===b||a instanceof U&&b instanceof U&&a.ha===b.ha?!0:u?G.a(a,b):null}
var sd=function(){function a(a,b,c,g,k){a=z(a);a[b]=c;a[g]=k;return a}function b(a,b,c){a=z(a);a[b]=c;return a}var c=null,c=function(c,e,f,g,k){switch(arguments.length){case 3:return b.call(this,c,e,f);case 5:return a.call(this,c,e,f,g,k)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.w=a;return c}();function td(a,b){var c=Array(a.length-2);Nb(a,0,c,0,2*b);Nb(a,2*(b+1),c,2*b,c.length-2*b);return c}
var ud=function(){function a(a,b,c,g,k,l){a=a.oa(b);a.d[c]=g;a.d[k]=l;return a}function b(a,b,c,g){a=a.oa(b);a.d[c]=g;return a}var c=null,c=function(c,e,f,g,k,l){switch(arguments.length){case 4:return b.call(this,c,e,f,g);case 6:return a.call(this,c,e,f,g,k,l)}throw Error("Invalid arity: "+arguments.length);};c.j=b;c.Y=a;return c}();function vd(a,b,c){this.n=a;this.p=b;this.d=c}h=vd.prototype;
h.$=function(a,b,c,d,e,f){var g=1<<(c>>>b&31),k=Wb(this.p&g-1);if(0===(this.p&g)){var l=Wb(this.p);if(2*l<this.d.length){a=this.oa(a);b=a.d;f.X=!0;a:for(c=2*(l-k),f=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[f];l-=1;c-=1;f-=1}b[2*k]=d;b[2*k+1]=e;a.p|=g;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=wd.$(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0!==
(this.p>>>d&1)&&(k[d]=null!=this.d[e]?wd.$(a,b+5,H(this.d[e]),this.d[e],this.d[e+1],f):this.d[e+1],e+=2),d+=1;else break;return new xd(a,l+1,k)}return u?(b=Array(2*(l+4)),Nb(this.d,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Nb(this.d,2*k,b,2*(k+1),2*(l-k)),f.X=!0,a=this.oa(a),a.d=b,a.p|=g,a):null}l=this.d[2*k];g=this.d[2*k+1];return null==l?(l=g.$(a,b+5,c,d,e,f),l===g?this:ud.j(this,a,2*k+1,l)):rd(d,l)?e===g?this:ud.j(this,a,2*k+1,e):u?(f.X=!0,ud.Y(this,a,2*k,null,2*k+1,yd.ma?yd.ma(a,b+5,l,g,c,d,e):yd.call(null,
a,b+5,l,g,c,d,e))):null};h.wa=function(){return zd.b?zd.b(this.d):zd.call(null,this.d)};h.oa=function(a){if(a===this.n)return this;var b=Wb(this.p),c=Array(0>b?4:2*(b+1));Nb(this.d,0,c,0,2*b);return new vd(a,this.p,c)};
h.xa=function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.p&d))return this;var e=Wb(this.p&d-1),f=this.d[2*e],g=this.d[2*e+1];return null==f?(a=g.xa(a+5,b,c),a===g?this:null!=a?new vd(null,this.p,sd.c(this.d,2*e+1,a)):this.p===d?null:u?new vd(null,this.p^d,td(this.d,e)):null):rd(c,f)?new vd(null,this.p^d,td(this.d,e)):u?this:null};
h.Z=function(a,b,c,d,e){var f=1<<(b>>>a&31),g=Wb(this.p&f-1);if(0===(this.p&f)){var k=Wb(this.p);if(16<=k){g=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];g[b>>>a&31]=wd.Z(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.p>>>c&1)&&(g[c]=null!=this.d[d]?wd.Z(a+5,H(this.d[d]),this.d[d],this.d[d+1],e):this.d[d+1],d+=2),c+=1;else break;return new xd(null,k+1,g)}a=Array(2*(k+1));Nb(this.d,0,a,
0,2*g);a[2*g]=c;a[2*g+1]=d;Nb(this.d,2*g,a,2*(g+1),2*(k-g));e.X=!0;return new vd(null,this.p|f,a)}k=this.d[2*g];f=this.d[2*g+1];return null==k?(k=f.Z(a+5,b,c,d,e),k===f?this:new vd(null,this.p,sd.c(this.d,2*g+1,k))):rd(c,k)?d===f?this:new vd(null,this.p,sd.c(this.d,2*g+1,d)):u?(e.X=!0,new vd(null,this.p,sd.w(this.d,2*g,null,2*g+1,yd.Y?yd.Y(a+5,k,f,b,c,d):yd.call(null,a+5,k,f,b,c,d)))):null};
h.ka=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.p&e))return d;var f=Wb(this.p&e-1),e=this.d[2*f],f=this.d[2*f+1];return null==e?f.ka(a+5,b,c,d):rd(c,e)?f:u?d:null};var wd=new vd(null,0,[]);function xd(a,b,c){this.n=a;this.f=b;this.d=c}h=xd.prototype;h.$=function(a,b,c,d,e,f){var g=c>>>b&31,k=this.d[g];if(null==k)return a=ud.j(this,a,g,wd.$(a,b+5,c,d,e,f)),a.f+=1,a;b=k.$(a,b+5,c,d,e,f);return b===k?this:ud.j(this,a,g,b)};h.wa=function(){return Ad.b?Ad.b(this.d):Ad.call(null,this.d)};
h.oa=function(a){return a===this.n?this:new xd(a,this.f,z(this.d))};h.xa=function(a,b,c){var d=b>>>a&31,e=this.d[d];if(null!=e){a=e.xa(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.f)a:{e=this.d;a=2*(this.f-1);b=Array(a);c=0;for(var f=1,g=0;;)if(c<a)c!==d&&null!=e[c]&&(b[f]=e[c],f+=2,g|=1<<c),c+=1;else{d=new vd(null,g,b);break a}d=void 0}else d=new xd(null,this.f-1,sd.c(this.d,d,a));else d=u?new xd(null,this.f,sd.c(this.d,d,a)):null;return d}return this};
h.Z=function(a,b,c,d,e){var f=b>>>a&31,g=this.d[f];if(null==g)return new xd(null,this.f+1,sd.c(this.d,f,wd.Z(a+5,b,c,d,e)));a=g.Z(a+5,b,c,d,e);return a===g?this:new xd(null,this.f,sd.c(this.d,f,a))};h.ka=function(a,b,c,d){var e=this.d[b>>>a&31];return null!=e?e.ka(a+5,b,c,d):d};function Bd(a,b,c){b*=2;for(var d=0;;)if(d<b){if(rd(c,a[d]))return d;d+=2}else return-1}function Cd(a,b,c,d){this.n=a;this.ea=b;this.f=c;this.d=d}h=Cd.prototype;
h.$=function(a,b,c,d,e,f){if(c===this.ea){b=Bd(this.d,this.f,d);if(-1===b){if(this.d.length>2*this.f)return a=ud.Y(this,a,2*this.f,d,2*this.f+1,e),f.X=!0,a.f+=1,a;c=this.d.length;b=Array(c+2);Nb(this.d,0,b,0,c);b[c]=d;b[c+1]=e;f.X=!0;f=this.f+1;a===this.n?(this.d=b,this.f=f,a=this):a=new Cd(this.n,this.ea,f,b);return a}return this.d[b+1]===e?this:ud.j(this,a,b+1,e)}return(new vd(a,1<<(this.ea>>>b&31),[null,this,null,null])).$(a,b,c,d,e,f)};h.wa=function(){return zd.b?zd.b(this.d):zd.call(null,this.d)};
h.oa=function(a){if(a===this.n)return this;var b=Array(2*(this.f+1));Nb(this.d,0,b,0,2*this.f);return new Cd(a,this.ea,this.f,b)};h.xa=function(a,b,c){a=Bd(this.d,this.f,c);return-1===a?this:1===this.f?null:u?new Cd(null,this.ea,this.f-1,td(this.d,Tb((a-a%2)/2))):null};
h.Z=function(a,b,c,d,e){return b===this.ea?(a=Bd(this.d,this.f,c),-1===a?(a=2*this.f,b=Array(a+2),Nb(this.d,0,b,0,a),b[a]=c,b[a+1]=d,e.X=!0,new Cd(null,this.ea,this.f+1,b)):G.a(this.d[a],d)?this:new Cd(null,this.ea,this.f,sd.c(this.d,a+1,d))):(new vd(null,1<<(this.ea>>>a&31),[null,this])).Z(a,b,c,d,e)};h.ka=function(a,b,c,d){a=Bd(this.d,this.f,c);return 0>a?d:rd(c,this.d[a])?this.d[a+1]:u?d:null};
var yd=function(){function a(a,b,c,g,k,l,m){var p=H(c);if(p===k)return new Cd(null,p,2,[c,g,l,m]);var q=new qd;return wd.$(a,b,p,c,g,q).$(a,b,k,l,m,q)}function b(a,b,c,g,k,l){var m=H(b);if(m===g)return new Cd(null,m,2,[b,c,k,l]);var p=new qd;return wd.Z(a,m,b,c,p).Z(a,g,k,l,p)}var c=null,c=function(c,e,f,g,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,f,g,k,l);case 7:return a.call(this,c,e,f,g,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.Y=b;c.ma=a;return c}();
function Dd(a,b,c,d,e){this.i=a;this.aa=b;this.l=c;this.r=d;this.k=e;this.o=0;this.g=32374860}h=Dd.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return this};h.S=function(){return null==this.r?new V(null,2,5,W,[this.aa[this.l],this.aa[this.l+1]],null):J(this.r)};
h.T=function(){return null==this.r?zd.c?zd.c(this.aa,this.l+2,null):zd.call(null,this.aa,this.l+2,null):zd.c?zd.c(this.aa,this.l,M(this.r)):zd.call(null,this.aa,this.l,M(this.r))};h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new Dd(b,this.aa,this.l,this.r,this.k)};h.B=function(){return this.i};h.K=function(){return Gb(L,this.i)};
var zd=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Dd(null,a,b,null,null);var g=a[b+1];if(s(g)&&(g=g.wa(),s(g)))return new Dd(null,a,b+2,g,null);b+=2}else return null;else return new Dd(null,a,b,c,null)}function b(a){return c.c(a,0,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();
function Ed(a,b,c,d,e){this.i=a;this.aa=b;this.l=c;this.r=d;this.k=e;this.o=0;this.g=32374860}h=Ed.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};h.P=function(a,b){return Sb.a(b,this)};h.Q=function(a,b,c){return Sb.c(b,c,this)};h.C=function(){return this};h.S=function(){return J(this.r)};h.T=function(){return Ad.j?Ad.j(null,this.aa,this.l,M(this.r)):Ad.call(null,null,this.aa,this.l,M(this.r))};
h.v=function(a,b){return yb(this,b)};h.D=function(a,b){return new Ed(b,this.aa,this.l,this.r,this.k)};h.B=function(){return this.i};h.K=function(){return Gb(L,this.i)};
var Ad=function(){function a(a,b,c,g){if(null==g)for(g=b.length;;)if(c<g){var k=b[c];if(s(k)&&(k=k.wa(),s(k)))return new Ed(a,b,c+1,k,null);c+=1}else return null;else return new Ed(a,b,c,g,null)}function b(a){return c.j(null,a,0,null)}var c=null,c=function(c,e,f,g){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,f,g)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.j=a;return c}();
function Fd(a,b,c,d,e,f){this.i=a;this.f=b;this.root=c;this.R=d;this.U=e;this.k=f;this.o=8196;this.g=16123663}h=Fd.prototype;h.sa=function(){return new Gd({},this.root,this.f,this.R,this.U)};h.A=function(){var a=this.k;return null!=a?a:this.k=a=Yb(this)};h.N=function(a,b){return Da.c(this,b,null)};h.O=function(a,b,c){return null==b?this.R?this.U:c:null==this.root?c:u?this.root.ka(0,H(b),b,c):null};
h.ra=function(a,b,c){if(null==b)return this.R&&c===this.U?this:new Fd(this.i,this.R?this.f:this.f+1,this.root,!0,c,null);a=new qd;b=(null==this.root?wd:this.root).Z(0,H(b),b,c,a);return b===this.root?this:new Fd(this.i,a.X?this.f+1:this.f,b,this.R,this.U,null)};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
h.apply=function(a,b){return this.call.apply(this,[this].concat(z(b)))};h.b=function(a){return this.N(null,a)};h.a=function(a,b){return this.O(null,a,b)};h.G=function(a,b){return Kb(b)?Ea(this,A.a(b,0),A.a(b,1)):sa.c(za,this,b)};h.toString=function(){return lb(this)};h.C=function(){if(0<this.f){var a=null!=this.root?this.root.wa():null;return this.R?O(new V(null,2,5,W,[null,this.U],null),a):a}return null};h.J=function(){return this.f};h.v=function(a,b){return id(this,b)};
h.D=function(a,b){return new Fd(b,this.f,this.root,this.R,this.U,this.k)};h.B=function(){return this.i};h.K=function(){return Ra(nd,this.i)};h.Ua=function(a,b){if(null==b)return this.R?new Fd(this.i,this.f-1,this.root,!1,null,null):this;if(null==this.root)return this;if(u){var c=this.root.xa(0,H(b),b);return c===this.root?this:new Fd(this.i,this.f-1,c,this.R,this.U,null)}return null};var nd=new Fd(null,0,null,!1,null,0);
function Cb(a,b){for(var c=a.length,d=0,e=bb(nd);;)if(d<c)var f=d+1,e=e.ua(null,a[d],b[d]),d=f;else return db(e)}function Gd(a,b,c,d,e){this.n=a;this.root=b;this.count=c;this.R=d;this.U=e;this.o=56;this.g=258}h=Gd.prototype;h.ua=function(a,b,c){return Hd(this,b,c)};
h.Ba=function(a,b){var c;a:{if(this.n){if(b?b.g&2048||b.lb||(b.g?0:t(Ha,b)):t(Ha,b)){c=Hd(this,Zb.b?Zb.b(b):Zb.call(null,b),$b.b?$b.b(b):$b.call(null,b));break a}c=I(b);for(var d=this;;){var e=J(c);if(s(e))c=M(c),d=Hd(d,Zb.b?Zb.b(e):Zb.call(null,e),$b.b?$b.b(e):$b.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
h.Ca=function(){var a;if(this.n)this.n=null,a=new Fd(null,this.count,this.root,this.R,this.U,null);else throw Error("persistent! called twice");return a};h.N=function(a,b){return null==b?this.R?this.U:null:null==this.root?null:this.root.ka(0,H(b),b)};h.O=function(a,b,c){return null==b?this.R?this.U:c:null==this.root?c:this.root.ka(0,H(b),b,c)};h.J=function(){if(this.n)return this.count;throw Error("count after persistent!");};
function Hd(a,b,c){if(a.n){if(null==b)a.U!==c&&(a.U=c),a.R||(a.count+=1,a.R=!0);else{var d=new qd;b=(null==a.root?wd:a.root).$(a.n,0,H(b),b,c,d);b!==a.root&&(a.root=b);d.X&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var Id=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=I(a);for(var b=bb(nd);;)if(a){var e=M(M(a)),b=xc.c(b,J(a),J(M(a)));a=e}else return db(b)}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();function Zb(a){return Ia(a)}function $b(a){return Ja(a)}
var Jd=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return s(Ac(a))?sa.a(function(a,b){return Ab.a(s(a)?a:od,b)},a):null}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();function fc(a){if(a&&(a.o&4096||a.nb))return a.name;if("string"===typeof a)return a;throw Error([x("Doesn't support name: "),x(a)].join(""));}
function Kd(a,b,c,d,e){this.i=a;this.start=b;this.end=c;this.step=d;this.k=e;this.g=32375006;this.o=8192}h=Kd.prototype;h.A=function(){var a=this.k;return null!=a?a:this.k=a=xb(this)};h.ba=function(){return 0<this.step?this.start+this.step<this.end?new Kd(this.i,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new Kd(this.i,this.start+this.step,this.end,this.step,null):null};h.G=function(a,b){return O(b,this)};h.toString=function(){return lb(this)};
h.P=function(a,b){return tb.a(this,b)};h.Q=function(a,b,c){return tb.c(this,b,c)};h.C=function(){return 0<this.step?this.start<this.end?this:null:this.start>this.end?this:null};h.J=function(){return pa(Xa(this))?0:Math.ceil((this.end-this.start)/this.step)};h.S=function(){return null==Xa(this)?null:this.start};h.T=function(){return null!=Xa(this)?new Kd(this.i,this.start+this.step,this.end,this.step,null):L};h.v=function(a,b){return yb(this,b)};
h.D=function(a,b){return new Kd(b,this.start,this.end,this.step,this.k)};h.B=function(){return this.i};h.H=function(a,b){if(b<wa(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};h.V=function(a,b,c){return b<wa(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};h.K=function(){return Gb(L,this.i)};
var Ld=function(){function a(a,b,c){return new Kd(null,a,b,c,null)}function b(a,b){return e.c(a,b,1)}function c(a){return e.c(0,a,1)}function d(){return e.c(0,Number.MAX_VALUE,1)}var e=null,e=function(e,g,k){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,e);case 2:return b.call(this,e,g);case 3:return a.call(this,e,g,k)}throw Error("Invalid arity: "+arguments.length);};e.q=d;e.b=c;e.a=b;e.c=a;return e}();
function Md(a,b,c,d,e,f,g){var k=ha;try{ha=null==ha?null:ha-1;if(null!=ha&&0>ha)return E(a,"#");E(a,c);I(g)&&(b.c?b.c(J(g),a,f):b.call(null,J(g),a,f));for(var l=M(g),m=oa.b(f);l&&(null==m||0!==m);){E(a,d);b.c?b.c(J(l),a,f):b.call(null,J(l),a,f);var p=M(l);c=m-1;l=p;m=c}s(oa.b(f))&&(E(a,d),b.c?b.c("...",a,f):b.call(null,"...",a,f));return E(a,e)}finally{ha=k}}
var Nd=function(){function a(a,d){var e=null;1<arguments.length&&(e=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=I(b),f=null,g=0,k=0;;)if(k<g){var l=f.H(null,k);E(a,l);k+=1}else if(e=I(e))f=e,Lb(f)?(e=hb(f),g=ib(f),f=e,l=P(e),e=g,g=l):(l=J(f),E(a,l),e=M(f),f=null,g=0),k=0;else return null}a.m=1;a.h=function(a){var d=J(a);a=K(a);return b(d,a)};a.e=b;return a}(),Od={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function Pd(a){return[x('"'),x(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return Od[a]})),x('"')].join("")}
var Y=function Qd(b,c,d){if(null==b)return E(c,"nil");if(void 0===b)return E(c,"#\x3cundefined\x3e");if(u){s(function(){var c=R.a(d,la);return s(c)?(c=b?b.g&131072||b.mb?!0:b.g?!1:t(Oa,b):t(Oa,b))?Hb(b):c:c}())&&(E(c,"^"),Qd(Hb(b),c,d),E(c," "));if(null==b)return E(c,"nil");if(b.Xa)return b.gb(b,c,d);if(b&&(b.g&2147483648||b.L))return b.u(null,c,d);if(qa(b)===Boolean||"number"===typeof b)return E(c,""+x(b));if(null!=b&&b.constructor===Object)return E(c,"#js "),Rd.j?Rd.j(Cc.a(function(c){return new V(null,
2,5,W,[gc.b(c),b[c]],null)},Mb(b)),Qd,c,d):Rd.call(null,Cc.a(function(c){return new V(null,2,5,W,[gc.b(c),b[c]],null)},Mb(b)),Qd,c,d);if(b instanceof Array)return Md(c,Qd,"#js ["," ","]",d,b);if("string"==typeof b)return s(ka.b(d))?E(c,Pd(b)):E(c,b);if(Eb(b))return Nd.e(c,N(["#\x3c",""+x(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+x(b);;)if(P(d)<c)d=[x("0"),x(d)].join("");else return d};return Nd.e(c,N(['#inst "',""+x(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),
2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?Nd.e(c,N(['#"',b.source,'"'],0)):(b?b.g&2147483648||b.L||(b.g?0:t(Za,b)):t(Za,b))?$a(b,c,d):u?Nd.e(c,N(["#\x3c",""+x(b),"\x3e"],0)):null}return null};
function Sd(a,b){var c;if(null==a||pa(I(a)))c="";else{c=x;var d=new ea;a:{var e=new kb(d);Y(J(a),e,b);for(var f=I(M(a)),g=null,k=0,l=0;;)if(l<k){var m=g.H(null,l);E(e," ");Y(m,e,b);l+=1}else if(f=I(f))g=f,Lb(g)?(f=hb(g),k=ib(g),g=f,m=P(f),f=k,k=m):(m=J(g),E(e," "),Y(m,e,b),f=M(g),g=null,k=0),l=0;else break a}c=""+c(d)}return c}
var Td=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return Sd(a,ia())}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}(),Ud=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=S.c(ia(),ka,!1);a=Sd(a,b);ga.b?ga.b(a):ga.call(null,a);return null}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();
function Rd(a,b,c,d){return Md(c,function(a,c,d){b.c?b.c(Ia(a),c,d):b.call(null,Ia(a),c,d);E(c," ");return b.c?b.c(Ja(a),c,d):b.call(null,Ja(a),c,d)},"{",", ","}",d,I(a))}rb.prototype.L=!0;rb.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};cd.prototype.L=!0;cd.prototype.u=function(a,b,c){return Md(b,Y,"["," ","]",c,this)};nc.prototype.L=!0;nc.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};r.prototype.L=!0;r.prototype.u=function(a,b,c){return Rd(this,Y,b,c)};
hc.prototype.L=!0;hc.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};Dd.prototype.L=!0;Dd.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};$c.prototype.L=!0;$c.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};Fd.prototype.L=!0;Fd.prototype.u=function(a,b,c){return Rd(this,Y,b,c)};V.prototype.L=!0;V.prototype.u=function(a,b,c){return Md(b,Y,"["," ","]",c,this)};ac.prototype.L=!0;ac.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};
kd.prototype.L=!0;kd.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};bc.prototype.L=!0;bc.prototype.u=function(a,b){return E(b,"()")};ec.prototype.L=!0;ec.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};Kd.prototype.L=!0;Kd.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};Ed.prototype.L=!0;Ed.prototype.u=function(a,b,c){return Md(b,Y,"("," ",")",c,this)};V.prototype.za=!0;V.prototype.Aa=function(a,b){return Rb.a(this,b)};cd.prototype.za=!0;
cd.prototype.Aa=function(a,b){return Rb.a(this,b)};U.prototype.za=!0;U.prototype.Aa=function(a,b){return mb(this,b)};pb.prototype.za=!0;pb.prototype.Aa=function(a,b){return mb(this,b)};function Vd(a,b){if(a?a.pb:a)return a.pb(a,b);var c;c=Vd[n(null==a?null:a)];if(!c&&(c=Vd._,!c))throw w("IReset.-reset!",a);return c.call(null,a,b)}
var Wd=function(){function a(a,b,c,d,e){if(a?a.tb:a)return a.tb(a,b,c,d,e);var p;p=Wd[n(null==a?null:a)];if(!p&&(p=Wd._,!p))throw w("ISwap.-swap!",a);return p.call(null,a,b,c,d,e)}function b(a,b,c,d){if(a?a.sb:a)return a.sb(a,b,c,d);var e;e=Wd[n(null==a?null:a)];if(!e&&(e=Wd._,!e))throw w("ISwap.-swap!",a);return e.call(null,a,b,c,d)}function c(a,b,c){if(a?a.rb:a)return a.rb(a,b,c);var d;d=Wd[n(null==a?null:a)];if(!d&&(d=Wd._,!d))throw w("ISwap.-swap!",a);return d.call(null,a,b,c)}function d(a,b){if(a?
a.qb:a)return a.qb(a,b);var c;c=Wd[n(null==a?null:a)];if(!c&&(c=Wd._,!c))throw w("ISwap.-swap!",a);return c.call(null,a,b)}var e=null,e=function(e,g,k,l,m){switch(arguments.length){case 2:return d.call(this,e,g);case 3:return c.call(this,e,g,k);case 4:return b.call(this,e,g,k,l);case 5:return a.call(this,e,g,k,l,m)}throw Error("Invalid arity: "+arguments.length);};e.a=d;e.c=c;e.j=b;e.w=a;return e}();function Xd(a,b,c,d){this.state=a;this.i=b;this.zb=c;this.hb=d;this.g=2153938944;this.o=16386}h=Xd.prototype;
h.A=function(){return this[aa]||(this[aa]=++ca)};h.eb=function(a,b,c){a=I(this.hb);for(var d=null,e=0,f=0;;)if(f<e){var g=d.H(null,f),k=Q.c(g,0,null),g=Q.c(g,1,null);g.j?g.j(k,this,b,c):g.call(null,k,this,b,c);f+=1}else if(a=I(a))Lb(a)?(d=hb(a),a=ib(a),k=d,e=P(d),d=k):(d=J(a),k=Q.c(d,0,null),g=Q.c(d,1,null),g.j?g.j(k,this,b,c):g.call(null,k,this,b,c),a=M(a),d=null,e=0),f=0;else return null};h.u=function(a,b,c){E(b,"#\x3cAtom: ");Y(this.state,b,c);return E(b,"\x3e")};h.B=function(){return this.i};
h.kb=function(){return this.state};h.v=function(a,b){return this===b};
var Zd=function(){function a(a){return new Xd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=Pb(c)?T.a(Id,c):c,e=R.a(d,Yd),d=R.a(d,la);return new Xd(a,d,e,null)}a.m=1;a.h=function(a){var c=J(a);a=K(a);return b(c,a)};a.e=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.e(b,N(arguments,1))}throw Error("Invalid arity: "+
arguments.length);};b.m=1;b.h=c.h;b.b=a;b.e=c.e;return b}();function $d(a,b){if(a instanceof Xd){var c=a.zb;if(null!=c&&!s(c.b?c.b(b):c.call(null,b)))throw Error([x("Assert failed: "),x("Validator rejected reference state"),x("\n"),x(Td.e(N([dc(new pb(null,"validate","validate",1233162959,null),new pb(null,"new-value","new-value",972165309,null))],0)))].join(""));c=a.state;a.state=b;null!=a.hb&&ab(a,c,b);return b}return Vd(a,b)}
var ae=function(){function a(a,b,c,d){return a instanceof Xd?$d(a,b.c?b.c(a.state,c,d):b.call(null,a.state,c,d)):Wd.j(a,b,c,d)}function b(a,b,c){return a instanceof Xd?$d(a,b.a?b.a(a.state,c):b.call(null,a.state,c)):Wd.c(a,b,c)}function c(a,b){return a instanceof Xd?$d(a,b.b?b.b(a.state):b.call(null,a.state)):Wd.a(a,b)}var d=null,e=function(){function a(c,d,e,f,q){var v=null;4<arguments.length&&(v=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,v)}function b(a,c,d,e,f){return a instanceof
Xd?$d(a,T.w(c,a.state,d,e,f)):Wd.w(a,c,d,e,f)}a.m=4;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=K(a);return b(c,d,e,f,a)};a.e=b;return a}(),d=function(d,g,k,l,m){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,d,g,k);case 4:return a.call(this,d,g,k,l);default:return e.e(d,g,k,l,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.h=e.h;d.a=c;d.c=b;d.j=a;d.e=e.e;return d}(),Ub=function(){function a(a){return(Math.random.q?
Math.random.q():Math.random.call(null))*a}function b(){return c.b(1)}var c=null,c=function(c){switch(arguments.length){case 0:return b.call(this);case 1:return a.call(this,c)}throw Error("Invalid arity: "+arguments.length);};c.q=b;c.b=a;return c}(),Vb=function(a){return Math.floor.b?Math.floor.b((Math.random.q?Math.random.q():Math.random.call(null))*a):Math.floor.call(null,(Math.random.q?Math.random.q():Math.random.call(null))*a)};var be=new U(null,"game","game"),na=new U(null,"dup","dup"),ce=new U(null,"ball","ball"),de=new U(null,"direction","direction"),ee=new U(null,"timestamp","timestamp"),ob=new U(null,"default","default"),fe=new U(null,"history","history"),ge=new U(null,"position","position"),he=new U(null,"width","width"),ie=new U(null,"pattern","pattern"),ne=new U(null,"speed","speed"),oe=new U(null,"velocity","velocity"),pe=new U(null,"mutes","mutes"),Z=new U(null,"y","y"),qe=new U(null,"current","current"),re=new U(null,
"menu","menu"),$=new U(null,"x","x"),se=new U(null,"wall-hits","wall-hits"),ja=new U(null,"flush-on-newline","flush-on-newline"),te=new U(null,"length","length"),ue=new U(null,"intensity","intensity"),ve=new U("cljs.core.async","nothing","cljs.core.async/nothing"),we=new U(null,"acceleration","acceleration"),xe=new U(null,"pos","pos"),ye=new U(null,"phone","phone"),ze=new U(null,"walls","walls"),oa=new U(null,"print-length","print-length"),Ae=new U(null,"reads","reads"),u=new U(null,"else","else"),
ka=new U(null,"readably","readably"),Yd=new U(null,"validator","validator"),la=new U(null,"meta","meta"),Be=new U(null,"mode","mode"),Ce=new U(null,"coord","coord"),De=new U(null,"height","height"),Ee=new U(null,"steps","steps");function Fe(){var a=innerWidth,b=innerHeight,c=new V(null,4,5,W,[new r(null,4,[Ce,$,xe,0,te,b,de,1],null),new r(null,4,[Ce,Z,xe,0,te,a,de,1],null),new r(null,4,[Ce,$,xe,a,te,b,de,-1],null),new r(null,4,[Ce,Z,xe,b,te,a,de,-1],null)],null);return new r(null,3,[ze,c,ie,new r(null,2,[qe,0,Ee,function(){return function(a,b,c){return function k(l){return new hc(null,function(a,b,c){return function(){for(;;){var a=I(l);if(a){if(Lb(a)){var b=hb(a),d=P(b),e=lc(d);a:{for(var f=0;;)if(f<d){A.a(b,f);var m=R.a(c,
Vb(4));e.add(m);f+=1}else{b=!0;break a}b=void 0}return b?oc(e.F(),k(ib(a))):oc(e.F(),null)}J(a);return O(R.a(c,Vb(4)),k(K(a)))}return null}}}(a,b,c),null,null)}}(a,b,c)(Ld.b(10))}()],null),ce,new r(null,5,[he,40,De,40,ge,new r(null,2,[$,a/2,Z,b/2],null),we,new r(null,2,[$,0,Z,0],null),oe,new r(null,2,[$,0,Z,0],null)],null)],null)};var Ge;"undefined"!==typeof MessageChannel&&new MessageChannel;function He(a,b,c){this.key=a;this.X=b;this.forward=c;this.o=0;this.g=2155872256}He.prototype.u=function(a,b,c){return Md(b,Y,"["," ","]",c,this)};He.prototype.C=function(){return za(za(L,this.X),this.key)};
(function(){function a(a,b,c){c=Array(c+1);for(var g=0;;)if(g<c.length)c[g]=null,g+=1;else break;return new He(a,b,c)}function b(a){return c.c(null,null,a)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c})().b(0);(function Ie(b){"undefined"===typeof Ge&&(Ge=function(b,d,e){this.ub=b;this.vb=d;this.xb=e;this.o=0;this.g=393216},Ge.Xa=!0,Ge.Wa="cljs.core.async/t25134",Ge.gb=function(b,d){return E(d,"cljs.core.async/t25134")},Ge.prototype.B=function(){return this.xb},Ge.prototype.D=function(b,d){return new Ge(this.ub,this.vb,d)});return new Ge(b,Ie,null)})(function(){return null});var Je=function(){function a(a,d){var e=null;1<arguments.length&&(e=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=document.createElement(a),f=I(J(b)),g=null,k=0,l=0;;)if(l<k){var m=g.H(null,l),p=Q.c(m,0,null),m=Q.c(m,1,null);e.setAttribute(fc(p),m);l+=1}else if(f=I(f))Lb(f)?(k=hb(f),f=ib(f),g=k,k=P(k)):(k=J(f),g=Q.c(k,0,null),k=Q.c(k,1,null),e.setAttribute(fc(g),k),f=M(f),g=null,k=0),l=0;else break;return e}a.m=1;a.h=function(a){var d=J(a);a=K(a);
return b(d,a)};a.e=b;return a}();var Ke=Math.PI;function Le(a){var b=new Image;b.src="/assets/images/ring.clj.svg";b.width=2*a;b.height=2*a;return b}function Me(a,b,c,d,e){a.save();a.translate(b,c);a.rotate(d);a.drawImage(Le((e.b?e.b(he):e.call(null,he))/2),-((e.b?e.b(he):e.call(null,he))/2),-((e.b?e.b(De):e.call(null,De))/2),he.b(e),De.b(e));return a.restore()};function Ne(a){a.getContext("2d").clearRect(0,0,a.width,a.height)}
function Oe(a,b,c,d,e,f,g){var k;k=new V(null,2,5,W,[b,g],null);k=G.a(new V(null,2,5,W,[Z,-1],null),k)?"rgba(123,0,123,":G.a(new V(null,2,5,W,[$,-1],null),k)?"rgba(0,123,176,":G.a(new V(null,2,5,W,[$,1],null),k)?"rgba(0,255,0,":u?"rgba(255,0,0,":null;f*=g;e*=g;a=G.a(b,$)?a.createLinearGradient(c,d,c+e,d/2):a.createLinearGradient(c,d,c/2,d+f);a.addColorStop(0,[x(k),x("0.3)")].join(""));a.addColorStop(0.1,[x(k),x("0.3)")].join(""));a.addColorStop(0.8,[x(k),x("0)")].join(""));return a}
function Pe(a,b){var c=Pb(b)?T.a(Id,b):b,d=R.a(c,ue),e=R.a(c,de),f=R.a(c,te),g=R.a(c,xe),k=R.a(c,Ce),d=G.a(k,$)?new V(null,2,5,W,[f,25*d],null):new V(null,2,5,W,[25*d,f],null),c=Q.c(d,0,null),d=Q.c(d,1,null),l=function(){if(G.a(Z,k))return new V(null,2,5,W,[0,g],null);if(G.a($,k))return new V(null,2,5,W,[g,0],null);if(u)throw Error([x("No matching clause: "),x(k)].join(""));return null}(),f=Q.c(l,0,null),l=Q.c(l,1,null);a.fillStyle=Oe(a,k,f,l,d,c,e);a.fillRect(G.a(k,$)&&G.a(e,-1)?f-d:f,G.a(k,Z)&&
G.a(e,-1)?l-c:l,d,c)}
function Qe(a,b){return requestAnimationFrame(function(){var c;c=b.b?b.b(Be):b.call(null,Be);if(G.a(be,c)){c=a.getContext("2d");var d=Jd.e(N([new r(null,1,[ue,2],null),Q.a(Ee.b(ie.b(b)),qe.b(ie.b(b)))],0));Ne(a);b:for(var e=I(b.b?b.b(se):b.call(null,se)),f=null,g=0,k=0;;)if(k<g){var l=f.H(null,k),m=Q.c(l,0,null),l=Q.c(l,1,null),p=b.b?b.b(ee):b.call(null,ee),q=m.b?m.b(ne):m.call(null,ne);-900<l-(b.b?b.b(ee):b.call(null,ee))&&Pe(c,Jd.e(N([m,new r(null,1,[ue,100*q/(p-l)],null)],0)));k+=1}else if(m=I(e))e=
m,Lb(e)?(l=hb(e),e=ib(e),m=l,l=P(l),f=m,g=l):(l=J(e),m=Q.c(l,0,null),l=Q.c(l,1,null),f=b.b?b.b(ee):b.call(null,ee),g=m.b?m.b(ne):m.call(null,ne),-900<l-(b.b?b.b(ee):b.call(null,ee))&&Pe(c,Jd.e(N([m,new r(null,1,[ue,100*g/(f-l)],null)],0))),e=M(e),f=null,g=0),k=0;else break b;Pe(c,d);l=b.b?b.b(ce):b.call(null,ce);d=new r(null,2,[he,l.b?l.b(he):l.call(null,he),De,l.b?l.b(De):l.call(null,De)],null);m=b.b?b.b(ee):b.call(null,ee);e=$.b(ge.b(l));l=Z.b(ge.b(l));Me(c,e,l,((m+1E3)%9E4+9E4)%9E4/9E4*(360/Ke),
new r(null,2,[he,32,De,32],null));c=Me(c,e,l,((-m+90)%9E4+9E4)%9E4/9E4*(360/Ke),d)}else if(G.a(re,c))c=a.getContext("2d"),d=Pb(b)?T.a(Id,b):b,d=R.a(d,ye),d=new r(null,2,[$,G.a(d.gamma,0)?0:Math.abs(d.gamma)/d.gamma*(d.gamma*d.gamma/1290),Z,G.a(d.beta,0)?0:Math.abs(d.beta)/d.beta*(d.beta*d.beta/1290)],null),Ne(a),c.font="bold 12px sans-serif",c=Graphics.Mb(c,"New Game",43+$.b(d),100+Z.b(d));else{if(u)throw Error([x("No matching clause: "),x(b.b?b.b(Be):b.call(null,Be))].join(""));c=null}return c})}
;function Re(a){var b=new V(null,2,5,W,[0,1],null),c=Q.c(b,0,null),b=Q.c(b,1,null);return Math.min(Math.max(a,c),b)}function Se(a){return function(a){return a*a}.call(null,Re(a/1.2))}
function Te(a){return[x("sounds/"),x(function(){var b=new V(null,2,5,W,[Ce.b(a),de.b(a)],null);return G.a(new V(null,2,5,W,[Z,-1],null),b)?"boink.wav":G.a(new V(null,2,5,W,[$,-1],null),b)?"boink.wav":G.a(new V(null,2,5,W,[Z,1],null),b)?"boink.wav":G.a(new V(null,2,5,W,[$,1],null),b)?"boink.wav":u?"squish.mp3":null}())].join("")}function Ue(a){var b=be.b(ce.b(a));s(b)&&(a=Te(b),b=Se(ne.b(b)),a=Je.e("audio",N([new r(null,1,[Be,a],null)],0)),a.volume=b,a.play())};ga=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return console.log.apply(console,ta.b?ta.b(a):ta.call(null,a))}a.m=0;a.h=function(a){a=I(a);return b(a)};a.e=b;return a}();if("undefined"===typeof Ve)var Ve=Zd.b({gamma:0,beta:0,alpha:0});if("undefined"===typeof We)var We=Zd.b(Xc);
function Xe(){s(DeviceOrientationEvent)?window.addEventListener("deviceorientation",function(a){return $d(Ve,a)}):navigator.Bb.Nb(function(a){return $d(Ve,a)},function(a){return console.log(a)})}function Ye(){document.addEventListener("click",function(a){return ae.c(We,Ab,a)})}
function Ze(a,b,c){var d=Q.c(b,0,null),e=Q.c(b,1,null);return Gc.c(a,new V(null,1,5,W,[ge],null),function(a,b,d){return function(a){return Cb.a?Cb.a([$,Z],[$.b(a)+c*b,Z.b(a)+c*d]):Cb.call(null,[$,Z],[$.b(a)+c*b,Z.b(a)+c*d])}}(b,d,e))}
function $e(a,b){var c=$.b(we.b(a)),d=Z.b(we.b(a)),e=$.b(oe.b(a)),f=Z.b(oe.b(a)),g=e+b*c,k=f+b*d;return Ze(Gc.c(a,new V(null,1,5,W,[oe],null),function(a,b,c,d,e,f){return function(){return Cb.a?Cb.a([$,Z],[e,f]):Cb.call(null,[$,Z],[e,f])}}(c,d,e,f,g,k)),new V(null,2,5,W,[(e+g)/2,(f+k)/2],null),b)}function af(a,b){var c=Q.c(b,0,null),d=Q.c(b,1,null);return c<a&&a<d||c>a&&a>d}
function bf(a,b,c){return sa.c(function(a,b){var c=Q.c(b,0,null),g=Pb(c)?T.a(Id,c):c,k=R.a(g,xe),l=R.a(g,Ce),m=Q.c(b,1,null);return s(m)?Jd.e(N([Gc.c(Gc.c(a,new V(null,2,5,W,[ge,l],null),function(a,b,c,d,e,f,g){return function(a){return a+g}}(b,c,g,g,k,l,m)),new V(null,2,5,W,[oe,l],null),function(){return function(a){return-(0.62*a)}}(b,c,g,g,k,l,m)),new r(null,1,[be,S.c(g,ne,Math.abs(l.b?l.b(oe.b(a)):l.call(null,oe.b(a))))],null)],0)):a},a,T.a(uc,function(){return function e(c){return new hc(null,
function(){for(;;){var g=I(c);if(g){var k=g;if(Lb(k)){var l=hb(k),m=P(l),p=lc(m);return function(){for(var c=0;;)if(c<m){var e=A.a(l,c),f=Pb(e)?T.a(Id,e):e,q=f,v=R.a(f,xe),y=R.a(f,Ce);pc(p,function(){var B=Dc.a(b,new V(null,2,5,W,[ge,y],null)),F=Dc.a(a,new V(null,2,5,W,[ge,y],null)),je=b.b?b.b(G.a(y,$)?he:De):b.call(null,G.a(y,$)?he:De),me=function(a,b,c,e,f,g,k,l,m,p,q,v,y,B){return function le(F){return new hc(null,function(a,b,c,e,f,g,k,l){return function(){for(;;){var a=I(F);if(a){if(Lb(a)){var b=
hb(a),c=P(b),e=lc(c);a:{for(var f=0;;)if(f<c){var g=A.a(b,f),m=Q.c(g,0,null),g=Q.c(g,1,null),m=new V(null,2,5,W,[k,af(l,new V(null,2,5,W,[m,g],null))?2*(l-g):null],null);e.add(m);f+=1}else{b=!0;break a}b=void 0}return b?oc(e.F(),le(ib(a))):oc(e.F(),null)}b=J(a);e=Q.c(b,0,null);b=Q.c(b,1,null);return O(new V(null,2,5,W,[k,af(l,new V(null,2,5,W,[e,b],null))?2*(l-b):null],null),le(K(a)))}return null}}}(a,b,c,e,f,g,k,l,m,p,q,v,y,B),null,null)}}(c,B,F,je,e,f,q,v,y,l,m,p,k,g);return me(T.c(Cc,Zc,Cc.a(function(a,
b,c,e,f){return function(a){return new V(null,2,5,W,[a-f/2,a+f/2],null)}}(c,me,B,F,je,e,f,q,v,y,l,m,p,k,g),new V(null,2,5,W,[B,F],null))))}());c+=1}else return!0}()?oc(p.F(),e(ib(k))):oc(p.F(),null)}var q=J(k),v=Pb(q)?T.a(Id,q):q,F=v,y=R.a(v,xe),B=R.a(v,Ce);return O(function(){var c=Dc.a(b,new V(null,2,5,W,[ge,B],null)),e=Dc.a(a,new V(null,2,5,W,[ge,B],null)),f=b.b?b.b(G.a(B,$)?he:De):b.call(null,G.a(B,$)?he:De),l=function(a,b,c,e,f,g,k,l,m,p){return function ke(q){return new hc(null,function(a,b,
c,e,f,g,k){return function(){for(;;){var a=I(q);if(a){if(Lb(a)){var b=hb(a),c=P(b),e=lc(c);a:{for(var f=0;;)if(f<c){var l=A.a(b,f),m=Q.c(l,0,null),l=Q.c(l,1,null),m=new V(null,2,5,W,[g,af(k,new V(null,2,5,W,[m,l],null))?2*(k-l):null],null);e.add(m);f+=1}else{b=!0;break a}b=void 0}return b?oc(e.F(),ke(ib(a))):oc(e.F(),null)}b=J(a);e=Q.c(b,0,null);b=Q.c(b,1,null);return O(new V(null,2,5,W,[g,af(k,new V(null,2,5,W,[e,b],null))?2*(k-b):null],null),ke(K(a)))}return null}}}(a,b,c,e,f,g,k,l,m,p),null,null)}}(c,
e,f,q,v,F,y,B,k,g);return l(T.c(Cc,Zc,Cc.a(function(a,b,c,e){return function(a){return new V(null,2,5,W,[a-e/2,a+e/2],null)}}(l,c,e,f,q,v,F,y,B,k,g),new V(null,2,5,W,[c,e],null))))}(),e(K(k)))}return null}},null,null)}(c)}()))}function cf(a,b){return Gc.c(a,new V(null,1,5,W,[pe],null),function(c){return O(new V(null,2,5,W,[a,b],null),c)})}function df(a){return Db.a(a,be)}
function ef(a,b){var c;c=1.2E-5*ye.b(a).gamma;var d;d=1.2E-5*ye.b(a).beta;return S.c(a,ce,bf($e(Fc(df(cf(a.b?a.b(ce):a.call(null,ce),a.b?a.b(ee):a.call(null,ee))),new V(null,1,5,W,[we],null),Cb.a?Cb.a([$,Z],[c,d]):Cb.call(null,[$,Z],[c,d])),b),a.b?a.b(ce):a.call(null,ce),a.b?a.b(ze):a.call(null,ze)))}
function ff(a){var b=Dc.a(a,new V(null,2,5,W,[ce,be],null));return s(b)?Gc.c(a,new V(null,1,5,W,[se],null),function(b){return function(d){return Ab.a(d,new V(null,2,5,W,[b,a.b?a.b(ee):a.call(null,ee)],null))}}(b)):a}
function gf(a){var b;a:{for(b=a.b?a.b(se):a.call(null,se);;){var c=M(b);if(null!=c)b=c;else{b=J(b);break a}}b=void 0}return s(b)?(c=Q.c(b,0,null),Q.c(b,1,null),G.a(Q.a(Dc.a(a,new V(null,2,5,W,[ie,Ee],null)),Dc.a(a,new V(null,2,5,W,[ie,qe],null))),Db.a(c,ne))?Gc.c(a,new V(null,2,5,W,[ie,qe],null),sb):a):a}function hf(a){var b=Date.now(),c=b-ee.b(a);return S.c(gf(ff(ef(a,c))),ee,b)}function jf(a){var b=Ma(We);return null==b||pa(I(b))?a:S.c(S.c(Fe.q?Fe.q():Fe.call(null),Ae,ve),se,Xc)}
function kf(a){return function(){var b=a.b?a.b(Ae):a.call(null,Ae);if(G.a(ve,b))return hf;if(G.a(fe,b))return jf;if(u)throw Error([x("No matching clause: "),x(a.b?a.b(Ae):a.call(null,Ae))].join(""));return null}().call(null,S.c(a,ye,Ma(Ve)))}var lf=new r(null,3,[Ae,fe,he,innerWidth,De,innerHeight],null),nf=function mf(b,c){requestAnimationFrame(function(){return mf(kf(b),c)});Ue(b);return Qe(c,b)};
function of(){Ud.e(N(["Starting..."],0));Xe();Ye();var a=Je("canvas");a.width=innerWidth;a.height=innerHeight;document.body.appendChild(a);return nf(Jd.e(N([lf,new r(null,1,[ee,Date.now()],null)],0)),a)}var pf=["ball_roller","core","start"],qf=this;pf[0]in qf||!qf.execScript||qf.execScript("var "+pf[0]);for(var rf;pf.length&&(rf=pf.shift());)pf.length||void 0===of?qf=qf[rf]?qf[rf]:qf[rf]={}:qf[rf]=of;
})();
