;(function(){
var h;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function da(a,b){null!=a&&this.append.apply(this,arguments)}da.prototype.qa="";da.prototype.append=function(a,b,c){this.qa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.qa+=arguments[d];return this};da.prototype.toString=function(){return this.qa};var ea;function fa(){throw Error("No *print-fn* fn set for evaluation environment");}var ga=null;function ia(){return new r(null,5,[ja,!0,ka,!0,la,!1,ma,!1,na,null],null)}function s(a){return null!=a&&!1!==a}function u(a,b){return a[n(null==b?null:b)]?!0:a._?!0:w?!1:null}function oa(a){return null==a?null:a.constructor}function x(a,b){var c=oa(b),c=s(s(c)?c.Xa:c)?c.Wa:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}
function pa(a){var b=a.Wa;return s(b)?b:""+z(a)}function A(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
var ra=function(){function a(a,b){return qa.b?qa.b(function(a,b){a.push(b);return a},[],b):qa.call(null,function(a,b){a.push(b);return a},[],b)}function b(a){return c.a(null,a)}var c=null,c=function(d,c){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,0,c)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}(),sa={},ta={};
function ua(a){if(a?a.J:a)return a.J(a);var b;b=ua[n(null==a?null:a)];if(!b&&(b=ua._,!b))throw x("ICounted.-count",a);return b.call(null,a)}function wa(a){if(a?a.K:a)return a.K(a);var b;b=wa[n(null==a?null:a)];if(!b&&(b=wa._,!b))throw x("IEmptyableCollection.-empty",a);return b.call(null,a)}function xa(a,b){if(a?a.F:a)return a.F(a,b);var c;c=xa[n(null==a?null:a)];if(!c&&(c=xa._,!c))throw x("ICollection.-conj",a);return c.call(null,a,b)}
var ya={},B=function(){function a(a,b,c){if(a?a.Y:a)return a.Y(a,b,c);var g;g=B[n(null==a?null:a)];if(!g&&(g=B._,!g))throw x("IIndexed.-nth",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.G:a)return a.G(a,b);var c;c=B[n(null==a?null:a)];if(!c&&(c=B._,!c))throw x("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,f){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}(),
za={};function D(a){if(a?a.R:a)return a.R(a);var b;b=D[n(null==a?null:a)];if(!b&&(b=D._,!b))throw x("ISeq.-first",a);return b.call(null,a)}function E(a){if(a?a.T:a)return a.T(a);var b;b=E[n(null==a?null:a)];if(!b&&(b=E._,!b))throw x("ISeq.-rest",a);return b.call(null,a)}
var Aa={},Ba=function(){function a(a,b,c){if(a?a.M:a)return a.M(a,b,c);var g;g=Ba[n(null==a?null:a)];if(!g&&(g=Ba._,!g))throw x("ILookup.-lookup",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.L:a)return a.L(a,b);var c;c=Ba[n(null==a?null:a)];if(!c&&(c=Ba._,!c))throw x("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}();
function Ca(a,b,c){if(a?a.ra:a)return a.ra(a,b,c);var d;d=Ca[n(null==a?null:a)];if(!d&&(d=Ca._,!d))throw x("IAssociative.-assoc",a);return d.call(null,a,b,c)}var Da={};function Ea(a,b){if(a?a.Ua:a)return a.Ua(a,b);var c;c=Ea[n(null==a?null:a)];if(!c&&(c=Ea._,!c))throw x("IMap.-dissoc",a);return c.call(null,a,b)}var Fa={};function Ga(a){if(a?a.$a:a)return a.$a();var b;b=Ga[n(null==a?null:a)];if(!b&&(b=Ga._,!b))throw x("IMapEntry.-key",a);return b.call(null,a)}
function Ha(a){if(a?a.ab:a)return a.ab();var b;b=Ha[n(null==a?null:a)];if(!b&&(b=Ha._,!b))throw x("IMapEntry.-val",a);return b.call(null,a)}var Ia={};function Ka(a,b,c){if(a?a.Va:a)return a.Va(a,b,c);var d;d=Ka[n(null==a?null:a)];if(!d&&(d=Ka._,!d))throw x("IVector.-assoc-n",a);return d.call(null,a,b,c)}function La(a){if(a?a.jb:a)return a.state;var b;b=La[n(null==a?null:a)];if(!b&&(b=La._,!b))throw x("IDeref.-deref",a);return b.call(null,a)}var Ma={};
function Na(a){if(a?a.A:a)return a.A(a);var b;b=Na[n(null==a?null:a)];if(!b&&(b=Na._,!b))throw x("IMeta.-meta",a);return b.call(null,a)}var Oa={};function Pa(a,b){if(a?a.C:a)return a.C(a,b);var c;c=Pa[n(null==a?null:a)];if(!c&&(c=Pa._,!c))throw x("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var Qa={},Ra=function(){function a(a,b,c){if(a?a.Q:a)return a.Q(a,b,c);var g;g=Ra[n(null==a?null:a)];if(!g&&(g=Ra._,!g))throw x("IReduce.-reduce",a);return g.call(null,a,b,c)}function b(a,b){if(a?a.P:a)return a.P(a,b);var c;c=Ra[n(null==a?null:a)];if(!c&&(c=Ra._,!c))throw x("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}();
function Sa(a,b){if(a?a.u:a)return a.u(a,b);var c;c=Sa[n(null==a?null:a)];if(!c&&(c=Sa._,!c))throw x("IEquiv.-equiv",a);return c.call(null,a,b)}function Ta(a){if(a?a.v:a)return a.v(a);var b;b=Ta[n(null==a?null:a)];if(!b&&(b=Ta._,!b))throw x("IHash.-hash",a);return b.call(null,a)}var Ua={};function Va(a){if(a?a.B:a)return a.B(a);var b;b=Va[n(null==a?null:a)];if(!b&&(b=Va._,!b))throw x("ISeqable.-seq",a);return b.call(null,a)}var Wa={};
function F(a,b){if(a?a.eb:a)return a.eb(0,b);var c;c=F[n(null==a?null:a)];if(!c&&(c=F._,!c))throw x("IWriter.-write",a);return c.call(null,a,b)}var Xa={};function Ya(a,b,c){if(a?a.t:a)return a.t(a,b,c);var d;d=Ya[n(null==a?null:a)];if(!d&&(d=Ya._,!d))throw x("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function Za(a,b,c){if(a?a.cb:a)return a.cb(0,b,c);var d;d=Za[n(null==a?null:a)];if(!d&&(d=Za._,!d))throw x("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function $a(a){if(a?a.sa:a)return a.sa(a);var b;b=$a[n(null==a?null:a)];if(!b&&(b=$a._,!b))throw x("IEditableCollection.-as-transient",a);return b.call(null,a)}function ab(a,b){if(a?a.Ba:a)return a.Ba(a,b);var c;c=ab[n(null==a?null:a)];if(!c&&(c=ab._,!c))throw x("ITransientCollection.-conj!",a);return c.call(null,a,b)}function bb(a){if(a?a.Ca:a)return a.Ca(a);var b;b=bb[n(null==a?null:a)];if(!b&&(b=bb._,!b))throw x("ITransientCollection.-persistent!",a);return b.call(null,a)}
function cb(a,b,c){if(a?a.ua:a)return a.ua(a,b,c);var d;d=cb[n(null==a?null:a)];if(!d&&(d=cb._,!d))throw x("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function db(a,b,c){if(a?a.bb:a)return a.bb(0,b,c);var d;d=db[n(null==a?null:a)];if(!d&&(d=db._,!d))throw x("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function eb(a){if(a?a.Ya:a)return a.Ya();var b;b=eb[n(null==a?null:a)];if(!b&&(b=eb._,!b))throw x("IChunk.-drop-first",a);return b.call(null,a)}
function fb(a){if(a?a.Fa:a)return a.Fa(a);var b;b=fb[n(null==a?null:a)];if(!b&&(b=fb._,!b))throw x("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function gb(a){if(a?a.Ga:a)return a.Ga(a);var b;b=gb[n(null==a?null:a)];if(!b&&(b=gb._,!b))throw x("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function hb(a){if(a?a.Ea:a)return a.Ea(a);var b;b=hb[n(null==a?null:a)];if(!b&&(b=hb._,!b))throw x("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function ib(a){this.ub=a;this.o=0;this.g=1073741824}ib.prototype.eb=function(a,b){return this.ub.append(b)};function jb(a){var b=new da;a.t(null,new ib(b),ia());return""+z(b)}function kb(a,b){if(s(G.a?G.a(a,b):G.call(null,a,b)))return 0;var c=s(a.H)?!1:!0;if(s(c?b.H:c))return-1;if(s(a.H)){if(!s(b.H))return 1;c=lb.a?lb.a(a.H,b.H):lb.call(null,a.H,b.H);return 0===c?lb.a?lb.a(a.name,b.name):lb.call(null,a.name,b.name):c}return mb?lb.a?lb.a(a.name,b.name):lb.call(null,a.name,b.name):null}
function nb(a,b,c,d,e){this.H=a;this.name=b;this.ia=c;this.ja=d;this.la=e;this.g=2154168321;this.o=4096}h=nb.prototype;h.t=function(a,b){return F(b,this.ia)};h.v=function(){var a=this.ja;return null!=a?a:this.ja=a=ob.a?ob.a(H.c?H.c(this.H):H.call(null,this.H),H.c?H.c(this.name):H.call(null,this.name)):ob.call(null,H.c?H.c(this.H):H.call(null,this.H),H.c?H.c(this.name):H.call(null,this.name))};h.C=function(a,b){return new nb(this.H,this.name,this.ia,this.ja,b)};h.A=function(){return this.la};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return Ba.b(c,this,null);case 3:return Ba.b(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return Ba.b(a,this,null)};h.a=function(a,b){return Ba.b(a,this,b)};h.u=function(a,b){return b instanceof nb?this.ia===b.ia:!1};h.toString=function(){return this.ia};
function I(a){if(null==a)return null;if(a&&(a.g&8388608||a.Cb))return a.B(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new pb(a,0);if(u(Ua,a))return Va(a);if(w)throw Error([z(a),z("is not ISeqable")].join(""));return null}function J(a){if(null==a)return null;if(a&&(a.g&64||a.ta))return a.R(null);a=I(a);return null==a?null:D(a)}function K(a){return null!=a?a&&(a.g&64||a.ta)?a.T(null):(a=I(a))?E(a):L:L}
function M(a){return null==a?null:a&&(a.g&128||a.Bb)?a.da(null):I(K(a))}
var G=function(){function a(a,b){return null==a?null==b:a===b||Sa(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(M(e))a=d,d=J(e),e=M(e);else return b.a(d,J(e));else return!1}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);
default:return c.f(b,e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.h=c.h;b.c=function(){return!0};b.a=a;b.f=c.f;return b}();ta["null"]=!0;ua["null"]=function(){return 0};Date.prototype.u=function(a,b){return b instanceof Date&&this.toString()===b.toString()};Sa.number=function(a,b){return a===b};Ma["function"]=!0;Na["function"]=function(){return null};sa["function"]=!0;Ta._=function(a){return a[aa]||(a[aa]=++ba)};
var qb=function(){function a(a,b,c,d){for(var l=ua(a);;)if(d<l)c=b.a?b.a(c,B.a(a,d)):b.call(null,c,B.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=ua(a),l=0;;)if(l<d)c=b.a?b.a(c,B.a(a,l)):b.call(null,c,B.a(a,l)),l+=1;else return c}function c(a,b){var c=ua(a);if(0===c)return b.W?b.W():b.call(null);for(var d=B.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,B.a(a,l)):b.call(null,d,B.a(a,l)),l+=1;else return d}var d=null,d=function(d,f,g,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,
d,f,g);case 4:return a.call(this,d,f,g,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.b=b;d.j=a;return d}(),rb=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.W?b.W():b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,f,g,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,g);case 4:return a.call(this,d,f,g,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.b=b;d.j=a;return d}();function sb(a){return a?a.g&2||a.ib?!0:a.g?!1:u(ta,a):u(ta,a)}function tb(a){return a?a.g&16||a.Za?!0:a.g?!1:u(ya,a):u(ya,a)}function pb(a,b){this.d=a;this.k=b;this.g=166199550;this.o=8192}h=pb.prototype;h.v=function(){return ub.c?ub.c(this):ub.call(null,this)};
h.da=function(){return this.k+1<this.d.length?new pb(this.d,this.k+1):null};h.F=function(a,b){return O.a?O.a(b,this):O.call(null,b,this)};h.toString=function(){return jb(this)};h.P=function(a,b){return rb.j(this.d,b,this.d[this.k],this.k+1)};h.Q=function(a,b,c){return rb.j(this.d,b,c,this.k)};h.B=function(){return this};h.J=function(){return this.d.length-this.k};h.R=function(){return this.d[this.k]};h.T=function(){return this.k+1<this.d.length?new pb(this.d,this.k+1):L};
h.u=function(a,b){return vb.a?vb.a(this,b):vb.call(null,this,b)};h.G=function(a,b){var c=b+this.k;return c<this.d.length?this.d[c]:null};h.Y=function(a,b,c){a=b+this.k;return a<this.d.length?this.d[a]:c};h.K=function(){return L};
var wb=function(){function a(a,b){return b<a.length?new pb(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}(),N=function(){function a(a,b){return wb.a(a,b)}function b(a){return wb.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.c=b;c.a=a;return c}();Sa._=function(a,b){return a===b};
var xb=function(){function a(a,b){return null!=a?xa(a,b):xa(L,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(s(e))a=b.a(a,d),d=J(e),e=M(e);else return b.a(a,d)}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.f(b,e,N(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.m=2;b.h=c.h;b.a=a;b.f=c.f;return b}();function P(a){if(null!=a)if(a&&(a.g&2||a.ib))a=a.J(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(u(ta,a))a=ua(a);else if(w)a:{a=I(a);for(var b=0;;){if(sb(a)){a=b+ua(a);break a}a=M(a);b+=1}a=void 0}else a=null;else a=0;return a}
var yb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return I(a)?J(a):c;if(tb(a))return B.b(a,b,c);if(I(a))a=M(a),b-=1;else return w?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(I(a))return J(a);throw Error("Index out of bounds");}if(tb(a))return B.a(a,b);if(I(a)){var c=M(a),g=b-1;a=c;b=g}else{if(w)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}(),Q=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.g&16||a.Za))return a.Y(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(u(ya,a))return B.a(a,b);if(a?a.g&64||a.ta||(a.g?0:u(za,a)):u(za,a))return yb.b(a,b,c);if(w)throw Error([z("nth not supported on this type "),z(pa(oa(a)))].join(""));return null}function b(a,
b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.g&16||a.Za))return a.G(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(u(ya,a))return B.a(a,b);if(a?a.g&64||a.ta||(a.g?0:u(za,a)):u(za,a))return yb.a(a,b);if(w)throw Error([z("nth not supported on this type "),z(pa(oa(a)))].join(""));return null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,
e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}(),R=function(){function a(a,b,c){return null!=a?a&&(a.g&256||a.kb)?a.M(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:u(Aa,a)?Ba.b(a,b,c):w?c:null:c}function b(a,b){return null==a?null:a&&(a.g&256||a.kb)?a.L(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:u(Aa,a)?Ba.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}(),S=function(){function a(a,b,c){return null!=a?Ca(a,b,c):zb.a?zb.a([b],[c]):zb.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=N(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.b(a,d,e),s(l))d=J(l),e=J(M(l)),l=M(M(l));else return a}a.m=3;a.h=function(a){var b=J(a);a=M(a);var d=J(a);
a=M(a);var l=J(a);a=K(a);return c(b,d,l,a)};a.f=c;return a}(),b=function(b,e,f,g){switch(arguments.length){case 3:return a.call(this,b,e,f);default:return c.f(b,e,f,N(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.m=3;b.h=c.h;b.b=a;b.f=c.f;return b}(),Ab=function(){function a(a,b){return null==a?null:Ea(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;){if(null==
a)return null;a=b.a(a,d);if(s(e))d=J(e),e=M(e);else return a}}a.m=2;a.h=function(a){var b=J(a);a=M(a);var d=J(a);a=K(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return b;case 2:return a.call(this,b,e);default:return c.f(b,e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.h=c.h;b.c=function(a){return a};b.a=a;b.f=c.f;return b}();function Bb(a){var b="function"==n(a);return b?b:a?s(s(null)?null:a.hb)?!0:a.Gb?!1:u(sa,a):u(sa,a)}
var Eb=function Cb(b,c){return Bb(b)&&!(b?b.g&262144||b.Fb||(b.g?0:u(Oa,b)):u(Oa,b))?Cb(function(){"undefined"===typeof ea&&(ea=function(b,c,f,g){this.i=b;this.ya=c;this.wb=f;this.sb=g;this.o=0;this.g=393217},ea.Xa=!0,ea.Wa="cljs.core/t17101",ea.fb=function(b,c){return F(c,"cljs.core/t17101")},ea.prototype.call=function(){function b(d,g){d=this;var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,d,k)}function c(b,d){return Db.a?Db.a(b.ya,d):Db.call(null,
b.ya,d)}b.m=1;b.h=function(b){var d=J(b);b=K(b);return c(d,b)};b.f=c;return b}(),ea.prototype.apply=function(b,c){return this.call.apply(this,[this].concat(A(c)))},ea.prototype.a=function(){function b(d){var g=null;0<arguments.length&&(g=N(Array.prototype.slice.call(arguments,0),0));return c.call(this,g)}function c(b){return Db.a?Db.a(self__.ya,b):Db.call(null,self__.ya,b)}b.m=0;b.h=function(b){b=I(b);return c(b)};b.f=c;return b}(),ea.prototype.hb=!0,ea.prototype.A=function(){return this.sb},ea.prototype.C=
function(b,c){return new ea(this.i,this.ya,this.wb,c)});return new ea(c,b,Cb,null)}(),c):null==b?null:Pa(b,c)};function Fb(a){var b=null!=a;return(b?a?a.g&131072||a.mb||(a.g?0:u(Ma,a)):u(Ma,a):b)?Na(a):null}var Gb={},Hb=0;
function H(a){if(a&&(a.g&4194304||a.zb))a=a.v(null);else if("number"===typeof a)a=Math.floor(a)%2147483647;else if(!0===a)a=1;else if(!1===a)a=0;else if("string"===typeof a){255<Hb&&(Gb={},Hb=0);var b=Gb[a];if("number"!==typeof b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;Gb[a]=b;Hb+=1}a=b}else a=null==a?0:w?Ta(a):null;return a}function Ib(a){return a?a.g&16384||a.Eb?!0:a.g?!1:u(Ia,a):u(Ia,a)}function Jb(a){return a?a.o&512||a.xb?!0:!1:!1}
function Kb(a){var b=[];ca(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Lb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}function Mb(a){return null==a?!1:a?a.g&64||a.ta?!0:a.g?!1:u(za,a):u(za,a)}function Nb(a){return s(a)?!0:!1}function lb(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(oa(a)===oa(b))return a&&(a.o&2048||a.za)?a.Aa(null,b):a>b?1:a<b?-1:0;if(w)throw Error("compare on non-nil objects of different types");return null}
var Ob=function(){function a(a,b,c,g){for(;;){var k=lb(Q.a(a,g),Q.a(b,g));if(0===k&&g+1<c)g+=1;else return k}}function b(a,b){var f=P(a),g=P(b);return f<g?-1:f>g?1:w?c.j(a,b,f,0):null}var c=null,c=function(c,e,f,g){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,f,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.j=a;return c}(),Qb=function(){function a(a,b,c){for(c=I(c);;)if(c)b=a.a?a.a(b,J(c)):a.call(null,b,J(c)),c=M(c);else return b}function b(a,
b){var c=I(b);return c?qa.b?qa.b(a,J(c),M(c)):qa.call(null,a,J(c),M(c)):a.W?a.W():a.call(null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}(),qa=function(){function a(a,b,c){return c&&(c.g&524288||c.ob)?c.Q(null,a,b):c instanceof Array?rb.b(c,a,b):"string"===typeof c?rb.b(c,a,b):u(Qa,c)?Ra.b(c,a,b):w?Qb.b(a,b,c):null}function b(a,b){return b&&(b.g&524288||
b.ob)?b.P(null,a):b instanceof Array?rb.a(b,a):"string"===typeof b?rb.a(b,a):u(Qa,b)?Ra.a(b,a):w?Qb.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}();function Rb(a){return 0<=a?Math.floor.c?Math.floor.c(a):Math.floor.call(null,a):Math.ceil.c?Math.ceil.c(a):Math.ceil.call(null,a)}
function Sb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}function Tb(a){var b=1;for(a=I(a);;)if(a&&0<b)b-=1,a=M(a);else return a}
var z=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new da(b.c(a)),l=d;;)if(s(l))e=e.append(b.c(J(l))),l=M(l);else return e.toString()}a.m=1;a.h=function(a){var b=J(a);a=K(a);return c(b,a)};a.f=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.f(b,N(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.h=c.h;b.W=function(){return""};b.c=a;b.f=c.f;return b}();function vb(a,b){return Nb((b?b.g&16777216||b.Db||(b.g?0:u(Wa,b)):u(Wa,b))?function(){for(var c=I(a),d=I(b);;){if(null==c)return null==d;if(null==d)return!1;if(G.a(J(c),J(d)))c=M(c),d=M(d);else return w?!1:null}}():null)}function ob(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function ub(a){if(I(a)){var b=H(J(a));for(a=M(a);;){if(null==a)return b;b=ob(b,H(J(a)));a=M(a)}}else return 0}function Ub(a){var b=0;for(a=I(a);;)if(a){var c=J(a),b=(b+(H(Vb.c?Vb.c(c):Vb.call(null,c))^H(Wb.c?Wb.c(c):Wb.call(null,c))))%4503599627370496;a=M(a)}else return b}function Xb(a,b,c,d,e){this.i=a;this.va=b;this.ga=c;this.count=d;this.l=e;this.g=65937646;this.o=8192}h=Xb.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.da=function(){return 1===this.count?null:this.ga};
h.F=function(a,b){return new Xb(this.i,b,this,this.count+1,null)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return this};h.J=function(){return this.count};h.R=function(){return this.va};h.T=function(){return 1===this.count?L:this.ga};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new Xb(b,this.va,this.ga,this.count,this.l)};h.A=function(){return this.i};h.K=function(){return L};
function Yb(a){this.i=a;this.g=65937614;this.o=8192}h=Yb.prototype;h.v=function(){return 0};h.da=function(){return null};h.F=function(a,b){return new Xb(this.i,b,null,1,null)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return null};h.J=function(){return 0};h.R=function(){return null};h.T=function(){return L};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new Yb(b)};h.A=function(){return this.i};
h.K=function(){return this};var L=new Yb(null),Zb=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof pb&&0===a.k)b=a.d;else a:{for(b=[];;)if(null!=a)b.push(a.R(null)),a=a.da(null);else break a;b=void 0}a=b.length;for(var e=L;;)if(0<a){var f=a-1,e=e.F(null,b[a-1]);a=f}else return e}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}();
function $b(a,b,c,d){this.i=a;this.va=b;this.ga=c;this.l=d;this.g=65929452;this.o=8192}h=$b.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.da=function(){return null==this.ga?null:I(this.ga)};h.F=function(a,b){return new $b(null,b,this,this.l)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return this};h.R=function(){return this.va};h.T=function(){return null==this.ga?L:this.ga};
h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new $b(b,this.va,this.ga,this.l)};h.A=function(){return this.i};h.K=function(){return Eb(L,this.i)};function O(a,b){var c=null==b;return(c?c:b&&(b.g&64||b.ta))?new $b(null,a,b,null):new $b(null,a,I(b),null)}function T(a,b,c,d){this.H=a;this.name=b;this.ha=c;this.ja=d;this.g=2153775105;this.o=4096}h=T.prototype;h.t=function(a,b){return F(b,[z(":"),z(this.ha)].join(""))};
h.v=function(){null==this.ja&&(this.ja=ob(H(this.H),H(this.name))+2654435769);return this.ja};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return R.a(c,this);case 3:return R.b(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return R.a(a,this)};h.a=function(a,b){return R.b(a,this,b)};h.u=function(a,b){return b instanceof T?this.ha===b.ha:!1};
h.toString=function(){return[z(":"),z(this.ha)].join("")};
var bc=function(){function a(a,b){return new T(a,b,[z(s(a)?[z(a),z("/")].join(""):null),z(b)].join(""),null)}function b(a){if(a instanceof T)return a;if(a instanceof nb){var b;if(a&&(a.o&4096||a.nb))b=a.H;else throw Error([z("Doesn't support namespace: "),z(a)].join(""));return new T(b,ac.c?ac.c(a):ac.call(null,a),a.ia,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new T(b[0],b[1],a,null):new T(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,
c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}();function cc(a,b,c,d){this.i=a;this.pa=b;this.q=c;this.l=d;this.o=0;this.g=32374988}h=cc.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.da=function(){Va(this);return null==this.q?null:M(this.q)};h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};function dc(a){null!=a.pa&&(a.q=a.pa.W?a.pa.W():a.pa.call(null),a.pa=null);return a.q}
h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){dc(this);if(null==this.q)return null;for(var a=this.q;;)if(a instanceof cc)a=dc(a);else return this.q=a,I(this.q)};h.R=function(){Va(this);return null==this.q?null:J(this.q)};h.T=function(){Va(this);return null!=this.q?K(this.q):L};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new cc(b,this.pa,this.q,this.l)};h.A=function(){return this.i};h.K=function(){return Eb(L,this.i)};
function ec(a,b){this.Da=a;this.end=b;this.o=0;this.g=2}ec.prototype.J=function(){return this.end};ec.prototype.add=function(a){this.Da[this.end]=a;return this.end+=1};ec.prototype.I=function(){var a=new fc(this.Da,0,this.end);this.Da=null;return a};function fc(a,b,c){this.d=a;this.r=b;this.end=c;this.o=0;this.g=524306}h=fc.prototype;h.P=function(a,b){return rb.j(this.d,b,this.d[this.r],this.r+1)};h.Q=function(a,b,c){return rb.j(this.d,b,c,this.r)};
h.Ya=function(){if(this.r===this.end)throw Error("-drop-first of empty chunk");return new fc(this.d,this.r+1,this.end)};h.G=function(a,b){return this.d[this.r+b]};h.Y=function(a,b,c){return 0<=b&&b<this.end-this.r?this.d[this.r+b]:c};h.J=function(){return this.end-this.r};
var gc=function(){function a(a,b,c){return new fc(a,b,c)}function b(a,b){return new fc(a,b,a.length)}function c(a){return new fc(a,0,a.length)}var d=null,d=function(d,f,g){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.a=b;d.b=a;return d}();function hc(a,b,c,d){this.I=a;this.ba=b;this.i=c;this.l=d;this.g=31850732;this.o=1536}h=hc.prototype;
h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.da=function(){if(1<ua(this.I))return new hc(eb(this.I),this.ba,this.i,null);var a=Va(this.ba);return null==a?null:a};h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};h.B=function(){return this};h.R=function(){return B.a(this.I,0)};h.T=function(){return 1<ua(this.I)?new hc(eb(this.I),this.ba,this.i,null):null==this.ba?L:this.ba};h.Ea=function(){return null==this.ba?null:this.ba};
h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new hc(this.I,this.ba,b,this.l)};h.A=function(){return this.i};h.K=function(){return Eb(L,this.i)};h.Fa=function(){return this.I};h.Ga=function(){return null==this.ba?L:this.ba};function ic(a,b){return 0===ua(a)?b:new hc(a,b,null,null)}function jc(a,b){a.add(b)}function kc(a){for(var b=[];;)if(I(a))b.push(J(a)),a=M(a);else return b}function lc(a,b){if(sb(a))return P(a);for(var c=a,d=b,e=0;;)if(0<d&&I(c))c=M(c),d-=1,e+=1;else return e}
var nc=function mc(b){return null==b?null:null==M(b)?I(J(b)):w?O(J(b),mc(M(b))):null},oc=function(){function a(a,b){return new cc(null,function(){var c=I(a);return c?Jb(c)?ic(fb(c),d.a(gb(c),b)):O(J(c),d.a(K(c),b)):b},null,null)}function b(a){return new cc(null,function(){return a},null,null)}function c(){return new cc(null,function(){return null},null,null)}var d=null,e=function(){function a(c,d,e){var f=null;2<arguments.length&&(f=N(Array.prototype.slice.call(arguments,2),0));return b.call(this,
c,d,f)}function b(a,c,e){return function p(a,b){return new cc(null,function(){var c=I(a);return c?Jb(c)?ic(fb(c),p(gb(c),b)):O(J(c),p(K(c),b)):s(b)?p(J(b),M(b)):null},null,null)}(d.a(a,c),e)}a.m=2;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=K(a);return b(c,d,a)};a.f=b;return a}(),d=function(d,g,k){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,d);case 2:return a.call(this,d,g);default:return e.f(d,g,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);
};d.m=2;d.h=e.h;d.W=c;d.c=b;d.a=a;d.f=e.f;return d}(),pc=function(){function a(a,b,c,d){return O(a,O(b,O(c,d)))}function b(a,b,c){return O(a,O(b,c))}var c=null,d=function(){function a(c,d,e,m,q){var p=null;4<arguments.length&&(p=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,p)}function b(a,c,d,e,f){return O(a,O(c,O(d,O(e,nc(f)))))}a.m=4;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var q=J(a);a=K(a);return b(c,d,e,q,a)};a.f=b;return a}(),c=function(c,
f,g,k,l){switch(arguments.length){case 1:return I(c);case 2:return O(c,f);case 3:return b.call(this,c,f,g);case 4:return a.call(this,c,f,g,k);default:return d.f(c,f,g,k,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.m=4;c.h=d.h;c.c=function(a){return I(a)};c.a=function(a,b){return O(a,b)};c.b=b;c.j=a;c.f=d.f;return c}(),qc=function(){var a=null,b=function(){function a(c,f,g){var k=null;2<arguments.length&&(k=N(Array.prototype.slice.call(arguments,2),0));return b.call(this,c,f,
k)}function b(a,c,d){for(;;)if(a=ab(a,c),s(d))c=J(d),d=M(d);else return a}a.m=2;a.h=function(a){var c=J(a);a=M(a);var g=J(a);a=K(a);return b(c,g,a)};a.f=b;return a}(),a=function(a,d,e){switch(arguments.length){case 2:return ab(a,d);default:return b.f(a,d,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};a.m=2;a.h=b.h;a.a=function(a,b){return ab(a,b)};a.f=b.f;return a}(),rc=function(){var a=null,b=function(){function a(c,f,g,k){var l=null;3<arguments.length&&(l=N(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,f,g,l)}function b(a,c,d,k){for(;;)if(a=cb(a,c,d),s(k))c=J(k),d=J(M(k)),k=M(M(k));else return a}a.m=3;a.h=function(a){var c=J(a);a=M(a);var g=J(a);a=M(a);var k=J(a);a=K(a);return b(c,g,k,a)};a.f=b;return a}(),a=function(a,d,e,f){switch(arguments.length){case 3:return cb(a,d,e);default:return b.f(a,d,e,N(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.m=3;a.h=b.h;a.b=function(a,b,e){return cb(a,b,e)};a.f=b.f;return a}();
function sc(a,b,c){var d=I(c);if(0===b)return a.W?a.W():a.call(null);c=D(d);var e=E(d);if(1===b)return a.c?a.c(c):a.c?a.c(c):a.call(null,c);var d=D(e),f=E(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=D(f),g=E(f);if(3===b)return a.b?a.b(c,d,e):a.b?a.b(c,d,e):a.call(null,c,d,e);var f=D(g),k=E(g);if(4===b)return a.j?a.j(c,d,e,f):a.j?a.j(c,d,e,f):a.call(null,c,d,e,f);var g=D(k),l=E(k);if(5===b)return a.w?a.w(c,d,e,f,g):a.w?a.w(c,d,e,f,g):a.call(null,c,d,e,f,g);var k=D(l),m=E(l);
if(6===b)return a.X?a.X(c,d,e,f,g,k):a.X?a.X(c,d,e,f,g,k):a.call(null,c,d,e,f,g,k);var l=D(m),q=E(m);if(7===b)return a.ma?a.ma(c,d,e,f,g,k,l):a.ma?a.ma(c,d,e,f,g,k,l):a.call(null,c,d,e,f,g,k,l);var m=D(q),p=E(q);if(8===b)return a.Sa?a.Sa(c,d,e,f,g,k,l,m):a.Sa?a.Sa(c,d,e,f,g,k,l,m):a.call(null,c,d,e,f,g,k,l,m);var q=D(p),t=E(p);if(9===b)return a.Ta?a.Ta(c,d,e,f,g,k,l,m,q):a.Ta?a.Ta(c,d,e,f,g,k,l,m,q):a.call(null,c,d,e,f,g,k,l,m,q);var p=D(t),C=E(t);if(10===b)return a.Ha?a.Ha(c,d,e,f,g,k,l,m,q,p):a.Ha?
a.Ha(c,d,e,f,g,k,l,m,q,p):a.call(null,c,d,e,f,g,k,l,m,q,p);var t=D(C),y=E(C);if(11===b)return a.Ia?a.Ia(c,d,e,f,g,k,l,m,q,p,t):a.Ia?a.Ia(c,d,e,f,g,k,l,m,q,p,t):a.call(null,c,d,e,f,g,k,l,m,q,p,t);var C=D(y),v=E(y);if(12===b)return a.Ja?a.Ja(c,d,e,f,g,k,l,m,q,p,t,C):a.Ja?a.Ja(c,d,e,f,g,k,l,m,q,p,t,C):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C);var y=D(v),V=E(v);if(13===b)return a.Ka?a.Ka(c,d,e,f,g,k,l,m,q,p,t,C,y):a.Ka?a.Ka(c,d,e,f,g,k,l,m,q,p,t,C,y):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y);var v=D(V),Z=E(V);
if(14===b)return a.La?a.La(c,d,e,f,g,k,l,m,q,p,t,C,y,v):a.La?a.La(c,d,e,f,g,k,l,m,q,p,t,C,y,v):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v);var V=D(Z),ha=E(Z);if(15===b)return a.Ma?a.Ma(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V):a.Ma?a.Ma(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,V);var Z=D(ha),va=E(ha);if(16===b)return a.Na?a.Na(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z):a.Na?a.Na(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z);var ha=D(va),Ja=E(va);if(17===b)return a.Oa?
a.Oa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha):a.Oa?a.Oa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha);var va=D(Ja),Pb=E(Ja);if(18===b)return a.Pa?a.Pa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va):a.Pa?a.Pa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va);Ja=D(Pb);Pb=E(Pb);if(19===b)return a.Qa?a.Qa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va,Ja):a.Qa?a.Qa(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va,Ja):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,
V,Z,ha,va,Ja);var Mc=D(Pb);E(Pb);if(20===b)return a.Ra?a.Ra(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va,Ja,Mc):a.Ra?a.Ra(c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va,Ja,Mc):a.call(null,c,d,e,f,g,k,l,m,q,p,t,C,y,v,V,Z,ha,va,Ja,Mc);throw Error("Only up to 20 arguments supported on functions");}
var Db=function(){function a(a,b,c,d,e){b=pc.j(b,c,d,e);c=a.m;return a.h?(d=lc(b,c+1),d<=c?sc(a,d,b):a.h(b)):a.apply(a,kc(b))}function b(a,b,c,d){b=pc.b(b,c,d);c=a.m;return a.h?(d=lc(b,c+1),d<=c?sc(a,d,b):a.h(b)):a.apply(a,kc(b))}function c(a,b,c){b=pc.a(b,c);c=a.m;if(a.h){var d=lc(b,c+1);return d<=c?sc(a,d,b):a.h(b)}return a.apply(a,kc(b))}function d(a,b){var c=a.m;if(a.h){var d=lc(b,c+1);return d<=c?sc(a,d,b):a.h(b)}return a.apply(a,kc(b))}var e=null,f=function(){function a(c,d,e,f,g,C){var y=null;
5<arguments.length&&(y=N(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,f,g,y)}function b(a,c,d,e,f,g){c=O(c,O(d,O(e,O(f,nc(g)))));d=a.m;return a.h?(e=lc(c,d+1),e<=d?sc(a,e,c):a.h(c)):a.apply(a,kc(c))}a.m=5;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=M(a);var g=J(a);a=K(a);return b(c,d,e,f,g,a)};a.f=b;return a}(),e=function(e,k,l,m,q,p){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,q);default:return f.f(e,k,l,m,q,N(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.m=5;e.h=f.h;e.a=d;e.b=c;e.j=b;e.w=a;e.f=f.f;return e}();function tc(a,b){for(;;){if(null==I(b))return!0;if(s(a.c?a.c(J(b)):a.call(null,J(b)))){var c=a,d=M(b);a=c;b=d}else return w?!1:null}}function uc(a){for(var b=vc;;)if(I(a)){var c=b.c?b.c(J(a)):b.call(null,J(a));if(s(c))return c;a=M(a)}else return null}function vc(a){return a}
var wc=function(){function a(a,b,c,e){return new cc(null,function(){var m=I(b),q=I(c),p=I(e);return m&&q&&p?O(a.b?a.b(J(m),J(q),J(p)):a.call(null,J(m),J(q),J(p)),d.j(a,K(m),K(q),K(p))):null},null,null)}function b(a,b,c){return new cc(null,function(){var e=I(b),m=I(c);return e&&m?O(a.a?a.a(J(e),J(m)):a.call(null,J(e),J(m)),d.b(a,K(e),K(m))):null},null,null)}function c(a,b){return new cc(null,function(){var c=I(b);if(c){if(Jb(c)){for(var e=fb(c),m=P(e),q=new ec(Array(m),0),p=0;;)if(p<m){var t=a.c?a.c(B.a(e,
p)):a.call(null,B.a(e,p));q.add(t);p+=1}else break;return ic(q.I(),d.a(a,gb(c)))}return O(a.c?a.c(J(c)):a.call(null,J(c)),d.a(a,K(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,f,p){var t=null;4<arguments.length&&(t=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,t)}function b(a,c,e,f,g){var t=function y(a){return new cc(null,function(){var b=d.a(I,a);return tc(vc,b)?O(d.a(J,b),y(d.a(K,b))):null},null,null)};return d.a(function(){return function(b){return Db.a(a,
b)}}(t),t(xb.f(g,f,N([e,c],0))))}a.m=4;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);var f=J(a);a=K(a);return b(c,d,e,f,a)};a.f=b;return a}(),d=function(d,g,k,l,m){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,d,g,k);case 4:return a.call(this,d,g,k,l);default:return e.f(d,g,k,l,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.h=e.h;d.a=c;d.b=b;d.j=a;d.f=e.f;return d}(),yc=function xc(b,c,d){var e=Q.b(c,0,null);return(c=
Tb(c))?S.b(b,e,xc(R.a(b,e),c,d)):S.b(b,e,d)},zc=function(){function a(a,b,c,d,f,p){var t=Q.b(b,0,null);return(b=Tb(b))?S.b(a,t,e.X(R.a(a,t),b,c,d,f,p)):S.b(a,t,c.j?c.j(R.a(a,t),d,f,p):c.call(null,R.a(a,t),d,f,p))}function b(a,b,c,d,f){var p=Q.b(b,0,null);return(b=Tb(b))?S.b(a,p,e.w(R.a(a,p),b,c,d,f)):S.b(a,p,c.b?c.b(R.a(a,p),d,f):c.call(null,R.a(a,p),d,f))}function c(a,b,c,d){var f=Q.b(b,0,null);return(b=Tb(b))?S.b(a,f,e.j(R.a(a,f),b,c,d)):S.b(a,f,c.a?c.a(R.a(a,f),d):c.call(null,R.a(a,f),d))}function d(a,
b,c){var d=Q.b(b,0,null);return(b=Tb(b))?S.b(a,d,e.b(R.a(a,d),b,c)):S.b(a,d,c.c?c.c(R.a(a,d)):c.call(null,R.a(a,d)))}var e=null,f=function(){function a(c,d,e,f,g,C,y){var v=null;6<arguments.length&&(v=N(Array.prototype.slice.call(arguments,6),0));return b.call(this,c,d,e,f,g,C,v)}function b(a,c,d,f,g,k,y){var v=Q.b(c,0,null);return(c=Tb(c))?S.b(a,v,Db.f(e,R.a(a,v),c,d,f,N([g,k,y],0))):S.b(a,v,Db.f(d,R.a(a,v),f,g,k,N([y],0)))}a.m=6;a.h=function(a){var c=J(a);a=M(a);var d=J(a);a=M(a);var e=J(a);a=M(a);
var f=J(a);a=M(a);var g=J(a);a=M(a);var y=J(a);a=K(a);return b(c,d,e,f,g,y,a)};a.f=b;return a}(),e=function(e,k,l,m,q,p,t){switch(arguments.length){case 3:return d.call(this,e,k,l);case 4:return c.call(this,e,k,l,m);case 5:return b.call(this,e,k,l,m,q);case 6:return a.call(this,e,k,l,m,q,p);default:return f.f(e,k,l,m,q,p,N(arguments,6))}throw Error("Invalid arity: "+arguments.length);};e.m=6;e.h=f.h;e.b=d;e.j=c;e.w=b;e.X=a;e.f=f.f;return e}();function Ac(a,b){this.n=a;this.d=b}
function Bc(a){return new Ac(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Cc(a){a=a.e;return 32>a?0:a-1>>>5<<5}function Dc(a,b,c){for(;;){if(0===b)return c;var d=Bc(a);d.d[0]=c;c=d;b-=5}}var Fc=function Ec(b,c,d,e){var f=new Ac(d.n,A(d.d)),g=b.e-1>>>c&31;5===c?f.d[g]=e:(d=d.d[g],b=null!=d?Ec(b,c-5,d,e):Dc(null,c-5,e),f.d[g]=b);return f};
function Gc(a,b){throw Error([z("No item "),z(a),z(" in vector of length "),z(b)].join(""));}function Hc(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.d[0];else return b.d}function Ic(a,b){if(b>=Cc(a))return a.D;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.d[b>>>d&31],d=e;else return c.d}function Jc(a,b){return 0<=b&&b<a.e?Ic(a,b):Gc(b,a.e)}var Lc=function Kc(b,c,d,e,f){var g=new Ac(d.n,A(d.d));if(0===c)g.d[e&31]=f;else{var k=e>>>c&31;b=Kc(b,c-5,d.d[k],e,f);g.d[k]=b}return g};
function U(a,b,c,d,e,f){this.i=a;this.e=b;this.shift=c;this.root=d;this.D=e;this.l=f;this.o=8196;this.g=167668511}h=U.prototype;h.sa=function(){return new Nc(this.e,this.shift,Oc.c?Oc.c(this.root):Oc.call(null,this.root),Pc.c?Pc.c(this.D):Pc.call(null,this.D))};h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){return"number"===typeof b?B.b(this,b,c):c};
h.ra=function(a,b,c){if("number"===typeof b)return Ka(this,b,c);throw Error("Vector's key for assoc must be a number.");};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.G(null,c);case 3:return this.Y(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return this.G(null,a)};h.a=function(a,b){return this.Y(null,a,b)};
h.F=function(a,b){if(32>this.e-Cc(this)){for(var c=this.D.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.D[e],e+=1;else break;d[c]=b;return new U(this.i,this.e+1,this.shift,this.root,d,null)}c=(d=this.e>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Bc(null),d.d[0]=this.root,e=Dc(null,this.shift,new Ac(null,this.D)),d.d[1]=e):d=Fc(this,this.shift,this.root,new Ac(null,this.D));return new U(this.i,this.e+1,c,d,[b],null)};h.$a=function(){return B.a(this,0)};h.ab=function(){return B.a(this,1)};
h.toString=function(){return jb(this)};h.P=function(a,b){return qb.a(this,b)};h.Q=function(a,b,c){return qb.b(this,b,c)};h.B=function(){return 0===this.e?null:32>=this.e?new pb(this.D,0):w?W.j?W.j(this,Hc(this),0,0):W.call(null,this,Hc(this),0,0):null};h.J=function(){return this.e};
h.Va=function(a,b,c){if(0<=b&&b<this.e)return Cc(this)<=b?(a=A(this.D),a[b&31]=c,new U(this.i,this.e,this.shift,this.root,a,null)):new U(this.i,this.e,this.shift,Lc(this,this.shift,this.root,b,c),this.D,null);if(b===this.e)return xa(this,c);if(w)throw Error([z("Index "),z(b),z(" out of bounds  [0,"),z(this.e),z("]")].join(""));return null};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new U(b,this.e,this.shift,this.root,this.D,this.l)};h.A=function(){return this.i};
h.G=function(a,b){return Jc(this,b)[b&31]};h.Y=function(a,b,c){return 0<=b&&b<this.e?Ic(this,b)[b&31]:c};h.K=function(){return Eb(Qc,this.i)};var X=new Ac(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Qc=new U(null,0,5,X,[],0);
function Rc(a,b){var c=a.length,d=b?a:A(a);if(32>c)return new U(null,c,5,X,d,null);for(var e=d.slice(0,32),f=32,g=(new U(null,32,5,X,e,null)).sa(null);;)if(f<c)e=f+1,g=qc.a(g,d[f]),f=e;else return bb(g)}var Sc=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return a instanceof pb&&0===a.k?Rc.a?Rc.a(a.d,!0):Rc.call(null,a.d,!0):bb(qa.b(ab,$a(Qc),a))}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}();
function Tc(a,b,c,d,e,f){this.s=a;this.U=b;this.k=c;this.r=d;this.i=e;this.l=f;this.g=32243948;this.o=1536}h=Tc.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.da=function(){if(this.r+1<this.U.length){var a=W.j?W.j(this.s,this.U,this.k,this.r+1):W.call(null,this.s,this.U,this.k,this.r+1);return null==a?null:a}return hb(this)};h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};
h.P=function(a,b){return qb.a(Uc.b?Uc.b(this.s,this.k+this.r,P(this.s)):Uc.call(null,this.s,this.k+this.r,P(this.s)),b)};h.Q=function(a,b,c){return qb.b(Uc.b?Uc.b(this.s,this.k+this.r,P(this.s)):Uc.call(null,this.s,this.k+this.r,P(this.s)),b,c)};h.B=function(){return this};h.R=function(){return this.U[this.r]};h.T=function(){if(this.r+1<this.U.length){var a=W.j?W.j(this.s,this.U,this.k,this.r+1):W.call(null,this.s,this.U,this.k,this.r+1);return null==a?L:a}return gb(this)};
h.Ea=function(){var a=this.k+this.U.length;return a<ua(this.s)?W.j?W.j(this.s,Ic(this.s,a),a,0):W.call(null,this.s,Ic(this.s,a),a,0):null};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return W.w?W.w(this.s,this.U,this.k,this.r,b):W.call(null,this.s,this.U,this.k,this.r,b)};h.K=function(){return Eb(Qc,this.i)};h.Fa=function(){return gc.a(this.U,this.r)};h.Ga=function(){var a=this.k+this.U.length;return a<ua(this.s)?W.j?W.j(this.s,Ic(this.s,a),a,0):W.call(null,this.s,Ic(this.s,a),a,0):L};
var W=function(){function a(a,b,c,d,l){return new Tc(a,b,c,d,l,null)}function b(a,b,c,d){return new Tc(a,b,c,d,null,null)}function c(a,b,c){return new Tc(a,Jc(a,b),b,c,null,null)}var d=null,d=function(d,f,g,k,l){switch(arguments.length){case 3:return c.call(this,d,f,g);case 4:return b.call(this,d,f,g,k);case 5:return a.call(this,d,f,g,k,l)}throw Error("Invalid arity: "+arguments.length);};d.b=c;d.j=b;d.w=a;return d}();
function Vc(a,b,c,d,e){this.i=a;this.ca=b;this.start=c;this.end=d;this.l=e;this.g=166617887;this.o=8192}h=Vc.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){return"number"===typeof b?B.b(this,b,c):c};h.ra=function(a,b,c){if("number"===typeof b)return Ka(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.G(null,c);case 3:return this.Y(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return this.G(null,a)};h.a=function(a,b){return this.Y(null,a,b)};
h.F=function(a,b){return Wc.w?Wc.w(this.i,Ka(this.ca,this.end,b),this.start,this.end+1,null):Wc.call(null,this.i,Ka(this.ca,this.end,b),this.start,this.end+1,null)};h.toString=function(){return jb(this)};h.P=function(a,b){return qb.a(this,b)};h.Q=function(a,b,c){return qb.b(this,b,c)};h.B=function(){var a=this;return function(b){return function d(e){return e===a.end?null:O(B.a(a.ca,e),new cc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
h.J=function(){return this.end-this.start};h.Va=function(a,b,c){var d=this,e=d.start+b;return Wc.w?Wc.w(d.i,S.b(d.ca,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):Wc.call(null,d.i,S.b(d.ca,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return Wc.w?Wc.w(b,this.ca,this.start,this.end,this.l):Wc.call(null,b,this.ca,this.start,this.end,this.l)};h.A=function(){return this.i};
h.G=function(a,b){return 0>b||this.end<=this.start+b?Gc(b,this.end-this.start):B.a(this.ca,this.start+b)};h.Y=function(a,b,c){return 0>b||this.end<=this.start+b?c:B.b(this.ca,this.start+b,c)};h.K=function(){return Eb(Qc,this.i)};function Wc(a,b,c,d,e){for(;;)if(b instanceof Vc)c=b.start+c,d=b.start+d,b=b.ca;else{var f=P(b);if(0>c||0>d||c>f||d>f)throw Error("Index out of bounds");return new Vc(a,b,c,d,e)}}
var Uc=function(){function a(a,b,c){return Wc(null,a,b,c,null)}function b(a,b){return c.b(a,b,P(a))}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}();function Oc(a){return new Ac({},A(a.d))}
function Pc(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Lb(a,0,b,0,a.length);return b}var Yc=function Xc(b,c,d,e){d=b.root.n===d.n?d:new Ac(b.root.n,A(d.d));var f=b.e-1>>>c&31;if(5===c)b=e;else{var g=d.d[f];b=null!=g?Xc(b,c-5,g,e):Dc(b.root.n,c-5,e)}d.d[f]=b;return d};function Nc(a,b,c,d){this.e=a;this.shift=b;this.root=c;this.D=d;this.g=275;this.o=88}h=Nc.prototype;
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return this.L(null,a)};h.a=function(a,b){return this.M(null,a,b)};h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){return"number"===typeof b?B.b(this,b,c):c};
h.G=function(a,b){if(this.root.n)return Jc(this,b)[b&31];throw Error("nth after persistent!");};h.Y=function(a,b,c){return 0<=b&&b<this.e?B.a(this,b):c};h.J=function(){if(this.root.n)return this.e;throw Error("count after persistent!");};
h.bb=function(a,b,c){var d=this;if(d.root.n){if(0<=b&&b<d.e)return Cc(this)<=b?d.D[b&31]=c:(a=function(){return function f(a,k){var l=d.root.n===k.n?k:new Ac(d.root.n,A(k.d));if(0===a)l.d[b&31]=c;else{var m=b>>>a&31,q=f(a-5,l.d[m]);l.d[m]=q}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.e)return ab(this,c);if(w)throw Error([z("Index "),z(b),z(" out of bounds for TransientVector of length"),z(d.e)].join(""));return null}throw Error("assoc! after persistent!");};
h.ua=function(a,b,c){if("number"===typeof b)return db(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
h.Ba=function(a,b){if(this.root.n){if(32>this.e-Cc(this))this.D[this.e&31]=b;else{var c=new Ac(this.root.n,this.D),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.D=d;if(this.e>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Dc(this.root.n,this.shift,c);this.root=new Ac(this.root.n,d);this.shift=e}else this.root=Yc(this,this.shift,this.root,c)}this.e+=1;return this}throw Error("conj! after persistent!");};h.Ca=function(){if(this.root.n){this.root.n=null;var a=this.e-Cc(this),b=Array(a);Lb(this.D,0,b,0,a);return new U(null,this.e,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function Zc(){this.o=0;this.g=2097152}Zc.prototype.u=function(){return!1};var $c=new Zc;
function ad(a,b){return Nb((null==b?0:b?b.g&1024||b.Ab||(b.g?0:u(Da,b)):u(Da,b))?P(a)===P(b)?tc(vc,wc.a(function(a){return G.a(R.b(b,J(a),$c),J(M(a)))},a)):null:null)}
function bd(a,b){var c=a.d;if(b instanceof T)a:{for(var d=c.length,e=b.ha,f=0;;){if(d<=f){c=-1;break a}var g=c[f];if(g instanceof T&&e===g.ha){c=f;break a}if(w)f+=2;else{c=null;break a}}c=void 0}else if("string"==typeof b||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof nb)a:{d=c.length;e=b.ia;for(f=0;;){if(d<=f){c=-1;break a}g=c[f];if(g instanceof nb&&e===g.ia){c=f;break a}if(w)f+=2;else{c=null;
break a}}c=void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else if(w)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(G.a(b,c[e])){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function cd(a,b,c){this.d=a;this.k=b;this.la=c;this.o=0;this.g=32374990}h=cd.prototype;h.v=function(){return ub(this)};h.da=function(){return this.k<this.d.length-2?new cd(this.d,this.k+2,this.la):null};
h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return this};h.J=function(){return(this.d.length-this.k)/2};h.R=function(){return new U(null,2,5,X,[this.d[this.k],this.d[this.k+1]],null)};h.T=function(){return this.k<this.d.length-2?new cd(this.d,this.k+2,this.la):L};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new cd(this.d,this.k,b)};h.A=function(){return this.la};
h.K=function(){return Eb(L,this.la)};function r(a,b,c,d){this.i=a;this.e=b;this.d=c;this.l=d;this.o=8196;this.g=16123663}h=r.prototype;h.sa=function(){return new dd({},this.d.length,A(this.d))};h.v=function(){var a=this.l;return null!=a?a:this.l=a=Ub(this)};h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){a=bd(this,b);return-1===a?c:this.d[a+1]};
h.ra=function(a,b,c){a=bd(this,b);if(-1===a){if(this.e<ed){a=this.d;for(var d=a.length,e=Array(d+2),f=0;;)if(f<d)e[f]=a[f],f+=1;else break;e[d]=b;e[d+1]=c;return new r(this.i,this.e+1,e,null)}a=Pa;d=Ca;e=fd;null!=e?e&&(e.o&4||e.yb)?(e=qa.b(ab,$a(e),this),e=bb(e)):e=qa.b(xa,e,this):e=qa.b(xb,L,this);return a(d(e,b,c),this.i)}return c===this.d[a+1]?this:w?(b=A(this.d),b[a+1]=c,new r(this.i,this.e,b,null)):null};
h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return this.L(null,a)};h.a=function(a,b){return this.M(null,a,b)};h.F=function(a,b){return Ib(b)?Ca(this,B.a(b,0),B.a(b,1)):qa.b(xa,this,b)};h.toString=function(){return jb(this)};
h.B=function(){return 0<=this.d.length-2?new cd(this.d,0,null):null};h.J=function(){return this.e};h.u=function(a,b){return ad(this,b)};h.C=function(a,b){return new r(b,this.e,this.d,this.l)};h.A=function(){return this.i};h.K=function(){return Pa(gd,this.i)};
h.Ua=function(a,b){if(0<=bd(this,b)){var c=this.d.length,d=c-2;if(0===d)return wa(this);for(var d=Array(d),e=0,f=0;;){if(e>=c)return new r(this.i,this.e-1,d,null);if(G.a(b,this.d[e]))e+=2;else if(w)d[f]=this.d[e],d[f+1]=this.d[e+1],f+=2,e+=2;else return null}}else return this};var gd=new r(null,0,[],null),ed=8;function dd(a,b,c){this.na=a;this.fa=b;this.d=c;this.o=56;this.g=258}h=dd.prototype;
h.ua=function(a,b,c){if(s(this.na)){a=bd(this,b);if(-1===a)return this.fa+2<=2*ed?(this.fa+=2,this.d.push(b),this.d.push(c),this):rc.b(hd.a?hd.a(this.fa,this.d):hd.call(null,this.fa,this.d),b,c);c!==this.d[a+1]&&(this.d[a+1]=c);return this}throw Error("assoc! after persistent!");};
h.Ba=function(a,b){if(s(this.na)){if(b?b.g&2048||b.lb||(b.g?0:u(Fa,b)):u(Fa,b))return cb(this,Vb.c?Vb.c(b):Vb.call(null,b),Wb.c?Wb.c(b):Wb.call(null,b));for(var c=I(b),d=this;;){var e=J(c);if(s(e))c=M(c),d=cb(d,Vb.c?Vb.c(e):Vb.call(null,e),Wb.c?Wb.c(e):Wb.call(null,e));else return d}}else throw Error("conj! after persistent!");};h.Ca=function(){if(s(this.na))return this.na=!1,new r(null,Rb((this.fa-this.fa%2)/2),this.d,null);throw Error("persistent! called twice");};
h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){if(s(this.na))return a=bd(this,b),-1===a?c:this.d[a+1];throw Error("lookup after persistent!");};h.J=function(){if(s(this.na))return Rb((this.fa-this.fa%2)/2);throw Error("count after persistent!");};function hd(a,b){for(var c=$a(fd),d=0;;)if(d<a)c=rc.b(c,b[d],b[d+1]),d+=2;else return c}function id(){this.V=!1}function jd(a,b){return a===b?!0:a===b||a instanceof T&&b instanceof T&&a.ha===b.ha?!0:w?G.a(a,b):null}
var kd=function(){function a(a,b,c,g,k){a=A(a);a[b]=c;a[g]=k;return a}function b(a,b,c){a=A(a);a[b]=c;return a}var c=null,c=function(c,e,f,g,k){switch(arguments.length){case 3:return b.call(this,c,e,f);case 5:return a.call(this,c,e,f,g,k)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.w=a;return c}();function ld(a,b){var c=Array(a.length-2);Lb(a,0,c,0,2*b);Lb(a,2*(b+1),c,2*b,c.length-2*b);return c}
var md=function(){function a(a,b,c,g,k,l){a=a.oa(b);a.d[c]=g;a.d[k]=l;return a}function b(a,b,c,g){a=a.oa(b);a.d[c]=g;return a}var c=null,c=function(c,e,f,g,k,l){switch(arguments.length){case 4:return b.call(this,c,e,f,g);case 6:return a.call(this,c,e,f,g,k,l)}throw Error("Invalid arity: "+arguments.length);};c.j=b;c.X=a;return c}();function nd(a,b,c){this.n=a;this.p=b;this.d=c}h=nd.prototype;
h.$=function(a,b,c,d,e,f){var g=1<<(c>>>b&31),k=Sb(this.p&g-1);if(0===(this.p&g)){var l=Sb(this.p);if(2*l<this.d.length){a=this.oa(a);b=a.d;f.V=!0;a:for(c=2*(l-k),f=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[f];l-=1;c-=1;f-=1}b[2*k]=d;b[2*k+1]=e;a.p|=g;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=od.$(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0!==
(this.p>>>d&1)&&(k[d]=null!=this.d[e]?od.$(a,b+5,H(this.d[e]),this.d[e],this.d[e+1],f):this.d[e+1],e+=2),d+=1;else break;return new pd(a,l+1,k)}return w?(b=Array(2*(l+4)),Lb(this.d,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Lb(this.d,2*k,b,2*(k+1),2*(l-k)),f.V=!0,a=this.oa(a),a.d=b,a.p|=g,a):null}l=this.d[2*k];g=this.d[2*k+1];return null==l?(l=g.$(a,b+5,c,d,e,f),l===g?this:md.j(this,a,2*k+1,l)):jd(d,l)?e===g?this:md.j(this,a,2*k+1,e):w?(f.V=!0,md.X(this,a,2*k,null,2*k+1,qd.ma?qd.ma(a,b+5,l,g,c,d,e):qd.call(null,
a,b+5,l,g,c,d,e))):null};h.wa=function(){return rd.c?rd.c(this.d):rd.call(null,this.d)};h.oa=function(a){if(a===this.n)return this;var b=Sb(this.p),c=Array(0>b?4:2*(b+1));Lb(this.d,0,c,0,2*b);return new nd(a,this.p,c)};
h.xa=function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.p&d))return this;var e=Sb(this.p&d-1),f=this.d[2*e],g=this.d[2*e+1];return null==f?(a=g.xa(a+5,b,c),a===g?this:null!=a?new nd(null,this.p,kd.b(this.d,2*e+1,a)):this.p===d?null:w?new nd(null,this.p^d,ld(this.d,e)):null):jd(c,f)?new nd(null,this.p^d,ld(this.d,e)):w?this:null};
h.Z=function(a,b,c,d,e){var f=1<<(b>>>a&31),g=Sb(this.p&f-1);if(0===(this.p&f)){var k=Sb(this.p);if(16<=k){g=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];g[b>>>a&31]=od.Z(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.p>>>c&1)&&(g[c]=null!=this.d[d]?od.Z(a+5,H(this.d[d]),this.d[d],this.d[d+1],e):this.d[d+1],d+=2),c+=1;else break;return new pd(null,k+1,g)}a=Array(2*(k+1));Lb(this.d,0,a,
0,2*g);a[2*g]=c;a[2*g+1]=d;Lb(this.d,2*g,a,2*(g+1),2*(k-g));e.V=!0;return new nd(null,this.p|f,a)}k=this.d[2*g];f=this.d[2*g+1];return null==k?(k=f.Z(a+5,b,c,d,e),k===f?this:new nd(null,this.p,kd.b(this.d,2*g+1,k))):jd(c,k)?d===f?this:new nd(null,this.p,kd.b(this.d,2*g+1,d)):w?(e.V=!0,new nd(null,this.p,kd.w(this.d,2*g,null,2*g+1,qd.X?qd.X(a+5,k,f,b,c,d):qd.call(null,a+5,k,f,b,c,d)))):null};
h.ka=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.p&e))return d;var f=Sb(this.p&e-1),e=this.d[2*f],f=this.d[2*f+1];return null==e?f.ka(a+5,b,c,d):jd(c,e)?f:w?d:null};var od=new nd(null,0,[]);function pd(a,b,c){this.n=a;this.e=b;this.d=c}h=pd.prototype;h.$=function(a,b,c,d,e,f){var g=c>>>b&31,k=this.d[g];if(null==k)return a=md.j(this,a,g,od.$(a,b+5,c,d,e,f)),a.e+=1,a;b=k.$(a,b+5,c,d,e,f);return b===k?this:md.j(this,a,g,b)};h.wa=function(){return sd.c?sd.c(this.d):sd.call(null,this.d)};
h.oa=function(a){return a===this.n?this:new pd(a,this.e,A(this.d))};h.xa=function(a,b,c){var d=b>>>a&31,e=this.d[d];if(null!=e){a=e.xa(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.e)a:{e=this.d;a=2*(this.e-1);b=Array(a);c=0;for(var f=1,g=0;;)if(c<a)c!==d&&null!=e[c]&&(b[f]=e[c],f+=2,g|=1<<c),c+=1;else{d=new nd(null,g,b);break a}d=void 0}else d=new pd(null,this.e-1,kd.b(this.d,d,a));else d=w?new pd(null,this.e,kd.b(this.d,d,a)):null;return d}return this};
h.Z=function(a,b,c,d,e){var f=b>>>a&31,g=this.d[f];if(null==g)return new pd(null,this.e+1,kd.b(this.d,f,od.Z(a+5,b,c,d,e)));a=g.Z(a+5,b,c,d,e);return a===g?this:new pd(null,this.e,kd.b(this.d,f,a))};h.ka=function(a,b,c,d){var e=this.d[b>>>a&31];return null!=e?e.ka(a+5,b,c,d):d};function td(a,b,c){b*=2;for(var d=0;;)if(d<b){if(jd(c,a[d]))return d;d+=2}else return-1}function ud(a,b,c,d){this.n=a;this.ea=b;this.e=c;this.d=d}h=ud.prototype;
h.$=function(a,b,c,d,e,f){if(c===this.ea){b=td(this.d,this.e,d);if(-1===b){if(this.d.length>2*this.e)return a=md.X(this,a,2*this.e,d,2*this.e+1,e),f.V=!0,a.e+=1,a;c=this.d.length;b=Array(c+2);Lb(this.d,0,b,0,c);b[c]=d;b[c+1]=e;f.V=!0;f=this.e+1;a===this.n?(this.d=b,this.e=f,a=this):a=new ud(this.n,this.ea,f,b);return a}return this.d[b+1]===e?this:md.j(this,a,b+1,e)}return(new nd(a,1<<(this.ea>>>b&31),[null,this,null,null])).$(a,b,c,d,e,f)};h.wa=function(){return rd.c?rd.c(this.d):rd.call(null,this.d)};
h.oa=function(a){if(a===this.n)return this;var b=Array(2*(this.e+1));Lb(this.d,0,b,0,2*this.e);return new ud(a,this.ea,this.e,b)};h.xa=function(a,b,c){a=td(this.d,this.e,c);return-1===a?this:1===this.e?null:w?new ud(null,this.ea,this.e-1,ld(this.d,Rb((a-a%2)/2))):null};
h.Z=function(a,b,c,d,e){return b===this.ea?(a=td(this.d,this.e,c),-1===a?(a=2*this.e,b=Array(a+2),Lb(this.d,0,b,0,a),b[a]=c,b[a+1]=d,e.V=!0,new ud(null,this.ea,this.e+1,b)):G.a(this.d[a],d)?this:new ud(null,this.ea,this.e,kd.b(this.d,a+1,d))):(new nd(null,1<<(this.ea>>>a&31),[null,this])).Z(a,b,c,d,e)};h.ka=function(a,b,c,d){a=td(this.d,this.e,c);return 0>a?d:jd(c,this.d[a])?this.d[a+1]:w?d:null};
var qd=function(){function a(a,b,c,g,k,l,m){var q=H(c);if(q===k)return new ud(null,q,2,[c,g,l,m]);var p=new id;return od.$(a,b,q,c,g,p).$(a,b,k,l,m,p)}function b(a,b,c,g,k,l){var m=H(b);if(m===g)return new ud(null,m,2,[b,c,k,l]);var q=new id;return od.Z(a,m,b,c,q).Z(a,g,k,l,q)}var c=null,c=function(c,e,f,g,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,f,g,k,l);case 7:return a.call(this,c,e,f,g,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.X=b;c.ma=a;return c}();
function vd(a,b,c,d,e){this.i=a;this.aa=b;this.k=c;this.q=d;this.l=e;this.o=0;this.g=32374860}h=vd.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return this};h.R=function(){return null==this.q?new U(null,2,5,X,[this.aa[this.k],this.aa[this.k+1]],null):J(this.q)};
h.T=function(){return null==this.q?rd.b?rd.b(this.aa,this.k+2,null):rd.call(null,this.aa,this.k+2,null):rd.b?rd.b(this.aa,this.k,M(this.q)):rd.call(null,this.aa,this.k,M(this.q))};h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new vd(b,this.aa,this.k,this.q,this.l)};h.A=function(){return this.i};h.K=function(){return Eb(L,this.i)};
var rd=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new vd(null,a,b,null,null);var g=a[b+1];if(s(g)&&(g=g.wa(),s(g)))return new vd(null,a,b+2,g,null);b+=2}else return null;else return new vd(null,a,b,c,null)}function b(a){return c.b(a,0,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.b=a;return c}();
function wd(a,b,c,d,e){this.i=a;this.aa=b;this.k=c;this.q=d;this.l=e;this.o=0;this.g=32374860}h=wd.prototype;h.v=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};h.F=function(a,b){return O(b,this)};h.toString=function(){return jb(this)};h.P=function(a,b){return Qb.a(b,this)};h.Q=function(a,b,c){return Qb.b(b,c,this)};h.B=function(){return this};h.R=function(){return J(this.q)};h.T=function(){return sd.j?sd.j(null,this.aa,this.k,M(this.q)):sd.call(null,null,this.aa,this.k,M(this.q))};
h.u=function(a,b){return vb(this,b)};h.C=function(a,b){return new wd(b,this.aa,this.k,this.q,this.l)};h.A=function(){return this.i};h.K=function(){return Eb(L,this.i)};
var sd=function(){function a(a,b,c,g){if(null==g)for(g=b.length;;)if(c<g){var k=b[c];if(s(k)&&(k=k.wa(),s(k)))return new wd(a,b,c+1,k,null);c+=1}else return null;else return new wd(a,b,c,g,null)}function b(a){return c.j(null,a,0,null)}var c=null,c=function(c,e,f,g){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,f,g)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.j=a;return c}();
function xd(a,b,c,d,e,f){this.i=a;this.e=b;this.root=c;this.O=d;this.S=e;this.l=f;this.o=8196;this.g=16123663}h=xd.prototype;h.sa=function(){return new yd({},this.root,this.e,this.O,this.S)};h.v=function(){var a=this.l;return null!=a?a:this.l=a=Ub(this)};h.L=function(a,b){return Ba.b(this,b,null)};h.M=function(a,b,c){return null==b?this.O?this.S:c:null==this.root?c:w?this.root.ka(0,H(b),b,c):null};
h.ra=function(a,b,c){if(null==b)return this.O&&c===this.S?this:new xd(this.i,this.O?this.e:this.e+1,this.root,!0,c,null);a=new id;b=(null==this.root?od:this.root).Z(0,H(b),b,c,a);return b===this.root?this:new xd(this.i,a.V?this.e+1:this.e,b,this.O,this.S,null)};h.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
h.apply=function(a,b){return this.call.apply(this,[this].concat(A(b)))};h.c=function(a){return this.L(null,a)};h.a=function(a,b){return this.M(null,a,b)};h.F=function(a,b){return Ib(b)?Ca(this,B.a(b,0),B.a(b,1)):qa.b(xa,this,b)};h.toString=function(){return jb(this)};h.B=function(){if(0<this.e){var a=null!=this.root?this.root.wa():null;return this.O?O(new U(null,2,5,X,[null,this.S],null),a):a}return null};h.J=function(){return this.e};h.u=function(a,b){return ad(this,b)};
h.C=function(a,b){return new xd(b,this.e,this.root,this.O,this.S,this.l)};h.A=function(){return this.i};h.K=function(){return Pa(fd,this.i)};h.Ua=function(a,b){if(null==b)return this.O?new xd(this.i,this.e-1,this.root,!1,null,null):this;if(null==this.root)return this;if(w){var c=this.root.xa(0,H(b),b);return c===this.root?this:new xd(this.i,this.e-1,c,this.O,this.S,null)}return null};var fd=new xd(null,0,null,!1,null,0);
function zb(a,b){for(var c=a.length,d=0,e=$a(fd);;)if(d<c)var f=d+1,e=e.ua(null,a[d],b[d]),d=f;else return bb(e)}function yd(a,b,c,d,e){this.n=a;this.root=b;this.count=c;this.O=d;this.S=e;this.o=56;this.g=258}h=yd.prototype;h.ua=function(a,b,c){return zd(this,b,c)};
h.Ba=function(a,b){var c;a:{if(this.n){if(b?b.g&2048||b.lb||(b.g?0:u(Fa,b)):u(Fa,b)){c=zd(this,Vb.c?Vb.c(b):Vb.call(null,b),Wb.c?Wb.c(b):Wb.call(null,b));break a}c=I(b);for(var d=this;;){var e=J(c);if(s(e))c=M(c),d=zd(d,Vb.c?Vb.c(e):Vb.call(null,e),Wb.c?Wb.c(e):Wb.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
h.Ca=function(){var a;if(this.n)this.n=null,a=new xd(null,this.count,this.root,this.O,this.S,null);else throw Error("persistent! called twice");return a};h.L=function(a,b){return null==b?this.O?this.S:null:null==this.root?null:this.root.ka(0,H(b),b)};h.M=function(a,b,c){return null==b?this.O?this.S:c:null==this.root?c:this.root.ka(0,H(b),b,c)};h.J=function(){if(this.n)return this.count;throw Error("count after persistent!");};
function zd(a,b,c){if(a.n){if(null==b)a.S!==c&&(a.S=c),a.O||(a.count+=1,a.O=!0);else{var d=new id;b=(null==a.root?od:a.root).$(a.n,0,H(b),b,c,d);b!==a.root&&(a.root=b);d.V&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var Ad=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=I(a);for(var b=$a(fd);;)if(a){var e=M(M(a)),b=rc.b(b,J(a),J(M(a)));a=e}else return bb(b)}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}();function Vb(a){return Ga(a)}function Wb(a){return Ha(a)}
var Bd=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return s(uc(a))?qa.a(function(a,b){return xb.a(s(a)?a:gd,b)},a):null}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}();function ac(a){if(a&&(a.o&4096||a.nb))return a.name;if("string"===typeof a)return a;throw Error([z("Doesn't support name: "),z(a)].join(""));}
function Cd(a,b,c,d,e,f,g){var k=ga;try{ga=null==ga?null:ga-1;if(null!=ga&&0>ga)return F(a,"#");F(a,c);I(g)&&(b.b?b.b(J(g),a,f):b.call(null,J(g),a,f));for(var l=M(g),m=na.c(f);l&&(null==m||0!==m);){F(a,d);b.b?b.b(J(l),a,f):b.call(null,J(l),a,f);var q=M(l);c=m-1;l=q;m=c}s(na.c(f))&&(F(a,d),b.b?b.b("...",a,f):b.call(null,"...",a,f));return F(a,e)}finally{ga=k}}
var Dd=function(){function a(a,d){var e=null;1<arguments.length&&(e=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=I(b),f=null,g=0,k=0;;)if(k<g){var l=f.G(null,k);F(a,l);k+=1}else if(e=I(e))f=e,Jb(f)?(e=fb(f),g=gb(f),f=e,l=P(e),e=g,g=l):(l=J(f),F(a,l),e=M(f),f=null,g=0),k=0;else return null}a.m=1;a.h=function(a){var d=J(a);a=K(a);return b(d,a)};a.f=b;return a}(),Ed={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function Fd(a){return[z('"'),z(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return Ed[a]})),z('"')].join("")}
var Id=function Gd(b,c,d){if(null==b)return F(c,"nil");if(void 0===b)return F(c,"#\x3cundefined\x3e");if(w){s(function(){var c=R.a(d,la);return s(c)?(c=b?b.g&131072||b.mb?!0:b.g?!1:u(Ma,b):u(Ma,b))?Fb(b):c:c}())&&(F(c,"^"),Gd(Fb(b),c,d),F(c," "));if(null==b)return F(c,"nil");if(b.Xa)return b.fb(b,c,d);if(b&&(b.g&2147483648||b.N))return b.t(null,c,d);if(oa(b)===Boolean||"number"===typeof b)return F(c,""+z(b));if(null!=b&&b.constructor===Object)return F(c,"#js "),Hd.j?Hd.j(wc.a(function(c){return new U(null,
2,5,X,[bc.c(c),b[c]],null)},Kb(b)),Gd,c,d):Hd.call(null,wc.a(function(c){return new U(null,2,5,X,[bc.c(c),b[c]],null)},Kb(b)),Gd,c,d);if(b instanceof Array)return Cd(c,Gd,"#js ["," ","]",d,b);if("string"==typeof b)return s(ka.c(d))?F(c,Fd(b)):F(c,b);if(Bb(b))return Dd.f(c,N(["#\x3c",""+z(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+z(b);;)if(P(d)<c)d=[z("0"),z(d)].join("");else return d};return Dd.f(c,N(['#inst "',""+z(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),
2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?Dd.f(c,N(['#"',b.source,'"'],0)):(b?b.g&2147483648||b.N||(b.g?0:u(Xa,b)):u(Xa,b))?Ya(b,c,d):w?Dd.f(c,N(["#\x3c",""+z(b),"\x3e"],0)):null}return null};
function Jd(a,b){var c;(c=null==a)||(c=I(a),c=s(c)?!1:!0);if(c)c="";else{c=z;var d=new da;a:{var e=new ib(d);Id(J(a),e,b);for(var f=I(M(a)),g=null,k=0,l=0;;)if(l<k){var m=g.G(null,l);F(e," ");Id(m,e,b);l+=1}else if(f=I(f))g=f,Jb(g)?(f=fb(g),k=gb(g),g=f,m=P(f),f=k,k=m):(m=J(g),F(e," "),Id(m,e,b),f=M(g),g=null,k=0),l=0;else break a}c=""+c(d)}return c}
var Kd=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return Jd(a,ia())}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}(),Ld=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=S.b(ia(),ka,!1);a=Jd(a,b);fa.c?fa.c(a):fa.call(null,a);return null}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}();
function Hd(a,b,c,d){return Cd(c,function(a,c,d){b.b?b.b(Ga(a),c,d):b.call(null,Ga(a),c,d);F(c," ");return b.b?b.b(Ha(a),c,d):b.call(null,Ha(a),c,d)},"{",", ","}",d,I(a))}pb.prototype.N=!0;pb.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};Vc.prototype.N=!0;Vc.prototype.t=function(a,b,c){return Cd(b,Id,"["," ","]",c,this)};hc.prototype.N=!0;hc.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};r.prototype.N=!0;r.prototype.t=function(a,b,c){return Hd(this,Id,b,c)};
cc.prototype.N=!0;cc.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};vd.prototype.N=!0;vd.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};Tc.prototype.N=!0;Tc.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};xd.prototype.N=!0;xd.prototype.t=function(a,b,c){return Hd(this,Id,b,c)};U.prototype.N=!0;U.prototype.t=function(a,b,c){return Cd(b,Id,"["," ","]",c,this)};Xb.prototype.N=!0;Xb.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};
cd.prototype.N=!0;cd.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};Yb.prototype.N=!0;Yb.prototype.t=function(a,b){return F(b,"()")};$b.prototype.N=!0;$b.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};wd.prototype.N=!0;wd.prototype.t=function(a,b,c){return Cd(b,Id,"("," ",")",c,this)};U.prototype.za=!0;U.prototype.Aa=function(a,b){return Ob.a(this,b)};Vc.prototype.za=!0;Vc.prototype.Aa=function(a,b){return Ob.a(this,b)};T.prototype.za=!0;
T.prototype.Aa=function(a,b){return kb(this,b)};nb.prototype.za=!0;nb.prototype.Aa=function(a,b){return kb(this,b)};function Md(a,b){if(a?a.pb:a)return a.pb(a,b);var c;c=Md[n(null==a?null:a)];if(!c&&(c=Md._,!c))throw x("IReset.-reset!",a);return c.call(null,a,b)}function Nd(a,b,c,d){this.state=a;this.i=b;this.vb=c;this.gb=d;this.g=2153938944;this.o=16386}h=Nd.prototype;h.v=function(){return this[aa]||(this[aa]=++ba)};
h.cb=function(a,b,c){a=I(this.gb);for(var d=null,e=0,f=0;;)if(f<e){var g=d.G(null,f),k=Q.b(g,0,null),g=Q.b(g,1,null);g.j?g.j(k,this,b,c):g.call(null,k,this,b,c);f+=1}else if(a=I(a))Jb(a)?(d=fb(a),a=gb(a),k=d,e=P(d),d=k):(d=J(a),k=Q.b(d,0,null),g=Q.b(d,1,null),g.j?g.j(k,this,b,c):g.call(null,k,this,b,c),a=M(a),d=null,e=0),f=0;else return null};h.t=function(a,b,c){F(b,"#\x3cAtom: ");Id(this.state,b,c);return F(b,"\x3e")};h.A=function(){return this.i};h.jb=function(){return this.state};
h.u=function(a,b){return this===b};
var Pd=function(){function a(a){return new Nd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=Mb(c)?Db.a(Ad,c):c,e=R.a(d,Od),d=R.a(d,la);return new Nd(a,d,e,null)}a.m=1;a.h=function(a){var c=J(a);a=K(a);return b(c,a)};a.f=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.f(b,N(arguments,1))}throw Error("Invalid arity: "+
arguments.length);};b.m=1;b.h=c.h;b.c=a;b.f=c.f;return b}();function Qd(a,b){if(a instanceof Nd){var c=a.vb;if(null!=c&&!s(c.c?c.c(b):c.call(null,b)))throw Error([z("Assert failed: "),z("Validator rejected reference state"),z("\n"),z(Kd.f(N([Zb(new nb(null,"validate","validate",1233162959,null),new nb(null,"new-value","new-value",972165309,null))],0)))].join(""));c=a.state;a.state=b;null!=a.gb&&Za(a,c,b);return b}return Md(a,b)};var ma=new T(null,"dup","dup"),Rd=new T(null,"ball","ball"),Wd=new T(null,"direction","direction"),Xd=new T(null,"finished","finished"),Yd=new T(null,"timestamp","timestamp"),mb=new T(null,"default","default"),Zd=new T(null,"position","position"),$d=new T(null,"width","width"),ae=new T(null,"speed","speed"),be=new T(null,"velocity","velocity"),Y=new T(null,"y","y"),$=new T(null,"x","x"),ce=new T(null,"has-bounced?","has-bounced?"),de=new T(null,"wall-hits","wall-hits"),ja=new T(null,"flush-on-newline",
"flush-on-newline"),ee=new T(null,"length","length"),fe=new T(null,"src","src"),ge=new T(null,"pos","pos"),he=new T(null,"phone","phone"),ie=new T(null,"walls","walls"),na=new T(null,"print-length","print-length"),w=new T(null,"else","else"),ka=new T(null,"readably","readably"),Od=new T(null,"validator","validator"),la=new T(null,"meta","meta"),je=new T(null,"coord","coord"),ke=new T(null,"height","height");var le=Pd.c(gd);
function me(a,b,c,d,e,f,g){var k;k=new U(null,2,5,X,[b,g],null);k=G.a(new U(null,2,5,X,[Y,-1],null),k)?"rgba(123,0,123,":G.a(new U(null,2,5,X,[$,-1],null),k)?"rgba(0,123,176,":G.a(new U(null,2,5,X,[$,1],null),k)?"rgba(0,255,0,":w?"rgba(255,0,0,":null;f*=g;e*=g;a=G.a(b,$)?a.createLinearGradient(c,d,c+e,d/2):a.createLinearGradient(c,d,c/2,d+f);a.addColorStop(0,[z(k),z("0.3)")].join(""));a.addColorStop(0.1,[z(k),z("0.3)")].join(""));a.addColorStop(0.8,[z(k),z("0)")].join(""));return a}
function ne(a,b){var c=Mb(a)?Db.a(Ad,a):a,d=R.a(c,ae),e=R.a(c,Wd),f=R.a(c,ee),g=R.a(c,ge),k=R.a(c,je),d=G.a(k,$)?new U(null,2,5,X,[f,25*d],null):new U(null,2,5,X,[25*d,f],null),c=Q.b(d,0,null),d=Q.b(d,1,null),l=function(){if(G.a(Y,k))return new U(null,2,5,X,[0,g],null);if(G.a($,k))return new U(null,2,5,X,[g,0],null);if(w)throw Error([z("No matching clause: "),z(k)].join(""));return null}(),f=Q.b(l,0,null),l=Q.b(l,1,null);b.fillStyle=me(b,k,f,l,d,c,e);b.fillRect(G.a(k,$)&&G.a(e,-1)?f-d:f,G.a(k,Y)&&
G.a(e,-1)?l-c:l,d,c)}
function oe(a,b){return G.a(La(le),b)?null:requestAnimationFrame(function(){Qd(le,b);var c=a.getContext("2d"),d=b.c?b.c(Rd):b.call(null,Rd),e=d.c?d.c($d):d.call(null,$d);d.c?d.c(ke):d.call(null,ke);var f=$.c(Zd.c(d)),d=Y.c(Zd.c(d));a.getContext("2d").clearRect(0,0,a.width,a.height);a:for(var g=I(b.c?b.c(de):b.call(null,de)),k=null,l=0,m=0;;)if(m<l){var q=k.G(null,m),p=Q.b(q,0,null),q=Q.b(q,1,null);-900<q-(b.c?b.c(Yd):b.call(null,Yd))&&ne(p,c);m+=1}else if(g=I(g))Jb(g)?(k=fb(g),g=gb(g),p=k,l=P(k),
k=p):(k=J(g),p=Q.b(k,0,null),q=Q.b(k,1,null),-900<q-(b.c?b.c(Yd):b.call(null,Yd))&&ne(p,c),g=M(g),k=null,l=0),m=0;else break a;c.fillStyle="rgb(123,0,123)";return c.fillRect(f-e/2,d-e/2,e,e)})};var pe=function(){function a(a,d){var e=null;1<arguments.length&&(e=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=document.createElement(a),f=I(J(b)),g=null,k=0,l=0;;)if(l<k){var m=g.G(null,l),q=Q.b(m,0,null),m=Q.b(m,1,null);e.setAttribute(ac(q),m);l+=1}else if(f=I(f))Jb(f)?(k=fb(f),f=gb(f),g=k,k=P(k)):(k=J(f),g=Q.b(k,0,null),k=Q.b(k,1,null),e.setAttribute(ac(g),k),f=M(f),g=null,k=0),l=0;else break;return e}a.m=1;a.h=function(a){var d=J(a);a=K(a);
return b(d,a)};a.f=b;return a}();function qe(a){var b=new U(null,2,5,X,[0,1],null),c=Q.b(b,0,null),b=Q.b(b,1,null);return Math.min(Math.max(a,c),b)}function re(a){return function(a){return a*a}.call(null,qe(a/1.2))}
function se(a){a=ce.c(Rd.c(a));if(s(a)){var b;b=new U(null,2,5,X,[je.c(a),Wd.c(a)],null);b=G.a(new U(null,2,5,X,[Y,-1],null),b)?"boink.wav":G.a(new U(null,2,5,X,[$,-1],null),b)?"boink.wav":G.a(new U(null,2,5,X,[Y,1],null),b)?"boink.wav":G.a(new U(null,2,5,X,[$,1],null),b)?"boink.wav":w?"squish.mp3":null;a=re(ae.c(a));b=pe.f("audio",N([new r(null,1,[fe,b],null)],0));b.volume=a;b.play()}};var te;"undefined"!==typeof MessageChannel&&new MessageChannel;function ue(a,b,c){this.key=a;this.V=b;this.forward=c;this.o=0;this.g=2155872256}ue.prototype.t=function(a,b,c){return Cd(b,Id,"["," ","]",c,this)};ue.prototype.B=function(){return xa(xa(L,this.V),this.key)};
(function(){function a(a,b,c){c=Array(c+1);for(var g=0;;)if(g<c.length)c[g]=null,g+=1;else break;return new ue(a,b,c)}function b(a){return c.b(null,null,a)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.b=a;return c})().c(0);(function ve(b){"undefined"===typeof te&&(te=function(b,d,e){this.qb=b;this.rb=d;this.tb=e;this.o=0;this.g=393216},te.Xa=!0,te.Wa="cljs.core.async/t17967",te.fb=function(b,d){return F(d,"cljs.core.async/t17967")},te.prototype.A=function(){return this.tb},te.prototype.C=function(b,d){return new te(this.qb,this.rb,d)});return new te(b,ve,null)})(function(){return null});var fa=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return console.log.apply(console,ra.c?ra.c(a):ra.call(null,a))}a.m=0;a.h=function(a){a=I(a);return b(a)};a.f=b;return a}(),we=Pd.c({gamma:0,beta:0,alpha:0});s(DeviceOrientationEvent)?window.addEventListener("deviceorientation",function(a){return Qd(we,a)}):navigator.accelerometer.watchAcceleration(function(a){return Qd(we,a)},function(a){return console.log(a)});
function xe(){s(DeviceOrientationEvent)||navigator.accelerometer.watchAcceleration(function(){return null},function(){return null},{frequency:10})}function ye(a,b,c){var d=Q.b(b,0,null),e=Q.b(b,1,null);return zc.b(a,new U(null,1,5,X,[Zd],null),function(a,b,d){return function(a){return zb.a?zb.a([$,Y],[$.c(a)+c*b,Y.c(a)+c*d]):zb.call(null,[$,Y],[$.c(a)+c*b,Y.c(a)+c*d])}}(b,d,e))}
function ze(a,b){var c=-$.c(ae.c(a)),d=-Y.c(ae.c(a)),e=$.c(be.c(a)),f=Y.c(be.c(a)),g=e+b*c,k=f+b*d;return ye(zc.b(a,new U(null,1,5,X,[be],null),function(a,b,c,d,e,f){return function(){return zb.a?zb.a([$,Y],[e,f]):zb.call(null,[$,Y],[e,f])}}(c,d,e,f,g,k)),new U(null,2,5,X,[(e+g)/2,(f+k)/2],null),b)}function Ae(a,b){var c=Q.b(b,0,null),d=Q.b(b,1,null);return c<a&&a<d||c>a&&a>d}
function Be(a,b,c){return qa.b(function(a,b){var c=Q.b(b,0,null),g=Mb(c)?Db.a(Ad,c):c,k=R.a(g,ge),l=R.a(g,je),m=Q.b(b,1,null);return s(m)?Bd.f(N([zc.b(zc.b(a,new U(null,2,5,X,[Zd,l],null),function(a,b,c,d,e,f,g){return function(a){return a+g}}(b,c,g,g,k,l,m)),new U(null,2,5,X,[be,l],null),function(){return function(a){return-(0.62*a)}}(b,c,g,g,k,l,m)),new r(null,1,[ce,S.b(g,Xd,Math.abs(l.c?l.c(be.c(a)):l.call(null,be.c(a))))],null)],0)):a},a,Db.a(oc,function(){return function e(c){return new cc(null,
function(){for(;;){var g=I(c);if(g){var k=g;if(Jb(k)){var l=fb(k),m=P(l),q=new ec(Array(m),0);return function(){for(var c=0;;)if(c<m){var e=B.a(l,c),f=Mb(e)?Db.a(Ad,e):e,p=f,t=R.a(f,ge),v=R.a(f,je);jc(q,function(){var y=v.c?v.c(Zd.c(b)):v.call(null,Zd.c(b)),C=v.c?v.c(Zd.c(a)):v.call(null,Zd.c(a)),Sd=b.c?b.c(G.a(v,$)?$d:ke):b.call(null,G.a(v,$)?$d:ke),Vd=function(a,b,c,e,f,g,k,l,m,p,q,t,v,y){return function Ud(C){return new cc(null,function(a,b,c,e,f,g,k,l){return function(){for(;;){var a=I(C);if(a){if(Jb(a)){var b=
fb(a),c=P(b),e=new ec(Array(c),0);a:{for(var f=0;;)if(f<c){var g=B.a(b,f),m=Q.b(g,0,null),g=Q.b(g,1,null),m=new U(null,2,5,X,[k,Ae(l,new U(null,2,5,X,[m,g],null))?2*(l-g):null],null);e.add(m);f+=1}else{b=!0;break a}b=void 0}return b?ic(e.I(),Ud(gb(a))):ic(e.I(),null)}b=J(a);e=Q.b(b,0,null);b=Q.b(b,1,null);return O(new U(null,2,5,X,[k,Ae(l,new U(null,2,5,X,[e,b],null))?2*(l-b):null],null),Ud(K(a)))}return null}}}(a,b,c,e,f,g,k,l,m,p,q,t,v,y),null,null)}}(c,y,C,Sd,e,f,p,t,v,l,m,q,k,g);return Vd(Db.b(wc,
Sc,wc.a(function(a,b,c,e,f){return function(a){return new U(null,2,5,X,[a-f/2,a+f/2],null)}}(c,Vd,y,C,Sd,e,f,p,t,v,l,m,q,k,g),new U(null,2,5,X,[y,C],null))))}());c+=1}else return!0}()?ic(q.I(),e(gb(k))):ic(q.I(),null)}var p=J(k),t=Mb(p)?Db.a(Ad,p):p,C=t,y=R.a(t,ge),v=R.a(t,je);return O(function(){var c=v.c?v.c(Zd.c(b)):v.call(null,Zd.c(b)),e=v.c?v.c(Zd.c(a)):v.call(null,Zd.c(a)),f=b.c?b.c(G.a(v,$)?$d:ke):b.call(null,G.a(v,$)?$d:ke),l=function(a,b,c,e,f,g,k,l,m,p){return function Td(q){return new cc(null,
function(a,b,c,e,f,g,k){return function(){for(;;){var a=I(q);if(a){if(Jb(a)){var b=fb(a),c=P(b),e=new ec(Array(c),0);a:{for(var f=0;;)if(f<c){var l=B.a(b,f),m=Q.b(l,0,null),l=Q.b(l,1,null),m=new U(null,2,5,X,[g,Ae(k,new U(null,2,5,X,[m,l],null))?2*(k-l):null],null);e.add(m);f+=1}else{b=!0;break a}b=void 0}return b?ic(e.I(),Td(gb(a))):ic(e.I(),null)}b=J(a);e=Q.b(b,0,null);b=Q.b(b,1,null);return O(new U(null,2,5,X,[g,Ae(k,new U(null,2,5,X,[e,b],null))?2*(k-b):null],null),Td(K(a)))}return null}}}(a,
b,c,e,f,g,k,l,m,p),null,null)}}(c,e,f,p,t,C,y,v,k,g);return l(Db.b(wc,Sc,wc.a(function(a,b,c,e){return function(a){return new U(null,2,5,X,[a-e/2,a+e/2],null)}}(l,c,e,f,p,t,C,y,v,k,g),new U(null,2,5,X,[c,e],null))))}(),e(K(k)))}return null}},null,null)}(c)}()))}function Ce(a){return Ab.a(a,ce)}
function De(a,b){var c;c=1.2E-5*he.c(a).gamma;var d;d=1.2E-5*he.c(a).beta;return S.b(a,Rd,Be(ze(yc(Ce(a.c?a.c(Rd):a.call(null,Rd)),new U(null,1,5,X,[ae],null),zb.a?zb.a([$,Y],[c,d]):zb.call(null,[$,Y],[c,d])),b),a.c?a.c(Rd):a.call(null,Rd),a.c?a.c(ie):a.call(null,ie)))}function Ee(a){var b=ce.c(Rd.c(a));return s(b)?zc.b(a,new U(null,1,5,X,[de],null),function(b){return function(d){return xb.a(d,new U(null,2,5,X,[b,a.c?a.c(Yd):a.call(null,Yd)],null))}}(b)):a}
var Fe=innerWidth,Ge=innerHeight,He=S.b(new r(null,2,[ie,new U(null,4,5,X,[new r(null,4,[je,$,ge,0,ee,Ge,Wd,1],null),new r(null,4,[je,Y,ge,0,ee,Fe,Wd,1],null),new r(null,4,[je,$,ge,Fe,ee,Ge,Wd,-1],null),new r(null,4,[je,Y,ge,Ge,ee,Fe,Wd,-1],null)],null),Rd,new r(null,4,[$d,40,ke,40,Zd,new r(null,2,[$,Fe/2,Y,Ge/2],null),be,new r(null,2,[$,0,Y,0],null)],null)],null),de,Qc),Je=function Ie(b,c){requestAnimationFrame(function(){var d;d=Date.now();var e=d-Yd.c(b);d=S.b(Ee(De(S.b(b,he,La(we)),e)),Yd,d);
return Ie(d,c)});se(b);return oe(c,b)};function Ke(){Ld.f(N(["Starting..."],0));xe();var a=pe("canvas");a.width=innerWidth;a.height=innerHeight;document.body.appendChild(a);return Je(Bd.f(N([He,new r(null,1,[Yd,Date.now()],null)],0)),a)}var Le=["ball_roller","core","start"],Me=this;Le[0]in Me||!Me.execScript||Me.execScript("var "+Le[0]);for(var Ne;Le.length&&(Ne=Le.shift());)Le.length||void 0===Ke?Me=Me[Ne]?Me[Ne]:Me[Ne]={}:Me[Ne]=Ke;document.addEventListener("DOMContentLoaded",function(){return Ke()});
})();
