;(function(){
var g;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function da(a,b){null!=a&&this.append.apply(this,arguments)}da.prototype.sa="";da.prototype.append=function(a,b,c){this.sa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.sa+=arguments[d];return this};da.prototype.toString=function(){return this.sa};var ea;function fa(){throw Error("No *print-fn* fn set for evaluation environment");}var ga=null;function ia(){return new q(null,5,[ja,!0,ka,!0,la,!1,ma,!1,na,null],null)}function s(a){return null!=a&&!1!==a}function oa(a){return s(a)?!1:!0}function t(a,b){return a[n(null==b?null:b)]?!0:a._?!0:u?!1:null}function pa(a){return null==a?null:a.constructor}function v(a,b){var c=pa(b),c=s(s(c)?c.xa:c)?c.wa:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}
function qa(a){var b=a.wa;return s(b)?b:""+x(a)}function y(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
var sa=function(){function a(a,b){return ra.c?ra.c(function(a,b){a.push(b);return a},[],b):ra.call(null,function(a,b){a.push(b);return a},[],b)}function b(a){return c.a(null,a)}var c=null,c=function(d,c){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,0,c)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}(),ua={},va={};
function wa(a){if(a?a.J:a)return a.J(a);var b;b=wa[n(null==a?null:a)];if(!b&&(b=wa._,!b))throw v("ICounted.-count",a);return b.call(null,a)}function xa(a){if(a?a.M:a)return a.M(a);var b;b=xa[n(null==a?null:a)];if(!b&&(b=xa._,!b))throw v("IEmptyableCollection.-empty",a);return b.call(null,a)}function ya(a,b){if(a?a.I:a)return a.I(a,b);var c;c=ya[n(null==a?null:a)];if(!c&&(c=ya._,!c))throw v("ICollection.-conj",a);return c.call(null,a,b)}
var za={},z=function(){function a(a,b,c){if(a?a.$:a)return a.$(a,b,c);var h;h=z[n(null==a?null:a)];if(!h&&(h=z._,!h))throw v("IIndexed.-nth",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.K:a)return a.K(a,b);var c;c=z[n(null==a?null:a)];if(!c&&(c=z._,!c))throw v("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,f){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),
Aa={};function A(a){if(a?a.T:a)return a.T(a);var b;b=A[n(null==a?null:a)];if(!b&&(b=A._,!b))throw v("ISeq.-first",a);return b.call(null,a)}function C(a){if(a?a.W:a)return a.W(a);var b;b=C[n(null==a?null:a)];if(!b&&(b=C._,!b))throw v("ISeq.-rest",a);return b.call(null,a)}
var Ba={},Ca=function(){function a(a,b,c){if(a?a.O:a)return a.O(a,b,c);var h;h=Ca[n(null==a?null:a)];if(!h&&(h=Ca._,!h))throw v("ILookup.-lookup",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.N:a)return a.N(a,b);var c;c=Ca[n(null==a?null:a)];if(!c&&(c=Ca._,!c))throw v("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Da(a,b,c){if(a?a.ta:a)return a.ta(a,b,c);var d;d=Da[n(null==a?null:a)];if(!d&&(d=Da._,!d))throw v("IAssociative.-assoc",a);return d.call(null,a,b,c)}var Ea={};function Fa(a,b){if(a?a.cb:a)return a.cb(a,b);var c;c=Fa[n(null==a?null:a)];if(!c&&(c=Fa._,!c))throw v("IMap.-dissoc",a);return c.call(null,a,b)}var Ga={};function Ha(a){if(a?a.lb:a)return a.lb();var b;b=Ha[n(null==a?null:a)];if(!b&&(b=Ha._,!b))throw v("IMapEntry.-key",a);return b.call(null,a)}
function Ia(a){if(a?a.mb:a)return a.mb();var b;b=Ia[n(null==a?null:a)];if(!b&&(b=Ia._,!b))throw v("IMapEntry.-val",a);return b.call(null,a)}var Ja={};function Ka(a,b,c){if(a?a.eb:a)return a.eb(a,b,c);var d;d=Ka[n(null==a?null:a)];if(!d&&(d=Ka._,!d))throw v("IVector.-assoc-n",a);return d.call(null,a,b,c)}function Ma(a){if(a?a.Pa:a)return a.Pa(a);var b;b=Ma[n(null==a?null:a)];if(!b&&(b=Ma._,!b))throw v("IDeref.-deref",a);return b.call(null,a)}var Na={};
function Oa(a){if(a?a.B:a)return a.B(a);var b;b=Oa[n(null==a?null:a)];if(!b&&(b=Oa._,!b))throw v("IMeta.-meta",a);return b.call(null,a)}var Pa={};function Qa(a,b){if(a?a.C:a)return a.C(a,b);var c;c=Qa[n(null==a?null:a)];if(!c&&(c=Qa._,!c))throw v("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var Ra={},Sa=function(){function a(a,b,c){if(a?a.S:a)return a.S(a,b,c);var h;h=Sa[n(null==a?null:a)];if(!h&&(h=Sa._,!h))throw v("IReduce.-reduce",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.R:a)return a.R(a,b);var c;c=Sa[n(null==a?null:a)];if(!c&&(c=Sa._,!c))throw v("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Ta(a,b){if(a?a.v:a)return a.v(a,b);var c;c=Ta[n(null==a?null:a)];if(!c&&(c=Ta._,!c))throw v("IEquiv.-equiv",a);return c.call(null,a,b)}function Ua(a){if(a?a.A:a)return a.A(a);var b;b=Ua[n(null==a?null:a)];if(!b&&(b=Ua._,!b))throw v("IHash.-hash",a);return b.call(null,a)}var Va={};function Wa(a){if(a?a.G:a)return a.G(a);var b;b=Wa[n(null==a?null:a)];if(!b&&(b=Wa._,!b))throw v("ISeqable.-seq",a);return b.call(null,a)}var Xa={};
function D(a,b){if(a?a.pb:a)return a.pb(0,b);var c;c=D[n(null==a?null:a)];if(!c&&(c=D._,!c))throw v("IWriter.-write",a);return c.call(null,a,b)}var Ya={};function Za(a,b,c){if(a?a.u:a)return a.u(a,b,c);var d;d=Za[n(null==a?null:a)];if(!d&&(d=Za._,!d))throw v("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function $a(a,b,c){if(a?a.ob:a)return a.ob(0,b,c);var d;d=$a[n(null==a?null:a)];if(!d&&(d=$a._,!d))throw v("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function ab(a){if(a?a.Ga:a)return a.Ga(a);var b;b=ab[n(null==a?null:a)];if(!b&&(b=ab._,!b))throw v("IEditableCollection.-as-transient",a);return b.call(null,a)}function bb(a,b){if(a?a.Ha:a)return a.Ha(a,b);var c;c=bb[n(null==a?null:a)];if(!c&&(c=bb._,!c))throw v("ITransientCollection.-conj!",a);return c.call(null,a,b)}function cb(a){if(a?a.Ia:a)return a.Ia(a);var b;b=cb[n(null==a?null:a)];if(!b&&(b=cb._,!b))throw v("ITransientCollection.-persistent!",a);return b.call(null,a)}
function db(a,b,c){if(a?a.va:a)return a.va(a,b,c);var d;d=db[n(null==a?null:a)];if(!d&&(d=db._,!d))throw v("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function eb(a,b,c){if(a?a.nb:a)return a.nb(0,b,c);var d;d=eb[n(null==a?null:a)];if(!d&&(d=eb._,!d))throw v("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function fb(a){if(a?a.jb:a)return a.jb();var b;b=fb[n(null==a?null:a)];if(!b&&(b=fb._,!b))throw v("IChunk.-drop-first",a);return b.call(null,a)}
function gb(a){if(a?a.Na:a)return a.Na(a);var b;b=gb[n(null==a?null:a)];if(!b&&(b=gb._,!b))throw v("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function hb(a){if(a?a.Oa:a)return a.Oa(a);var b;b=hb[n(null==a?null:a)];if(!b&&(b=hb._,!b))throw v("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function ib(a){if(a?a.Ma:a)return a.Ma(a);var b;b=ib[n(null==a?null:a)];if(!b&&(b=ib._,!b))throw v("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function jb(a){this.Jb=a;this.n=0;this.g=1073741824}jb.prototype.pb=function(a,b){return this.Jb.append(b)};function kb(a){var b=new da;a.u(null,new jb(b),ia());return""+x(b)}function lb(a,b){if(s(F.a?F.a(a,b):F.call(null,a,b)))return 0;var c=oa(a.L);if(s(c?b.L:c))return-1;if(s(a.L)){if(oa(b.L))return 1;c=mb.a?mb.a(a.L,b.L):mb.call(null,a.L,b.L);return 0===c?mb.a?mb.a(a.name,b.name):mb.call(null,a.name,b.name):c}return nb?mb.a?mb.a(a.name,b.name):mb.call(null,a.name,b.name):null}
function G(a,b,c,d,e){this.L=a;this.name=b;this.ka=c;this.la=d;this.na=e;this.g=2154168321;this.n=4096}g=G.prototype;g.u=function(a,b){return D(b,this.ka)};g.A=function(){var a=this.la;return null!=a?a:this.la=a=ob.a?ob.a(H.b?H.b(this.L):H.call(null,this.L),H.b?H.b(this.name):H.call(null,this.name)):ob.call(null,H.b?H.b(this.L):H.call(null,this.L),H.b?H.b(this.name):H.call(null,this.name))};g.C=function(a,b){return new G(this.L,this.name,this.ka,this.la,b)};g.B=function(){return this.na};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return Ca.c(c,this,null);case 3:return Ca.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return Ca.c(a,this,null)};g.a=function(a,b){return Ca.c(a,this,b)};g.v=function(a,b){return b instanceof G?this.ka===b.ka:!1};g.toString=function(){return this.ka};
function I(a){if(null==a)return null;if(a&&(a.g&8388608||a.Rb))return a.G(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new pb(a,0);if(t(Va,a))return Wa(a);if(u)throw Error([x(a),x("is not ISeqable")].join(""));return null}function J(a){if(null==a)return null;if(a&&(a.g&64||a.ua))return a.T(null);a=I(a);return null==a?null:A(a)}function L(a){return null!=a?a&&(a.g&64||a.ua)?a.W(null):(a=I(a))?C(a):M:M}
function N(a){return null==a?null:a&&(a.g&128||a.Qb)?a.fa(null):I(L(a))}
var F=function(){function a(a,b){return null==a?null==b:a===b||Ta(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=O(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(N(e))a=d,d=J(e),e=N(e);else return b.a(d,J(e));else return!1}a.m=2;a.i=function(a){var b=J(a);a=N(a);var d=J(a);a=L(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);
default:return c.f(b,e,O(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.i=c.i;b.b=function(){return!0};b.a=a;b.f=c.f;return b}();va["null"]=!0;wa["null"]=function(){return 0};Date.prototype.v=function(a,b){return b instanceof Date&&this.toString()===b.toString()};Ta.number=function(a,b){return a===b};Na["function"]=!0;Oa["function"]=function(){return null};ua["function"]=!0;Ua._=function(a){return a[aa]||(a[aa]=++ba)};
var qb=function(){function a(a,b,c,d){for(var l=wa(a);;)if(d<l)c=b.a?b.a(c,z.a(a,d)):b.call(null,c,z.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=wa(a),l=0;;)if(l<d)c=b.a?b.a(c,z.a(a,l)):b.call(null,c,z.a(a,l)),l+=1;else return c}function c(a,b){var c=wa(a);if(0===c)return b.w?b.w():b.call(null);for(var d=z.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,z.a(a,l)):b.call(null,d,z.a(a,l)),l+=1;else return d}var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,
d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.j=a;return d}(),rb=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.w?b.w():b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.j=a;return d}();function sb(a){return a?a.g&2||a.vb?!0:a.g?!1:t(va,a):t(va,a)}function tb(a){return a?a.g&16||a.kb?!0:a.g?!1:t(za,a):t(za,a)}function pb(a,b){this.d=a;this.k=b;this.g=166199550;this.n=8192}g=pb.prototype;g.A=function(){return ub.b?ub.b(this):ub.call(null,this)};
g.fa=function(){return this.k+1<this.d.length?new pb(this.d,this.k+1):null};g.I=function(a,b){return P.a?P.a(b,this):P.call(null,b,this)};g.toString=function(){return kb(this)};g.R=function(a,b){return rb.j(this.d,b,this.d[this.k],this.k+1)};g.S=function(a,b,c){return rb.j(this.d,b,c,this.k)};g.G=function(){return this};g.J=function(){return this.d.length-this.k};g.T=function(){return this.d[this.k]};g.W=function(){return this.k+1<this.d.length?new pb(this.d,this.k+1):M};
g.v=function(a,b){return vb.a?vb.a(this,b):vb.call(null,this,b)};g.K=function(a,b){var c=b+this.k;return c<this.d.length?this.d[c]:null};g.$=function(a,b,c){a=b+this.k;return a<this.d.length?this.d[a]:c};g.M=function(){return M};
var wb=function(){function a(a,b){return b<a.length?new pb(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}(),O=function(){function a(a,b){return wb.a(a,b)}function b(a){return wb.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.b=b;c.a=a;return c}();Ta._=function(a,b){return a===b};
var xb=function(){function a(a,b){return null!=a?ya(a,b):ya(M,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=O(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(s(e))a=b.a(a,d),d=J(e),e=N(e);else return b.a(a,d)}a.m=2;a.i=function(a){var b=J(a);a=N(a);var d=J(a);a=L(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.f(b,e,O(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.m=2;b.i=c.i;b.a=a;b.f=c.f;return b}();function Q(a){if(null!=a)if(a&&(a.g&2||a.vb))a=a.J(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(t(va,a))a=wa(a);else if(u)a:{a=I(a);for(var b=0;;){if(sb(a)){a=b+wa(a);break a}a=N(a);b+=1}a=void 0}else a=null;else a=0;return a}
var yb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return I(a)?J(a):c;if(tb(a))return z.c(a,b,c);if(I(a))a=N(a),b-=1;else return u?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(I(a))return J(a);throw Error("Index out of bounds");}if(tb(a))return z.a(a,b);if(I(a)){var c=N(a),h=b-1;a=c;b=h}else{if(u)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),R=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.g&16||a.kb))return a.$(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(t(za,a))return z.a(a,b);if(a?a.g&64||a.ua||(a.g?0:t(Aa,a)):t(Aa,a))return yb.c(a,b,c);if(u)throw Error([x("nth not supported on this type "),x(qa(pa(a)))].join(""));return null}function b(a,
b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.g&16||a.kb))return a.K(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(t(za,a))return z.a(a,b);if(a?a.g&64||a.ua||(a.g?0:t(Aa,a)):t(Aa,a))return yb.a(a,b);if(u)throw Error([x("nth not supported on this type "),x(qa(pa(a)))].join(""));return null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,
e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),S=function(){function a(a,b,c){return null!=a?a&&(a.g&256||a.wb)?a.O(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:t(Ba,a)?Ca.c(a,b,c):u?c:null:c}function b(a,b){return null==a?null:a&&(a.g&256||a.wb)?a.N(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:t(Ba,a)?Ca.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),T=function(){function a(a,b,c){return null!=a?Da(a,b,c):zb.a?zb.a([b],[c]):zb.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=O(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.c(a,d,e),s(l))d=J(l),e=J(N(l)),l=N(N(l));else return a}a.m=3;a.i=function(a){var b=J(a);a=N(a);var d=J(a);
a=N(a);var l=J(a);a=L(a);return c(b,d,l,a)};a.f=c;return a}(),b=function(b,e,f,h){switch(arguments.length){case 3:return a.call(this,b,e,f);default:return c.f(b,e,f,O(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.m=3;b.i=c.i;b.c=a;b.f=c.f;return b}(),Ab=function(){function a(a,b){return null==a?null:Fa(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=O(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;){if(null==
a)return null;a=b.a(a,d);if(s(e))d=J(e),e=N(e);else return a}}a.m=2;a.i=function(a){var b=J(a);a=N(a);var d=J(a);a=L(a);return c(b,d,a)};a.f=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return b;case 2:return a.call(this,b,e);default:return c.f(b,e,O(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.i=c.i;b.b=function(a){return a};b.a=a;b.f=c.f;return b}();function Bb(a){var b="function"==n(a);return b?b:a?s(s(null)?null:a.ub)?!0:a.Vb?!1:t(ua,a):t(ua,a)}
var Eb=function Cb(b,c){return Bb(b)&&!(b?b.g&262144||b.Ub||(b.g?0:t(Pa,b)):t(Pa,b))?Cb(function(){"undefined"===typeof ea&&(ea=function(b,c,f,h){this.h=b;this.Ba=c;this.Lb=f;this.Eb=h;this.n=0;this.g=393217},ea.xa=!0,ea.wa="cljs.core/t10068",ea.Ja=function(b,c){return D(c,"cljs.core/t10068")},ea.prototype.call=function(){function b(d,h){d=this;var k=null;1<arguments.length&&(k=O(Array.prototype.slice.call(arguments,1),0));return c.call(this,d,k)}function c(b,d){return Db.a?Db.a(b.Ba,d):Db.call(null,
b.Ba,d)}b.m=1;b.i=function(b){var d=J(b);b=L(b);return c(d,b)};b.f=c;return b}(),ea.prototype.apply=function(b,c){return this.call.apply(this,[this].concat(y(c)))},ea.prototype.a=function(){function b(d){var h=null;0<arguments.length&&(h=O(Array.prototype.slice.call(arguments,0),0));return c.call(this,h)}function c(b){return Db.a?Db.a(self__.Ba,b):Db.call(null,self__.Ba,b)}b.m=0;b.i=function(b){b=I(b);return c(b)};b.f=c;return b}(),ea.prototype.ub=!0,ea.prototype.B=function(){return this.Eb},ea.prototype.C=
function(b,c){return new ea(this.h,this.Ba,this.Lb,c)});return new ea(c,b,Cb,null)}(),c):null==b?null:Qa(b,c)};function Fb(a){var b=null!=a;return(b?a?a.g&131072||a.yb||(a.g?0:t(Na,a)):t(Na,a):b)?Oa(a):null}var Gb={},Hb=0;
function H(a){if(a&&(a.g&4194304||a.Ob))a=a.A(null);else if("number"===typeof a)a=Math.floor(a)%2147483647;else if(!0===a)a=1;else if(!1===a)a=0;else if("string"===typeof a){255<Hb&&(Gb={},Hb=0);var b=Gb[a];if("number"!==typeof b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;Gb[a]=b;Hb+=1}a=b}else a=null==a?0:u?Ua(a):null;return a}function Ib(a){return a?a.g&16384||a.Tb?!0:a.g?!1:t(Ja,a):t(Ja,a)}function Jb(a){return a?a.n&512||a.Mb?!0:!1:!1}
function Kb(a){var b=[];ca(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Lb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}function Mb(a){return null==a?!1:a?a.g&64||a.ua?!0:a.g?!1:t(Aa,a):t(Aa,a)}function Nb(a){return s(a)?!0:!1}function mb(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(pa(a)===pa(b))return a&&(a.n&2048||a.Ea)?a.Fa(null,b):a>b?1:a<b?-1:0;if(u)throw Error("compare on non-nil objects of different types");return null}
var Ob=function(){function a(a,b,c,h){for(;;){var k=mb(R.a(a,h),R.a(b,h));if(0===k&&h+1<c)h+=1;else return k}}function b(a,b){var f=Q(a),h=Q(b);return f<h?-1:f>h?1:u?c.j(a,b,f,0):null}var c=null,c=function(c,e,f,h){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.j=a;return c}(),Pb=function(){function a(a,b,c){for(c=I(c);;)if(c)b=a.a?a.a(b,J(c)):a.call(null,b,J(c)),c=N(c);else return b}function b(a,
b){var c=I(b);return c?ra.c?ra.c(a,J(c),N(c)):ra.call(null,a,J(c),N(c)):a.w?a.w():a.call(null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),ra=function(){function a(a,b,c){return c&&(c.g&524288||c.Ab)?c.S(null,a,b):c instanceof Array?rb.c(c,a,b):"string"===typeof c?rb.c(c,a,b):t(Ra,c)?Sa.c(c,a,b):u?Pb.c(a,b,c):null}function b(a,b){return b&&(b.g&524288||
b.Ab)?b.R(null,a):b instanceof Array?rb.a(b,a):"string"===typeof b?rb.a(b,a):t(Ra,b)?Sa.a(b,a):u?Pb.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Qb(a){return 0<=a?Math.floor.b?Math.floor.b(a):Math.floor.call(null,a):Math.ceil.b?Math.ceil.b(a):Math.ceil.call(null,a)}
function Rb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}function Sb(a){var b=1;for(a=I(a);;)if(a&&0<b)b-=1,a=N(a);else return a}
var x=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=O(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new da(b.b(a)),l=d;;)if(s(l))e=e.append(b.b(J(l))),l=N(l);else return e.toString()}a.m=1;a.i=function(a){var b=J(a);a=L(a);return c(b,a)};a.f=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.f(b,O(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.i=c.i;b.w=function(){return""};b.b=a;b.f=c.f;return b}();function vb(a,b){return Nb((b?b.g&16777216||b.Sb||(b.g?0:t(Xa,b)):t(Xa,b))?function(){for(var c=I(a),d=I(b);;){if(null==c)return null==d;if(null==d)return!1;if(F.a(J(c),J(d)))c=N(c),d=N(d);else return u?!1:null}}():null)}function ob(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function ub(a){if(I(a)){var b=H(J(a));for(a=N(a);;){if(null==a)return b;b=ob(b,H(J(a)));a=N(a)}}else return 0}function Tb(a){var b=0;for(a=I(a);;)if(a){var c=J(a),b=(b+(H(Vb.b?Vb.b(c):Vb.call(null,c))^H(Wb.b?Wb.b(c):Wb.call(null,c))))%4503599627370496;a=N(a)}else return b}function Xb(a,b,c,d,e){this.h=a;this.ya=b;this.ia=c;this.count=d;this.l=e;this.g=65937646;this.n=8192}g=Xb.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.fa=function(){return 1===this.count?null:this.ia};
g.I=function(a,b){return new Xb(this.h,b,this,this.count+1,null)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return this};g.J=function(){return this.count};g.T=function(){return this.ya};g.W=function(){return 1===this.count?M:this.ia};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new Xb(b,this.ya,this.ia,this.count,this.l)};g.B=function(){return this.h};g.M=function(){return M};
function Yb(a){this.h=a;this.g=65937614;this.n=8192}g=Yb.prototype;g.A=function(){return 0};g.fa=function(){return null};g.I=function(a,b){return new Xb(this.h,b,null,1,null)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return null};g.J=function(){return 0};g.T=function(){return null};g.W=function(){return M};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new Yb(b)};g.B=function(){return this.h};
g.M=function(){return this};var M=new Yb(null),Zb=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof pb&&0===a.k)b=a.d;else a:{for(b=[];;)if(null!=a)b.push(a.T(null)),a=a.fa(null);else break a;b=void 0}a=b.length;for(var e=M;;)if(0<a){var f=a-1,e=e.I(null,b[a-1]);a=f}else return e}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}();
function $b(a,b,c,d){this.h=a;this.ya=b;this.ia=c;this.l=d;this.g=65929452;this.n=8192}g=$b.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.fa=function(){return null==this.ia?null:I(this.ia)};g.I=function(a,b){return new $b(null,b,this,this.l)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return this};g.T=function(){return this.ya};g.W=function(){return null==this.ia?M:this.ia};
g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new $b(b,this.ya,this.ia,this.l)};g.B=function(){return this.h};g.M=function(){return Eb(M,this.h)};function P(a,b){var c=null==b;return(c?c:b&&(b.g&64||b.ua))?new $b(null,a,b,null):new $b(null,a,I(b),null)}function V(a,b,c,d){this.L=a;this.name=b;this.ja=c;this.la=d;this.g=2153775105;this.n=4096}g=V.prototype;g.u=function(a,b){return D(b,[x(":"),x(this.ja)].join(""))};
g.A=function(){null==this.la&&(this.la=ob(H(this.L),H(this.name))+2654435769);return this.la};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return S.a(c,this);case 3:return S.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return S.a(a,this)};g.a=function(a,b){return S.c(a,this,b)};g.v=function(a,b){return b instanceof V?this.ja===b.ja:!1};
g.toString=function(){return[x(":"),x(this.ja)].join("")};function ac(a,b){return a===b?!0:a instanceof V&&b instanceof V?a.ja===b.ja:!1}
var cc=function(){function a(a,b){return new V(a,b,[x(s(a)?[x(a),x("/")].join(""):null),x(b)].join(""),null)}function b(a){if(a instanceof V)return a;if(a instanceof G){var b;if(a&&(a.n&4096||a.zb))b=a.L;else throw Error([x("Doesn't support namespace: "),x(a)].join(""));return new V(b,bc.b?bc.b(a):bc.call(null,a),a.ka,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new V(b[0],b[1],a,null):new V(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,
c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.a=a;return c}();function dc(a,b,c,d){this.h=a;this.ra=b;this.r=c;this.l=d;this.n=0;this.g=32374988}g=dc.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.fa=function(){Wa(this);return null==this.r?null:N(this.r)};g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};function ec(a){null!=a.ra&&(a.r=a.ra.w?a.ra.w():a.ra.call(null),a.ra=null);return a.r}
g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){ec(this);if(null==this.r)return null;for(var a=this.r;;)if(a instanceof dc)a=ec(a);else return this.r=a,I(this.r)};g.T=function(){Wa(this);return null==this.r?null:J(this.r)};g.W=function(){Wa(this);return null!=this.r?L(this.r):M};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new dc(b,this.ra,this.r,this.l)};g.B=function(){return this.h};g.M=function(){return Eb(M,this.h)};
function fc(a,b){this.H=a;this.end=b;this.n=0;this.g=2}fc.prototype.J=function(){return this.end};fc.prototype.add=function(a){this.H[this.end]=a;return this.end+=1};fc.prototype.Y=function(){var a=new gc(this.H,0,this.end);this.H=null;return a};function gc(a,b,c){this.d=a;this.s=b;this.end=c;this.n=0;this.g=524306}g=gc.prototype;g.R=function(a,b){return rb.j(this.d,b,this.d[this.s],this.s+1)};g.S=function(a,b,c){return rb.j(this.d,b,c,this.s)};
g.jb=function(){if(this.s===this.end)throw Error("-drop-first of empty chunk");return new gc(this.d,this.s+1,this.end)};g.K=function(a,b){return this.d[this.s+b]};g.$=function(a,b,c){return 0<=b&&b<this.end-this.s?this.d[this.s+b]:c};g.J=function(){return this.end-this.s};
var hc=function(){function a(a,b,c){return new gc(a,b,c)}function b(a,b){return new gc(a,b,a.length)}function c(a){return new gc(a,0,a.length)}var d=null,d=function(d,f,h){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}throw Error("Invalid arity: "+arguments.length);};d.b=c;d.a=b;d.c=a;return d}();function ic(a,b,c,d){this.Y=a;this.da=b;this.h=c;this.l=d;this.g=31850732;this.n=1536}g=ic.prototype;
g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.fa=function(){if(1<wa(this.Y))return new ic(fb(this.Y),this.da,this.h,null);var a=Wa(this.da);return null==a?null:a};g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};g.G=function(){return this};g.T=function(){return z.a(this.Y,0)};g.W=function(){return 1<wa(this.Y)?new ic(fb(this.Y),this.da,this.h,null):null==this.da?M:this.da};g.Ma=function(){return null==this.da?null:this.da};
g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new ic(this.Y,this.da,b,this.l)};g.B=function(){return this.h};g.M=function(){return Eb(M,this.h)};g.Na=function(){return this.Y};g.Oa=function(){return null==this.da?M:this.da};function jc(a,b){return 0===wa(a)?b:new ic(a,b,null,null)}function kc(a){for(var b=[];;)if(I(a))b.push(J(a)),a=N(a);else return b}function lc(a,b){if(sb(a))return Q(a);for(var c=a,d=b,e=0;;)if(0<d&&I(c))c=N(c),d-=1,e+=1;else return e}
var nc=function mc(b){return null==b?null:null==N(b)?I(J(b)):u?P(J(b),mc(N(b))):null},oc=function(){function a(a,b,c,d){return P(a,P(b,P(c,d)))}function b(a,b,c){return P(a,P(b,c))}var c=null,d=function(){function a(c,d,e,m,p){var r=null;4<arguments.length&&(r=O(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,r)}function b(a,c,d,e,f){return P(a,P(c,P(d,P(e,nc(f)))))}a.m=4;a.i=function(a){var c=J(a);a=N(a);var d=J(a);a=N(a);var e=J(a);a=N(a);var p=J(a);a=L(a);return b(c,d,e,
p,a)};a.f=b;return a}(),c=function(c,f,h,k,l){switch(arguments.length){case 1:return I(c);case 2:return P(c,f);case 3:return b.call(this,c,f,h);case 4:return a.call(this,c,f,h,k);default:return d.f(c,f,h,k,O(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.m=4;c.i=d.i;c.b=function(a){return I(a)};c.a=function(a,b){return P(a,b)};c.c=b;c.j=a;c.f=d.f;return c}(),pc=function(){var a=null,b=function(){function a(c,f,h,k){var l=null;3<arguments.length&&(l=O(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,f,h,l)}function b(a,c,d,k){for(;;)if(a=db(a,c,d),s(k))c=J(k),d=J(N(k)),k=N(N(k));else return a}a.m=3;a.i=function(a){var c=J(a);a=N(a);var h=J(a);a=N(a);var k=J(a);a=L(a);return b(c,h,k,a)};a.f=b;return a}(),a=function(a,d,e,f){switch(arguments.length){case 3:return db(a,d,e);default:return b.f(a,d,e,O(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.m=3;a.i=b.i;a.c=function(a,b,e){return db(a,b,e)};a.f=b.f;return a}();
function qc(a,b,c){var d=I(c);if(0===b)return a.w?a.w():a.call(null);c=A(d);var e=C(d);if(1===b)return a.b?a.b(c):a.b?a.b(c):a.call(null,c);var d=A(e),f=C(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=A(f),h=C(f);if(3===b)return a.c?a.c(c,d,e):a.c?a.c(c,d,e):a.call(null,c,d,e);var f=A(h),k=C(h);if(4===b)return a.j?a.j(c,d,e,f):a.j?a.j(c,d,e,f):a.call(null,c,d,e,f);var h=A(k),l=C(k);if(5===b)return a.F?a.F(c,d,e,f,h):a.F?a.F(c,d,e,f,h):a.call(null,c,d,e,f,h);var k=A(l),m=C(l);
if(6===b)return a.Z?a.Z(c,d,e,f,h,k):a.Z?a.Z(c,d,e,f,h,k):a.call(null,c,d,e,f,h,k);var l=A(m),p=C(m);if(7===b)return a.oa?a.oa(c,d,e,f,h,k,l):a.oa?a.oa(c,d,e,f,h,k,l):a.call(null,c,d,e,f,h,k,l);var m=A(p),r=C(p);if(8===b)return a.ab?a.ab(c,d,e,f,h,k,l,m):a.ab?a.ab(c,d,e,f,h,k,l,m):a.call(null,c,d,e,f,h,k,l,m);var p=A(r),w=C(r);if(9===b)return a.bb?a.bb(c,d,e,f,h,k,l,m,p):a.bb?a.bb(c,d,e,f,h,k,l,m,p):a.call(null,c,d,e,f,h,k,l,m,p);var r=A(w),B=C(w);if(10===b)return a.Qa?a.Qa(c,d,e,f,h,k,l,m,p,r):a.Qa?
a.Qa(c,d,e,f,h,k,l,m,p,r):a.call(null,c,d,e,f,h,k,l,m,p,r);var w=A(B),E=C(B);if(11===b)return a.Ra?a.Ra(c,d,e,f,h,k,l,m,p,r,w):a.Ra?a.Ra(c,d,e,f,h,k,l,m,p,r,w):a.call(null,c,d,e,f,h,k,l,m,p,r,w);var B=A(E),K=C(E);if(12===b)return a.Sa?a.Sa(c,d,e,f,h,k,l,m,p,r,w,B):a.Sa?a.Sa(c,d,e,f,h,k,l,m,p,r,w,B):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B);var E=A(K),U=C(K);if(13===b)return a.Ta?a.Ta(c,d,e,f,h,k,l,m,p,r,w,B,E):a.Ta?a.Ta(c,d,e,f,h,k,l,m,p,r,w,B,E):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E);var K=A(U),Z=C(U);
if(14===b)return a.Ua?a.Ua(c,d,e,f,h,k,l,m,p,r,w,B,E,K):a.Ua?a.Ua(c,d,e,f,h,k,l,m,p,r,w,B,E,K):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K);var U=A(Z),ha=C(Z);if(15===b)return a.Va?a.Va(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U):a.Va?a.Va(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,U);var Z=A(ha),ta=C(ha);if(16===b)return a.Wa?a.Wa(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z):a.Wa?a.Wa(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z);var ha=A(ta),La=C(ta);if(17===b)return a.Xa?
a.Xa(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha):a.Xa?a.Xa(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha);var ta=A(La),Ub=C(La);if(18===b)return a.Ya?a.Ya(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta):a.Ya?a.Ya(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta);La=A(Ub);Ub=C(Ub);if(19===b)return a.Za?a.Za(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta,La):a.Za?a.Za(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta,La):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,
U,Z,ha,ta,La);var Zc=A(Ub);C(Ub);if(20===b)return a.$a?a.$a(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta,La,Zc):a.$a?a.$a(c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta,La,Zc):a.call(null,c,d,e,f,h,k,l,m,p,r,w,B,E,K,U,Z,ha,ta,La,Zc);throw Error("Only up to 20 arguments supported on functions");}
var Db=function(){function a(a,b,c,d,e){b=oc.j(b,c,d,e);c=a.m;return a.i?(d=lc(b,c+1),d<=c?qc(a,d,b):a.i(b)):a.apply(a,kc(b))}function b(a,b,c,d){b=oc.c(b,c,d);c=a.m;return a.i?(d=lc(b,c+1),d<=c?qc(a,d,b):a.i(b)):a.apply(a,kc(b))}function c(a,b,c){b=oc.a(b,c);c=a.m;if(a.i){var d=lc(b,c+1);return d<=c?qc(a,d,b):a.i(b)}return a.apply(a,kc(b))}function d(a,b){var c=a.m;if(a.i){var d=lc(b,c+1);return d<=c?qc(a,d,b):a.i(b)}return a.apply(a,kc(b))}var e=null,f=function(){function a(c,d,e,f,h,B){var E=null;
5<arguments.length&&(E=O(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,f,h,E)}function b(a,c,d,e,f,h){c=P(c,P(d,P(e,P(f,nc(h)))));d=a.m;return a.i?(e=lc(c,d+1),e<=d?qc(a,e,c):a.i(c)):a.apply(a,kc(c))}a.m=5;a.i=function(a){var c=J(a);a=N(a);var d=J(a);a=N(a);var e=J(a);a=N(a);var f=J(a);a=N(a);var h=J(a);a=L(a);return b(c,d,e,f,h,a)};a.f=b;return a}(),e=function(e,k,l,m,p,r){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,p);default:return f.f(e,k,l,m,p,O(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.m=5;e.i=f.i;e.a=d;e.c=c;e.j=b;e.F=a;e.f=f.f;return e}();function rc(a,b){for(;;){if(null==I(b))return!0;if(s(a.b?a.b(J(b)):a.call(null,J(b)))){var c=a,d=N(b);a=c;b=d}else return u?!1:null}}function sc(a){for(var b=tc;;)if(I(a)){var c=b.b?b.b(J(a)):b.call(null,J(a));if(s(c))return c;a=N(a)}else return null}function tc(a){return a}
var uc=function(){function a(a,b,c,e){return new dc(null,function(){var m=I(b),p=I(c),r=I(e);return m&&p&&r?P(a.c?a.c(J(m),J(p),J(r)):a.call(null,J(m),J(p),J(r)),d.j(a,L(m),L(p),L(r))):null},null,null)}function b(a,b,c){return new dc(null,function(){var e=I(b),m=I(c);return e&&m?P(a.a?a.a(J(e),J(m)):a.call(null,J(e),J(m)),d.c(a,L(e),L(m))):null},null,null)}function c(a,b){return new dc(null,function(){var c=I(b);if(c){if(Jb(c)){for(var e=gb(c),m=Q(e),p=new fc(Array(m),0),r=0;;)if(r<m){var w=a.b?a.b(z.a(e,
r)):a.call(null,z.a(e,r));p.add(w);r+=1}else break;return jc(p.Y(),d.a(a,hb(c)))}return P(a.b?a.b(J(c)):a.call(null,J(c)),d.a(a,L(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,f,r){var w=null;4<arguments.length&&(w=O(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,w)}function b(a,c,e,f,h){var w=function E(a){return new dc(null,function(){var b=d.a(I,a);return rc(tc,b)?P(d.a(J,b),E(d.a(L,b))):null},null,null)};return d.a(function(){return function(b){return Db.a(a,
b)}}(w),w(xb.f(h,f,O([e,c],0))))}a.m=4;a.i=function(a){var c=J(a);a=N(a);var d=J(a);a=N(a);var e=J(a);a=N(a);var f=J(a);a=L(a);return b(c,d,e,f,a)};a.f=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.f(d,h,k,l,O(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.i=e.i;d.a=c;d.c=b;d.j=a;d.f=e.f;return d}(),wc=function vc(b,c,d){var e=R.c(c,0,null);return(c=
Sb(c))?T.c(b,e,vc(S.a(b,e),c,d)):T.c(b,e,d)},xc=function(){function a(a,b,c,d,f,r){var w=R.c(b,0,null);return(b=Sb(b))?T.c(a,w,e.Z(S.a(a,w),b,c,d,f,r)):T.c(a,w,c.j?c.j(S.a(a,w),d,f,r):c.call(null,S.a(a,w),d,f,r))}function b(a,b,c,d,f){var r=R.c(b,0,null);return(b=Sb(b))?T.c(a,r,e.F(S.a(a,r),b,c,d,f)):T.c(a,r,c.c?c.c(S.a(a,r),d,f):c.call(null,S.a(a,r),d,f))}function c(a,b,c,d){var f=R.c(b,0,null);return(b=Sb(b))?T.c(a,f,e.j(S.a(a,f),b,c,d)):T.c(a,f,c.a?c.a(S.a(a,f),d):c.call(null,S.a(a,f),d))}function d(a,
b,c){var d=R.c(b,0,null);return(b=Sb(b))?T.c(a,d,e.c(S.a(a,d),b,c)):T.c(a,d,c.b?c.b(S.a(a,d)):c.call(null,S.a(a,d)))}var e=null,f=function(){function a(c,d,e,f,h,B,E){var K=null;6<arguments.length&&(K=O(Array.prototype.slice.call(arguments,6),0));return b.call(this,c,d,e,f,h,B,K)}function b(a,c,d,f,h,k,E){var K=R.c(c,0,null);return(c=Sb(c))?T.c(a,K,Db.f(e,S.a(a,K),c,d,f,O([h,k,E],0))):T.c(a,K,Db.f(d,S.a(a,K),f,h,k,O([E],0)))}a.m=6;a.i=function(a){var c=J(a);a=N(a);var d=J(a);a=N(a);var e=J(a);a=N(a);
var f=J(a);a=N(a);var h=J(a);a=N(a);var E=J(a);a=L(a);return b(c,d,e,f,h,E,a)};a.f=b;return a}(),e=function(e,k,l,m,p,r,w){switch(arguments.length){case 3:return d.call(this,e,k,l);case 4:return c.call(this,e,k,l,m);case 5:return b.call(this,e,k,l,m,p);case 6:return a.call(this,e,k,l,m,p,r);default:return f.f(e,k,l,m,p,r,O(arguments,6))}throw Error("Invalid arity: "+arguments.length);};e.m=6;e.i=f.i;e.c=d;e.j=c;e.F=b;e.Z=a;e.f=f.f;return e}();function yc(a,b){this.o=a;this.d=b}
function zc(a){return new yc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Ac(a){a=a.e;return 32>a?0:a-1>>>5<<5}function Bc(a,b,c){for(;;){if(0===b)return c;var d=zc(a);d.d[0]=c;c=d;b-=5}}var Dc=function Cc(b,c,d,e){var f=new yc(d.o,y(d.d)),h=b.e-1>>>c&31;5===c?f.d[h]=e:(d=d.d[h],b=null!=d?Cc(b,c-5,d,e):Bc(null,c-5,e),f.d[h]=b);return f};
function Ec(a,b){throw Error([x("No item "),x(a),x(" in vector of length "),x(b)].join(""));}function Fc(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.d[0];else return b.d}function Gc(a,b){if(b>=Ac(a))return a.p;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.d[b>>>d&31],d=e;else return c.d}function Hc(a,b){return 0<=b&&b<a.e?Gc(a,b):Ec(b,a.e)}var Jc=function Ic(b,c,d,e,f){var h=new yc(d.o,y(d.d));if(0===c)h.d[e&31]=f;else{var k=e>>>c&31;b=Ic(b,c-5,d.d[k],e,f);h.d[k]=b}return h};
function W(a,b,c,d,e,f){this.h=a;this.e=b;this.shift=c;this.root=d;this.p=e;this.l=f;this.n=8196;this.g=167668511}g=W.prototype;g.Ga=function(){return new Kc(this.e,this.shift,Lc.b?Lc.b(this.root):Lc.call(null,this.root),Mc.b?Mc.b(this.p):Mc.call(null,this.p))};g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};
g.ta=function(a,b,c){if("number"===typeof b)return Ka(this,b,c);throw Error("Vector's key for assoc must be a number.");};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.$(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return this.K(null,a)};g.a=function(a,b){return this.$(null,a,b)};
g.I=function(a,b){if(32>this.e-Ac(this)){for(var c=this.p.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.p[e],e+=1;else break;d[c]=b;return new W(this.h,this.e+1,this.shift,this.root,d,null)}c=(d=this.e>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=zc(null),d.d[0]=this.root,e=Bc(null,this.shift,new yc(null,this.p)),d.d[1]=e):d=Dc(this,this.shift,this.root,new yc(null,this.p));return new W(this.h,this.e+1,c,d,[b],null)};g.lb=function(){return z.a(this,0)};g.mb=function(){return z.a(this,1)};
g.toString=function(){return kb(this)};g.R=function(a,b){return qb.a(this,b)};g.S=function(a,b,c){return qb.c(this,b,c)};g.G=function(){return 0===this.e?null:32>=this.e?new pb(this.p,0):u?X.j?X.j(this,Fc(this),0,0):X.call(null,this,Fc(this),0,0):null};g.J=function(){return this.e};
g.eb=function(a,b,c){if(0<=b&&b<this.e)return Ac(this)<=b?(a=y(this.p),a[b&31]=c,new W(this.h,this.e,this.shift,this.root,a,null)):new W(this.h,this.e,this.shift,Jc(this,this.shift,this.root,b,c),this.p,null);if(b===this.e)return ya(this,c);if(u)throw Error([x("Index "),x(b),x(" out of bounds  [0,"),x(this.e),x("]")].join(""));return null};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new W(b,this.e,this.shift,this.root,this.p,this.l)};g.B=function(){return this.h};
g.K=function(a,b){return Hc(this,b)[b&31]};g.$=function(a,b,c){return 0<=b&&b<this.e?Gc(this,b)[b&31]:c};g.M=function(){return Eb(Nc,this.h)};var Y=new yc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Nc=new W(null,0,5,Y,[],0);function Oc(a,b,c,d,e,f){this.t=a;this.X=b;this.k=c;this.s=d;this.h=e;this.l=f;this.g=32243948;this.n=1536}g=Oc.prototype;
g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.fa=function(){if(this.s+1<this.X.length){var a=X.j?X.j(this.t,this.X,this.k,this.s+1):X.call(null,this.t,this.X,this.k,this.s+1);return null==a?null:a}return ib(this)};g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};g.R=function(a,b){return qb.a(Pc.c?Pc.c(this.t,this.k+this.s,Q(this.t)):Pc.call(null,this.t,this.k+this.s,Q(this.t)),b)};
g.S=function(a,b,c){return qb.c(Pc.c?Pc.c(this.t,this.k+this.s,Q(this.t)):Pc.call(null,this.t,this.k+this.s,Q(this.t)),b,c)};g.G=function(){return this};g.T=function(){return this.X[this.s]};g.W=function(){if(this.s+1<this.X.length){var a=X.j?X.j(this.t,this.X,this.k,this.s+1):X.call(null,this.t,this.X,this.k,this.s+1);return null==a?M:a}return hb(this)};g.Ma=function(){var a=this.k+this.X.length;return a<wa(this.t)?X.j?X.j(this.t,Gc(this.t,a),a,0):X.call(null,this.t,Gc(this.t,a),a,0):null};
g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return X.F?X.F(this.t,this.X,this.k,this.s,b):X.call(null,this.t,this.X,this.k,this.s,b)};g.M=function(){return Eb(Nc,this.h)};g.Na=function(){return hc.a(this.X,this.s)};g.Oa=function(){var a=this.k+this.X.length;return a<wa(this.t)?X.j?X.j(this.t,Gc(this.t,a),a,0):X.call(null,this.t,Gc(this.t,a),a,0):M};
var X=function(){function a(a,b,c,d,l){return new Oc(a,b,c,d,l,null)}function b(a,b,c,d){return new Oc(a,b,c,d,null,null)}function c(a,b,c){return new Oc(a,Hc(a,b),b,c,null,null)}var d=null,d=function(d,f,h,k,l){switch(arguments.length){case 3:return c.call(this,d,f,h);case 4:return b.call(this,d,f,h,k);case 5:return a.call(this,d,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.j=b;d.F=a;return d}();
function Qc(a,b,c,d,e){this.h=a;this.ea=b;this.start=c;this.end=d;this.l=e;this.g=166617887;this.n=8192}g=Qc.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};g.ta=function(a,b,c){if("number"===typeof b)return Ka(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.$(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return this.K(null,a)};g.a=function(a,b){return this.$(null,a,b)};
g.I=function(a,b){return Rc.F?Rc.F(this.h,Ka(this.ea,this.end,b),this.start,this.end+1,null):Rc.call(null,this.h,Ka(this.ea,this.end,b),this.start,this.end+1,null)};g.toString=function(){return kb(this)};g.R=function(a,b){return qb.a(this,b)};g.S=function(a,b,c){return qb.c(this,b,c)};g.G=function(){var a=this;return function(b){return function d(e){return e===a.end?null:P(z.a(a.ea,e),new dc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
g.J=function(){return this.end-this.start};g.eb=function(a,b,c){var d=this,e=d.start+b;return Rc.F?Rc.F(d.h,T.c(d.ea,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):Rc.call(null,d.h,T.c(d.ea,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return Rc.F?Rc.F(b,this.ea,this.start,this.end,this.l):Rc.call(null,b,this.ea,this.start,this.end,this.l)};g.B=function(){return this.h};
g.K=function(a,b){return 0>b||this.end<=this.start+b?Ec(b,this.end-this.start):z.a(this.ea,this.start+b)};g.$=function(a,b,c){return 0>b||this.end<=this.start+b?c:z.c(this.ea,this.start+b,c)};g.M=function(){return Eb(Nc,this.h)};function Rc(a,b,c,d,e){for(;;)if(b instanceof Qc)c=b.start+c,d=b.start+d,b=b.ea;else{var f=Q(b);if(0>c||0>d||c>f||d>f)throw Error("Index out of bounds");return new Qc(a,b,c,d,e)}}
var Pc=function(){function a(a,b,c){return Rc(null,a,b,c,null)}function b(a,b){return c.c(a,b,Q(a))}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Lc(a){return new yc({},y(a.d))}
function Mc(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Lb(a,0,b,0,a.length);return b}var Tc=function Sc(b,c,d,e){d=b.root.o===d.o?d:new yc(b.root.o,y(d.d));var f=b.e-1>>>c&31;if(5===c)b=e;else{var h=d.d[f];b=null!=h?Sc(b,c-5,h,e):Bc(b.root.o,c-5,e)}d.d[f]=b;return d};function Kc(a,b,c,d){this.e=a;this.shift=b;this.root=c;this.p=d;this.g=275;this.n=88}g=Kc.prototype;
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return this.N(null,a)};g.a=function(a,b){return this.O(null,a,b)};g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};
g.K=function(a,b){if(this.root.o)return Hc(this,b)[b&31];throw Error("nth after persistent!");};g.$=function(a,b,c){return 0<=b&&b<this.e?z.a(this,b):c};g.J=function(){if(this.root.o)return this.e;throw Error("count after persistent!");};
g.nb=function(a,b,c){var d=this;if(d.root.o){if(0<=b&&b<d.e)return Ac(this)<=b?d.p[b&31]=c:(a=function(){return function f(a,k){var l=d.root.o===k.o?k:new yc(d.root.o,y(k.d));if(0===a)l.d[b&31]=c;else{var m=b>>>a&31,p=f(a-5,l.d[m]);l.d[m]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.e)return bb(this,c);if(u)throw Error([x("Index "),x(b),x(" out of bounds for TransientVector of length"),x(d.e)].join(""));return null}throw Error("assoc! after persistent!");};
g.va=function(a,b,c){if("number"===typeof b)return eb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
g.Ha=function(a,b){if(this.root.o){if(32>this.e-Ac(this))this.p[this.e&31]=b;else{var c=new yc(this.root.o,this.p),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.p=d;if(this.e>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Bc(this.root.o,this.shift,c);this.root=new yc(this.root.o,d);this.shift=e}else this.root=Tc(this,this.shift,this.root,c)}this.e+=1;return this}throw Error("conj! after persistent!");};g.Ia=function(){if(this.root.o){this.root.o=null;var a=this.e-Ac(this),b=Array(a);Lb(this.p,0,b,0,a);return new W(null,this.e,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function Uc(){this.n=0;this.g=2097152}Uc.prototype.v=function(){return!1};var Vc=new Uc;
function Wc(a,b){return Nb((null==b?0:b?b.g&1024||b.Pb||(b.g?0:t(Ea,b)):t(Ea,b))?Q(a)===Q(b)?rc(tc,uc.a(function(a){return F.a(S.c(b,J(a),Vc),J(N(a)))},a)):null:null)}
function Xc(a,b){var c=a.d;if(b instanceof V)a:{for(var d=c.length,e=b.ja,f=0;;){if(d<=f){c=-1;break a}var h=c[f];if(h instanceof V&&e===h.ja){c=f;break a}if(u)f+=2;else{c=null;break a}}c=void 0}else if("string"==typeof b||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof G)a:{d=c.length;e=b.ka;for(f=0;;){if(d<=f){c=-1;break a}h=c[f];if(h instanceof G&&e===h.ka){c=f;break a}if(u)f+=2;else{c=null;
break a}}c=void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else if(u)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(F.a(b,c[e])){c=e;break a}if(u)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function Yc(a,b,c){this.d=a;this.k=b;this.na=c;this.n=0;this.g=32374990}g=Yc.prototype;g.A=function(){return ub(this)};g.fa=function(){return this.k<this.d.length-2?new Yc(this.d,this.k+2,this.na):null};
g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return this};g.J=function(){return(this.d.length-this.k)/2};g.T=function(){return new W(null,2,5,Y,[this.d[this.k],this.d[this.k+1]],null)};g.W=function(){return this.k<this.d.length-2?new Yc(this.d,this.k+2,this.na):M};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new Yc(this.d,this.k,b)};g.B=function(){return this.na};
g.M=function(){return Eb(M,this.na)};function q(a,b,c,d){this.h=a;this.e=b;this.d=c;this.l=d;this.n=8196;this.g=16123663}g=q.prototype;g.Ga=function(){return new $c({},this.d.length,y(this.d))};g.A=function(){var a=this.l;return null!=a?a:this.l=a=Tb(this)};g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){a=Xc(this,b);return-1===a?c:this.d[a+1]};
g.ta=function(a,b,c){a=Xc(this,b);if(-1===a){if(this.e<ad){a=this.d;for(var d=a.length,e=Array(d+2),f=0;;)if(f<d)e[f]=a[f],f+=1;else break;e[d]=b;e[d+1]=c;return new q(this.h,this.e+1,e,null)}a=Qa;d=Da;e=bd;null!=e?e&&(e.n&4||e.Nb)?(e=ra.c(bb,ab(e),this),e=cb(e)):e=ra.c(ya,e,this):e=ra.c(xb,M,this);return a(d(e,b,c),this.h)}return c===this.d[a+1]?this:u?(b=y(this.d),b[a+1]=c,new q(this.h,this.e,b,null)):null};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return this.N(null,a)};g.a=function(a,b){return this.O(null,a,b)};g.I=function(a,b){return Ib(b)?Da(this,z.a(b,0),z.a(b,1)):ra.c(ya,this,b)};g.toString=function(){return kb(this)};
g.G=function(){return 0<=this.d.length-2?new Yc(this.d,0,null):null};g.J=function(){return this.e};g.v=function(a,b){return Wc(this,b)};g.C=function(a,b){return new q(b,this.e,this.d,this.l)};g.B=function(){return this.h};g.M=function(){return Qa(cd,this.h)};
g.cb=function(a,b){if(0<=Xc(this,b)){var c=this.d.length,d=c-2;if(0===d)return xa(this);for(var d=Array(d),e=0,f=0;;){if(e>=c)return new q(this.h,this.e-1,d,null);if(F.a(b,this.d[e]))e+=2;else if(u)d[f]=this.d[e],d[f+1]=this.d[e+1],f+=2,e+=2;else return null}}else return this};var cd=new q(null,0,[],null),ad=8;function $c(a,b,c){this.pa=a;this.ha=b;this.d=c;this.n=56;this.g=258}g=$c.prototype;
g.va=function(a,b,c){if(s(this.pa)){a=Xc(this,b);if(-1===a)return this.ha+2<=2*ad?(this.ha+=2,this.d.push(b),this.d.push(c),this):pc.c(dd.a?dd.a(this.ha,this.d):dd.call(null,this.ha,this.d),b,c);c!==this.d[a+1]&&(this.d[a+1]=c);return this}throw Error("assoc! after persistent!");};
g.Ha=function(a,b){if(s(this.pa)){if(b?b.g&2048||b.xb||(b.g?0:t(Ga,b)):t(Ga,b))return db(this,Vb.b?Vb.b(b):Vb.call(null,b),Wb.b?Wb.b(b):Wb.call(null,b));for(var c=I(b),d=this;;){var e=J(c);if(s(e))c=N(c),d=db(d,Vb.b?Vb.b(e):Vb.call(null,e),Wb.b?Wb.b(e):Wb.call(null,e));else return d}}else throw Error("conj! after persistent!");};g.Ia=function(){if(s(this.pa))return this.pa=!1,new q(null,Qb((this.ha-this.ha%2)/2),this.d,null);throw Error("persistent! called twice");};
g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){if(s(this.pa))return a=Xc(this,b),-1===a?c:this.d[a+1];throw Error("lookup after persistent!");};g.J=function(){if(s(this.pa))return Qb((this.ha-this.ha%2)/2);throw Error("count after persistent!");};function dd(a,b){for(var c=ab(bd),d=0;;)if(d<a)c=pc.c(c,b[d],b[d+1]),d+=2;else return c}function ed(){this.D=!1}function fd(a,b){return a===b?!0:ac(a,b)?!0:u?F.a(a,b):null}
var gd=function(){function a(a,b,c,h,k){a=y(a);a[b]=c;a[h]=k;return a}function b(a,b,c){a=y(a);a[b]=c;return a}var c=null,c=function(c,e,f,h,k){switch(arguments.length){case 3:return b.call(this,c,e,f);case 5:return a.call(this,c,e,f,h,k)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.F=a;return c}();function hd(a,b){var c=Array(a.length-2);Lb(a,0,c,0,2*b);Lb(a,2*(b+1),c,2*b,c.length-2*b);return c}
var id=function(){function a(a,b,c,h,k,l){a=a.qa(b);a.d[c]=h;a.d[k]=l;return a}function b(a,b,c,h){a=a.qa(b);a.d[c]=h;return a}var c=null,c=function(c,e,f,h,k,l){switch(arguments.length){case 4:return b.call(this,c,e,f,h);case 6:return a.call(this,c,e,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};c.j=b;c.Z=a;return c}();function jd(a,b,c){this.o=a;this.q=b;this.d=c}g=jd.prototype;
g.ba=function(a,b,c,d,e,f){var h=1<<(c>>>b&31),k=Rb(this.q&h-1);if(0===(this.q&h)){var l=Rb(this.q);if(2*l<this.d.length){a=this.qa(a);b=a.d;f.D=!0;a:for(c=2*(l-k),f=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[f];l-=1;c-=1;f-=1}b[2*k]=d;b[2*k+1]=e;a.q|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=kd.ba(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0!==
(this.q>>>d&1)&&(k[d]=null!=this.d[e]?kd.ba(a,b+5,H(this.d[e]),this.d[e],this.d[e+1],f):this.d[e+1],e+=2),d+=1;else break;return new ld(a,l+1,k)}return u?(b=Array(2*(l+4)),Lb(this.d,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Lb(this.d,2*k,b,2*(k+1),2*(l-k)),f.D=!0,a=this.qa(a),a.d=b,a.q|=h,a):null}l=this.d[2*k];h=this.d[2*k+1];return null==l?(l=h.ba(a,b+5,c,d,e,f),l===h?this:id.j(this,a,2*k+1,l)):fd(d,l)?e===h?this:id.j(this,a,2*k+1,e):u?(f.D=!0,id.Z(this,a,2*k,null,2*k+1,md.oa?md.oa(a,b+5,l,h,c,d,e):md.call(null,
a,b+5,l,h,c,d,e))):null};g.za=function(){return nd.b?nd.b(this.d):nd.call(null,this.d)};g.qa=function(a){if(a===this.o)return this;var b=Rb(this.q),c=Array(0>b?4:2*(b+1));Lb(this.d,0,c,0,2*b);return new jd(a,this.q,c)};
g.Aa=function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.q&d))return this;var e=Rb(this.q&d-1),f=this.d[2*e],h=this.d[2*e+1];return null==f?(a=h.Aa(a+5,b,c),a===h?this:null!=a?new jd(null,this.q,gd.c(this.d,2*e+1,a)):this.q===d?null:u?new jd(null,this.q^d,hd(this.d,e)):null):fd(c,f)?new jd(null,this.q^d,hd(this.d,e)):u?this:null};
g.aa=function(a,b,c,d,e){var f=1<<(b>>>a&31),h=Rb(this.q&f-1);if(0===(this.q&f)){var k=Rb(this.q);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=kd.aa(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.q>>>c&1)&&(h[c]=null!=this.d[d]?kd.aa(a+5,H(this.d[d]),this.d[d],this.d[d+1],e):this.d[d+1],d+=2),c+=1;else break;return new ld(null,k+1,h)}a=Array(2*(k+1));Lb(this.d,0,
a,0,2*h);a[2*h]=c;a[2*h+1]=d;Lb(this.d,2*h,a,2*(h+1),2*(k-h));e.D=!0;return new jd(null,this.q|f,a)}k=this.d[2*h];f=this.d[2*h+1];return null==k?(k=f.aa(a+5,b,c,d,e),k===f?this:new jd(null,this.q,gd.c(this.d,2*h+1,k))):fd(c,k)?d===f?this:new jd(null,this.q,gd.c(this.d,2*h+1,d)):u?(e.D=!0,new jd(null,this.q,gd.F(this.d,2*h,null,2*h+1,md.Z?md.Z(a+5,k,f,b,c,d):md.call(null,a+5,k,f,b,c,d)))):null};
g.ma=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.q&e))return d;var f=Rb(this.q&e-1),e=this.d[2*f],f=this.d[2*f+1];return null==e?f.ma(a+5,b,c,d):fd(c,e)?f:u?d:null};var kd=new jd(null,0,[]);function ld(a,b,c){this.o=a;this.e=b;this.d=c}g=ld.prototype;g.ba=function(a,b,c,d,e,f){var h=c>>>b&31,k=this.d[h];if(null==k)return a=id.j(this,a,h,kd.ba(a,b+5,c,d,e,f)),a.e+=1,a;b=k.ba(a,b+5,c,d,e,f);return b===k?this:id.j(this,a,h,b)};g.za=function(){return od.b?od.b(this.d):od.call(null,this.d)};
g.qa=function(a){return a===this.o?this:new ld(a,this.e,y(this.d))};g.Aa=function(a,b,c){var d=b>>>a&31,e=this.d[d];if(null!=e){a=e.Aa(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.e)a:{e=this.d;a=2*(this.e-1);b=Array(a);c=0;for(var f=1,h=0;;)if(c<a)c!==d&&null!=e[c]&&(b[f]=e[c],f+=2,h|=1<<c),c+=1;else{d=new jd(null,h,b);break a}d=void 0}else d=new ld(null,this.e-1,gd.c(this.d,d,a));else d=u?new ld(null,this.e,gd.c(this.d,d,a)):null;return d}return this};
g.aa=function(a,b,c,d,e){var f=b>>>a&31,h=this.d[f];if(null==h)return new ld(null,this.e+1,gd.c(this.d,f,kd.aa(a+5,b,c,d,e)));a=h.aa(a+5,b,c,d,e);return a===h?this:new ld(null,this.e,gd.c(this.d,f,a))};g.ma=function(a,b,c,d){var e=this.d[b>>>a&31];return null!=e?e.ma(a+5,b,c,d):d};function pd(a,b,c){b*=2;for(var d=0;;)if(d<b){if(fd(c,a[d]))return d;d+=2}else return-1}function qd(a,b,c,d){this.o=a;this.ga=b;this.e=c;this.d=d}g=qd.prototype;
g.ba=function(a,b,c,d,e,f){if(c===this.ga){b=pd(this.d,this.e,d);if(-1===b){if(this.d.length>2*this.e)return a=id.Z(this,a,2*this.e,d,2*this.e+1,e),f.D=!0,a.e+=1,a;c=this.d.length;b=Array(c+2);Lb(this.d,0,b,0,c);b[c]=d;b[c+1]=e;f.D=!0;f=this.e+1;a===this.o?(this.d=b,this.e=f,a=this):a=new qd(this.o,this.ga,f,b);return a}return this.d[b+1]===e?this:id.j(this,a,b+1,e)}return(new jd(a,1<<(this.ga>>>b&31),[null,this,null,null])).ba(a,b,c,d,e,f)};g.za=function(){return nd.b?nd.b(this.d):nd.call(null,this.d)};
g.qa=function(a){if(a===this.o)return this;var b=Array(2*(this.e+1));Lb(this.d,0,b,0,2*this.e);return new qd(a,this.ga,this.e,b)};g.Aa=function(a,b,c){a=pd(this.d,this.e,c);return-1===a?this:1===this.e?null:u?new qd(null,this.ga,this.e-1,hd(this.d,Qb((a-a%2)/2))):null};
g.aa=function(a,b,c,d,e){return b===this.ga?(a=pd(this.d,this.e,c),-1===a?(a=2*this.e,b=Array(a+2),Lb(this.d,0,b,0,a),b[a]=c,b[a+1]=d,e.D=!0,new qd(null,this.ga,this.e+1,b)):F.a(this.d[a],d)?this:new qd(null,this.ga,this.e,gd.c(this.d,a+1,d))):(new jd(null,1<<(this.ga>>>a&31),[null,this])).aa(a,b,c,d,e)};g.ma=function(a,b,c,d){a=pd(this.d,this.e,c);return 0>a?d:fd(c,this.d[a])?this.d[a+1]:u?d:null};
var md=function(){function a(a,b,c,h,k,l,m){var p=H(c);if(p===k)return new qd(null,p,2,[c,h,l,m]);var r=new ed;return kd.ba(a,b,p,c,h,r).ba(a,b,k,l,m,r)}function b(a,b,c,h,k,l){var m=H(b);if(m===h)return new qd(null,m,2,[b,c,k,l]);var p=new ed;return kd.aa(a,m,b,c,p).aa(a,h,k,l,p)}var c=null,c=function(c,e,f,h,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,f,h,k,l);case 7:return a.call(this,c,e,f,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.Z=b;c.oa=a;return c}();
function rd(a,b,c,d,e){this.h=a;this.ca=b;this.k=c;this.r=d;this.l=e;this.n=0;this.g=32374860}g=rd.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return this};g.T=function(){return null==this.r?new W(null,2,5,Y,[this.ca[this.k],this.ca[this.k+1]],null):J(this.r)};
g.W=function(){return null==this.r?nd.c?nd.c(this.ca,this.k+2,null):nd.call(null,this.ca,this.k+2,null):nd.c?nd.c(this.ca,this.k,N(this.r)):nd.call(null,this.ca,this.k,N(this.r))};g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new rd(b,this.ca,this.k,this.r,this.l)};g.B=function(){return this.h};g.M=function(){return Eb(M,this.h)};
var nd=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new rd(null,a,b,null,null);var h=a[b+1];if(s(h)&&(h=h.za(),s(h)))return new rd(null,a,b+2,h,null);b+=2}else return null;else return new rd(null,a,b,c,null)}function b(a){return c.c(a,0,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();
function sd(a,b,c,d,e){this.h=a;this.ca=b;this.k=c;this.r=d;this.l=e;this.n=0;this.g=32374860}g=sd.prototype;g.A=function(){var a=this.l;return null!=a?a:this.l=a=ub(this)};g.I=function(a,b){return P(b,this)};g.toString=function(){return kb(this)};g.R=function(a,b){return Pb.a(b,this)};g.S=function(a,b,c){return Pb.c(b,c,this)};g.G=function(){return this};g.T=function(){return J(this.r)};g.W=function(){return od.j?od.j(null,this.ca,this.k,N(this.r)):od.call(null,null,this.ca,this.k,N(this.r))};
g.v=function(a,b){return vb(this,b)};g.C=function(a,b){return new sd(b,this.ca,this.k,this.r,this.l)};g.B=function(){return this.h};g.M=function(){return Eb(M,this.h)};
var od=function(){function a(a,b,c,h){if(null==h)for(h=b.length;;)if(c<h){var k=b[c];if(s(k)&&(k=k.za(),s(k)))return new sd(a,b,c+1,k,null);c+=1}else return null;else return new sd(a,b,c,h,null)}function b(a){return c.j(null,a,0,null)}var c=null,c=function(c,e,f,h){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.j=a;return c}();
function td(a,b,c,d,e,f){this.h=a;this.e=b;this.root=c;this.Q=d;this.V=e;this.l=f;this.n=8196;this.g=16123663}g=td.prototype;g.Ga=function(){return new ud({},this.root,this.e,this.Q,this.V)};g.A=function(){var a=this.l;return null!=a?a:this.l=a=Tb(this)};g.N=function(a,b){return Ca.c(this,b,null)};g.O=function(a,b,c){return null==b?this.Q?this.V:c:null==this.root?c:u?this.root.ma(0,H(b),b,c):null};
g.ta=function(a,b,c){if(null==b)return this.Q&&c===this.V?this:new td(this.h,this.Q?this.e:this.e+1,this.root,!0,c,null);a=new ed;b=(null==this.root?kd:this.root).aa(0,H(b),b,c,a);return b===this.root?this:new td(this.h,a.D?this.e+1:this.e,b,this.Q,this.V,null)};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.O(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
g.apply=function(a,b){return this.call.apply(this,[this].concat(y(b)))};g.b=function(a){return this.N(null,a)};g.a=function(a,b){return this.O(null,a,b)};g.I=function(a,b){return Ib(b)?Da(this,z.a(b,0),z.a(b,1)):ra.c(ya,this,b)};g.toString=function(){return kb(this)};g.G=function(){if(0<this.e){var a=null!=this.root?this.root.za():null;return this.Q?P(new W(null,2,5,Y,[null,this.V],null),a):a}return null};g.J=function(){return this.e};g.v=function(a,b){return Wc(this,b)};
g.C=function(a,b){return new td(b,this.e,this.root,this.Q,this.V,this.l)};g.B=function(){return this.h};g.M=function(){return Qa(bd,this.h)};g.cb=function(a,b){if(null==b)return this.Q?new td(this.h,this.e-1,this.root,!1,null,null):this;if(null==this.root)return this;if(u){var c=this.root.Aa(0,H(b),b);return c===this.root?this:new td(this.h,this.e-1,c,this.Q,this.V,null)}return null};var bd=new td(null,0,null,!1,null,0);
function zb(a,b){for(var c=a.length,d=0,e=ab(bd);;)if(d<c)var f=d+1,e=e.va(null,a[d],b[d]),d=f;else return cb(e)}function ud(a,b,c,d,e){this.o=a;this.root=b;this.count=c;this.Q=d;this.V=e;this.n=56;this.g=258}g=ud.prototype;g.va=function(a,b,c){return vd(this,b,c)};
g.Ha=function(a,b){var c;a:{if(this.o){if(b?b.g&2048||b.xb||(b.g?0:t(Ga,b)):t(Ga,b)){c=vd(this,Vb.b?Vb.b(b):Vb.call(null,b),Wb.b?Wb.b(b):Wb.call(null,b));break a}c=I(b);for(var d=this;;){var e=J(c);if(s(e))c=N(c),d=vd(d,Vb.b?Vb.b(e):Vb.call(null,e),Wb.b?Wb.b(e):Wb.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
g.Ia=function(){var a;if(this.o)this.o=null,a=new td(null,this.count,this.root,this.Q,this.V,null);else throw Error("persistent! called twice");return a};g.N=function(a,b){return null==b?this.Q?this.V:null:null==this.root?null:this.root.ma(0,H(b),b)};g.O=function(a,b,c){return null==b?this.Q?this.V:c:null==this.root?c:this.root.ma(0,H(b),b,c)};g.J=function(){if(this.o)return this.count;throw Error("count after persistent!");};
function vd(a,b,c){if(a.o){if(null==b)a.V!==c&&(a.V=c),a.Q||(a.count+=1,a.Q=!0);else{var d=new ed;b=(null==a.root?kd:a.root).ba(a.o,0,H(b),b,c,d);b!==a.root&&(a.root=b);d.D&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var wd=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=I(a);for(var b=ab(bd);;)if(a){var e=N(N(a)),b=pc.c(b,J(a),J(N(a)));a=e}else return cb(b)}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}();function Vb(a){return Ha(a)}function Wb(a){return Ia(a)}
var xd=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return s(sc(a))?ra.a(function(a,b){return xb.a(s(a)?a:cd,b)},a):null}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}();function bc(a){if(a&&(a.n&4096||a.zb))return a.name;if("string"===typeof a)return a;throw Error([x("Doesn't support name: "),x(a)].join(""));}
function yd(a,b,c,d,e,f,h){var k=ga;try{ga=null==ga?null:ga-1;if(null!=ga&&0>ga)return D(a,"#");D(a,c);I(h)&&(b.c?b.c(J(h),a,f):b.call(null,J(h),a,f));for(var l=N(h),m=na.b(f);l&&(null==m||0!==m);){D(a,d);b.c?b.c(J(l),a,f):b.call(null,J(l),a,f);var p=N(l);c=m-1;l=p;m=c}s(na.b(f))&&(D(a,d),b.c?b.c("...",a,f):b.call(null,"...",a,f));return D(a,e)}finally{ga=k}}
var zd=function(){function a(a,d){var e=null;1<arguments.length&&(e=O(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=I(b),f=null,h=0,k=0;;)if(k<h){var l=f.K(null,k);D(a,l);k+=1}else if(e=I(e))f=e,Jb(f)?(e=gb(f),h=hb(f),f=e,l=Q(e),e=h,h=l):(l=J(f),D(a,l),e=N(f),f=null,h=0),k=0;else return null}a.m=1;a.i=function(a){var d=J(a);a=L(a);return b(d,a)};a.f=b;return a}(),Ad={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function Bd(a){return[x('"'),x(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return Ad[a]})),x('"')].join("")}
var Ed=function Cd(b,c,d){if(null==b)return D(c,"nil");if(void 0===b)return D(c,"#\x3cundefined\x3e");if(u){s(function(){var c=S.a(d,la);return s(c)?(c=b?b.g&131072||b.yb?!0:b.g?!1:t(Na,b):t(Na,b))?Fb(b):c:c}())&&(D(c,"^"),Cd(Fb(b),c,d),D(c," "));if(null==b)return D(c,"nil");if(b.xa)return b.Ja(b,c,d);if(b&&(b.g&2147483648||b.P))return b.u(null,c,d);if(pa(b)===Boolean||"number"===typeof b)return D(c,""+x(b));if(null!=b&&b.constructor===Object)return D(c,"#js "),Dd.j?Dd.j(uc.a(function(c){return new W(null,
2,5,Y,[cc.b(c),b[c]],null)},Kb(b)),Cd,c,d):Dd.call(null,uc.a(function(c){return new W(null,2,5,Y,[cc.b(c),b[c]],null)},Kb(b)),Cd,c,d);if(b instanceof Array)return yd(c,Cd,"#js ["," ","]",d,b);if("string"==typeof b)return s(ka.b(d))?D(c,Bd(b)):D(c,b);if(Bb(b))return zd.f(c,O(["#\x3c",""+x(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+x(b);;)if(Q(d)<c)d=[x("0"),x(d)].join("");else return d};return zd.f(c,O(['#inst "',""+x(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),
2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?zd.f(c,O(['#"',b.source,'"'],0)):(b?b.g&2147483648||b.P||(b.g?0:t(Ya,b)):t(Ya,b))?Za(b,c,d):u?zd.f(c,O(["#\x3c",""+x(b),"\x3e"],0)):null}return null};
function Fd(a,b){var c;if(null==a||oa(I(a)))c="";else{c=x;var d=new da;a:{var e=new jb(d);Ed(J(a),e,b);for(var f=I(N(a)),h=null,k=0,l=0;;)if(l<k){var m=h.K(null,l);D(e," ");Ed(m,e,b);l+=1}else if(f=I(f))h=f,Jb(h)?(f=gb(h),k=hb(h),h=f,m=Q(f),f=k,k=m):(m=J(h),D(e," "),Ed(m,e,b),f=N(h),h=null,k=0),l=0;else break a}c=""+c(d)}return c}
var Gd=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return Fd(a,ia())}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}(),Hd=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=T.c(ia(),ka,!1);a=Fd(a,b);fa.b?fa.b(a):fa.call(null,a);return null}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}();
function Dd(a,b,c,d){return yd(c,function(a,c,d){b.c?b.c(Ha(a),c,d):b.call(null,Ha(a),c,d);D(c," ");return b.c?b.c(Ia(a),c,d):b.call(null,Ia(a),c,d)},"{",", ","}",d,I(a))}pb.prototype.P=!0;pb.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};Qc.prototype.P=!0;Qc.prototype.u=function(a,b,c){return yd(b,Ed,"["," ","]",c,this)};ic.prototype.P=!0;ic.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};q.prototype.P=!0;q.prototype.u=function(a,b,c){return Dd(this,Ed,b,c)};
dc.prototype.P=!0;dc.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};rd.prototype.P=!0;rd.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};Oc.prototype.P=!0;Oc.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};td.prototype.P=!0;td.prototype.u=function(a,b,c){return Dd(this,Ed,b,c)};W.prototype.P=!0;W.prototype.u=function(a,b,c){return yd(b,Ed,"["," ","]",c,this)};Xb.prototype.P=!0;Xb.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};
Yc.prototype.P=!0;Yc.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};Yb.prototype.P=!0;Yb.prototype.u=function(a,b){return D(b,"()")};$b.prototype.P=!0;$b.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};sd.prototype.P=!0;sd.prototype.u=function(a,b,c){return yd(b,Ed,"("," ",")",c,this)};W.prototype.Ea=!0;W.prototype.Fa=function(a,b){return Ob.a(this,b)};Qc.prototype.Ea=!0;Qc.prototype.Fa=function(a,b){return Ob.a(this,b)};V.prototype.Ea=!0;
V.prototype.Fa=function(a,b){return lb(this,b)};G.prototype.Ea=!0;G.prototype.Fa=function(a,b){return lb(this,b)};function Id(a,b){if(a?a.Bb:a)return a.Bb(a,b);var c;c=Id[n(null==a?null:a)];if(!c&&(c=Id._,!c))throw v("IReset.-reset!",a);return c.call(null,a,b)}function Jd(a,b,c,d){this.state=a;this.h=b;this.Kb=c;this.sb=d;this.g=2153938944;this.n=16386}g=Jd.prototype;g.A=function(){return this[aa]||(this[aa]=++ba)};
g.ob=function(a,b,c){a=I(this.sb);for(var d=null,e=0,f=0;;)if(f<e){var h=d.K(null,f),k=R.c(h,0,null),h=R.c(h,1,null);h.j?h.j(k,this,b,c):h.call(null,k,this,b,c);f+=1}else if(a=I(a))Jb(a)?(d=gb(a),a=hb(a),k=d,e=Q(d),d=k):(d=J(a),k=R.c(d,0,null),h=R.c(d,1,null),h.j?h.j(k,this,b,c):h.call(null,k,this,b,c),a=N(a),d=null,e=0),f=0;else return null};g.u=function(a,b,c){D(b,"#\x3cAtom: ");Ed(this.state,b,c);return D(b,"\x3e")};g.B=function(){return this.h};g.Pa=function(){return this.state};
g.v=function(a,b){return this===b};
var Ld=function(){function a(a){return new Jd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=O(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=Mb(c)?Db.a(wd,c):c,e=S.a(d,Kd),d=S.a(d,la);return new Jd(a,d,e,null)}a.m=1;a.i=function(a){var c=J(a);a=L(a);return b(c,a)};a.f=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.f(b,O(arguments,1))}throw Error("Invalid arity: "+
arguments.length);};b.m=1;b.i=c.i;b.b=a;b.f=c.f;return b}();var ma=new V(null,"dup","dup"),Md=new V(null,"ball","ball"),Nd=new V(null,"direction","direction"),Od=new V(null,"timestamp","timestamp"),nb=new V(null,"default","default"),Pd=new V(null,"recur","recur"),Qd=new V(null,"position","position"),Rd=new V(null,"finally-block","finally-block"),Sd=new V(null,"catch-block","catch-block"),Td=new V(null,"width","width"),Ud=new V(null,"speed","speed"),Vd=new V(null,"velocity","velocity"),Wd=new V(null,"y","y"),$=new V(null,"x","x"),Xd=new V(null,"has-bounced?",
"has-bounced?"),Yd=new V(null,"wall-hits","wall-hits"),ja=new V(null,"flush-on-newline","flush-on-newline"),Zd=new V(null,"length","length"),$d=new V(null,"catch-exception","catch-exception"),ae=new V(null,"continue-block","continue-block"),be=new V(null,"src","src"),ce=new V(null,"prev","prev"),de=new V(null,"acceleration","acceleration"),ee=new V(null,"pos","pos"),fe=new V(null,"phone","phone"),ge=new V(null,"walls","walls"),na=new V(null,"print-length","print-length"),u=new V(null,"else","else"),
ka=new V(null,"readably","readably"),Kd=new V(null,"validator","validator"),la=new V(null,"meta","meta"),he=new V(null,"coord","coord"),ie=new V(null,"height","height");var je;function ke(a,b,c){if(a?a.gb:a)return a.gb(0,b,c);var d;d=ke[n(null==a?null:a)];if(!d&&(d=ke._,!d))throw v("WritePort.put!",a);return d.call(null,a,b,c)}function le(a){if(a?a.rb:a)return!0;var b;b=le[n(null==a?null:a)];if(!b&&(b=le._,!b))throw v("Handler.active?",a);return b.call(null,a)}function me(a){if(a?a.fb:a)return a.fb();var b;b=me[n(null==a?null:a)];if(!b&&(b=me._,!b))throw v("Buffer.full?",a);return b.call(null,a)};var ne,pe=function oe(b){"undefined"===typeof ne&&(ne=function(b,d,e){this.U=b;this.hb=d;this.Hb=e;this.n=0;this.g=393216},ne.xa=!0,ne.wa="cljs.core.async.impl.ioc-helpers/t13641",ne.Ja=function(b,d){return D(d,"cljs.core.async.impl.ioc-helpers/t13641")},ne.prototype.rb=function(){return!0},ne.prototype.B=function(){return this.Hb},ne.prototype.C=function(b,d){return new ne(this.U,this.hb,d)});return new ne(b,oe,null)};
function qe(a){try{return a[0].call(null,a)}catch(b){if(b instanceof Object)throw a[6].qb(),b;if(u)throw b;return null}}function re(a,b){var c=b.Db(pe(function(b){a[2]=b;a[1]=4;return qe(a)}));return s(c)?(a[2]=Ma(c),a[1]=4,Pd):null}function se(a,b){var c=a[6];null!=b&&c.gb(0,b,pe(function(){return function(){return null}}(c)));c.qb();return c}
function te(a){for(;;){var b=a[4],c=Sd.b(b),d=$d.b(b),e=a[5];if(s(function(){var a=e;return s(a)?oa(b):a}()))throw e;if(s(function(){var a=e;return s(a)?(a=c,s(a)?e instanceof d:a):a}())){a[1]=c;a[2]=e;a[5]=null;a[4]=T.f(b,Sd,null,O([$d,null],0));break}if(s(function(){var a=e;return s(a)?oa(c)&&oa(Rd.b(b)):a}()))a[4]=ce.b(b);else{if(s(function(){var a=e;return s(a)?(a=oa(c))?Rd.b(b):a:a}())){a[1]=Rd.b(b);a[4]=T.c(b,Rd,null);break}if(s(function(){var a=oa(e);return a?Rd.b(b):a}())){a[1]=Rd.b(b);a[4]=
T.c(b,Rd,null);break}if(oa(e)&&oa(Rd.b(b))){a[1]=ae.b(b);a[4]=ce.b(b);break}if(u)throw Error([x("Assert failed: "),x("No matching clause"),x("\n"),x(Gd.f(O([!1],0)))].join(""));break}}};function ue(a,b,c,d,e){for(var f=0;;)if(f<e)c[d+f]=a[b+f],f+=1;else break}function ve(a,b,c,d){this.head=a;this.p=b;this.length=c;this.d=d}ve.prototype.pop=function(){if(0===this.length)return null;var a=this.d[this.p];this.d[this.p]=null;this.p=(this.p+1)%this.d.length;this.length-=1;return a};ve.prototype.unshift=function(a){this.d[this.head]=a;this.head=(this.head+1)%this.d.length;this.length+=1;return null};function we(a,b){a.length+1===a.d.length&&a.resize();a.unshift(b)}
ve.prototype.resize=function(){var a=Array(2*this.d.length);return this.p<this.head?(ue(this.d,this.p,a,0,this.length),this.p=0,this.head=this.length,this.d=a):this.p>this.head?(ue(this.d,this.p,a,0,this.d.length-this.p),ue(this.d,0,a,this.d.length-this.p,this.head),this.p=0,this.head=this.length,this.d=a):this.p===this.head?(this.head=this.p=0,this.d=a):null};function xe(a,b){for(var c=a.length,d=0;;)if(d<c){var e=a.pop();(b.b?b.b(e):b.call(null,e))&&a.unshift(e);d+=1}else break}
function ye(a){if(!(0<a))throw Error([x("Assert failed: "),x("Can't create a ring buffer of size 0"),x("\n"),x(Gd.f(O([Zb(new G(null,"\x3e","\x3e",-1640531465,null),new G(null,"n","n",-1640531417,null),0)],0)))].join(""));return new ve(0,0,0,Array(a))}function ze(a,b){this.H=a;this.Ib=b;this.n=0;this.g=2}ze.prototype.J=function(){return this.H.length};ze.prototype.fb=function(){return this.H.length===this.Ib};ze.prototype.Cb=function(){return this.H.pop()};
function Ae(a,b){if(!oa(me(a)))throw Error([x("Assert failed: "),x("Can't add to a full buffer"),x("\n"),x(Gd.f(O([Zb(new G(null,"not","not",-1640422260,null),Zb(new G("impl","full?","impl/full?",-1337857039,null),new G(null,"this","this",-1636972457,null)))],0)))].join(""));a.H.unshift(b)};var Be=null,Ce=ye(32),De=!1,Ee=!1;function Fe(){De=!0;Ee=!1;for(var a=0;;){var b=Ce.pop();if(null!=b&&(b.w?b.w():b.call(null),1024>a)){a+=1;continue}break}De=!1;return 0<Ce.length?Ge.w?Ge.w():Ge.call(null):null}"undefined"!==typeof MessageChannel&&(Be=new MessageChannel,Be.port1.onmessage=function(){return Fe()});
function Ge(){var a=Ee;if(s(a?De:a))return null;Ee=!0;return"undefined"!==typeof MessageChannel?Be.port2.postMessage(0):"undefined"!==typeof setImmediate?setImmediate(Fe):u?setTimeout(Fe,0):null}function He(a){we(Ce,a);Ge()};var Ie,Ke=function Je(b){"undefined"===typeof Ie&&(Ie=function(b,d,e){this.D=b;this.tb=d;this.Gb=e;this.n=0;this.g=425984},Ie.xa=!0,Ie.wa="cljs.core.async.impl.channels/t13625",Ie.Ja=function(b,d){return D(d,"cljs.core.async.impl.channels/t13625")},Ie.prototype.Pa=function(){return this.D},Ie.prototype.B=function(){return this.Gb},Ie.prototype.C=function(b,d){return new Ie(this.D,this.tb,d)});return new Ie(b,Je,null)};function Le(a,b){this.ib=a;this.D=b}function Me(a){return le(a.ib)}
function Ne(a,b,c,d,e,f){this.Da=a;this.La=b;this.Ca=c;this.Ka=d;this.H=e;this.closed=f}Ne.prototype.qb=function(){if(!this.closed)for(this.closed=!0;;){var a=this.Da.pop();if(null!=a)He(function(a){return function(){return a.b?a.b(null):a.call(null,null)}}(a.U,a,this));else break}};
Ne.prototype.Db=function(a){if(null!=this.H&&0<Q(this.H)){for(var b=a.U,c=Ke(this.H.Cb());;){var d=this.Ca.pop();if(null!=d){var e=d.ib,f=d.D;He(function(a){return function(){return a.b?a.b(!0):a.call(null,!0)}}(e.U,a.U,e,f,d,b,c,this));Ae(this.H,f)}break}return c}for(;;){c=this.Ca.pop();if(null!=c)return d=c.ib,e=c.D,f=d.U,b=a.U,He(function(a){return function(){return a.b?a.b(!0):a.call(null,!0)}}(f,b,d,e,c,this)),Ke(e);if(this.closed)return b=a.U,Ke(null);64<this.La?(this.La=0,xe(this.Da,le)):this.La+=
1;if(!(1024>this.Da.length))throw Error([x("Assert failed: "),x([x("No more than "),x(1024),x(" pending takes are allowed on a single channel.")].join("")),x("\n"),x(Gd.f(O([Zb(new G(null,"\x3c","\x3c",-1640531467,null),Zb(new G(null,".-length",".-length",1395928862,null),new G(null,"takes","takes",-1530407291,null)),new G("impl","MAX-QUEUE-SIZE","impl/MAX-QUEUE-SIZE",-1989946393,null))],0)))].join(""));we(this.Da,a);return null}};
Ne.prototype.gb=function(a,b,c){if(null==b)throw Error([x("Assert failed: "),x("Can't put nil in on a channel"),x("\n"),x(Gd.f(O([Zb(new G(null,"not","not",-1640422260,null),Zb(new G(null,"nil?","nil?",-1637150201,null),new G(null,"val","val",-1640415014,null)))],0)))].join(""));if(a=this.closed)return Ke(!a);for(;;){var d=this.Da.pop();if(null!=d)c=c.U,He(function(a){return function(){return a.b?a.b(b):a.call(null,b)}}(d.U,c,d,a,this));else{if(null==this.H||this.H.fb()){64<this.Ka?(this.Ka=0,xe(this.Ca,
Me)):this.Ka+=1;if(!(1024>this.Ca.length))throw Error([x("Assert failed: "),x([x("No more than "),x(1024),x(" pending puts are allowed on a single channel."),x(" Consider using a windowed buffer.")].join("")),x("\n"),x(Gd.f(O([Zb(new G(null,"\x3c","\x3c",-1640531467,null),Zb(new G(null,".-length",".-length",1395928862,null),new G(null,"puts","puts",-1637078787,null)),new G("impl","MAX-QUEUE-SIZE","impl/MAX-QUEUE-SIZE",-1989946393,null))],0)))].join(""));we(this.Ca,new Le(c,b));return null}c=c.U;Ae(this.H,
b)}return Ke(!0)}};function Oe(a,b,c){this.key=a;this.D=b;this.forward=c;this.n=0;this.g=2155872256}Oe.prototype.u=function(a,b,c){return yd(b,Ed,"["," ","]",c,this)};Oe.prototype.G=function(){return ya(ya(M,this.D),this.key)};
(function(){function a(a,b,c){c=Array(c+1);for(var h=0;;)if(h<c.length)c[h]=null,h+=1;else break;return new Oe(a,b,c)}function b(a){return c.c(null,null,a)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c})().b(0);var Qe=function Pe(b){"undefined"===typeof je&&(je=function(b,d,e){this.U=b;this.hb=d;this.Fb=e;this.n=0;this.g=393216},je.xa=!0,je.wa="cljs.core.async/t10934",je.Ja=function(b,d){return D(d,"cljs.core.async/t10934")},je.prototype.rb=function(){return!0},je.prototype.B=function(){return this.Fb},je.prototype.C=function(b,d){return new je(this.U,this.hb,d)});return new je(b,Pe,null)},Re=function(){function a(a){a=F.a(a,0)?null:a;a="number"===typeof a?new ze(ye(a),a):a;return new Ne(ye(32),0,ye(32),
0,a,!1)}function b(){return c.b(null)}var c=null,c=function(c){switch(arguments.length){case 0:return b.call(this);case 1:return a.call(this,c)}throw Error("Invalid arity: "+arguments.length);};c.w=b;c.b=a;return c}(),Se=Qe(function(){return null}),Te=function(){function a(a,b,c,d){a=ke(a,b,Qe(c));return s(a)?(b=Ma(a),s(d)?c.b?c.b(b):c.call(null,b):He(function(a){return function(){return c.b?c.b(a):c.call(null,a)}}(b,a,a)),b):!0}function b(a,b,c){return d.j(a,b,c,!0)}function c(a,b){var c=ke(a,b,
Se);return s(c)?Ma(c):!0}var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.j=a;return d}();var fa=function(){function a(a){var d=null;0<arguments.length&&(d=O(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return console.log.apply(console,sa.b?sa.b(a):sa.call(null,a))}a.m=0;a.i=function(a){a=I(a);return b(a)};a.f=b;return a}(),Ue=function(){function a(a,d){var e=null;1<arguments.length&&(e=O(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=document.createElement(a),f=I(J(b)),h=null,k=0,l=0;;)if(l<k){var m=h.K(null,
l),p=R.c(m,0,null),m=R.c(m,1,null);e.setAttribute(bc(p),m);l+=1}else if(f=I(f))Jb(f)?(k=gb(f),f=hb(f),h=k,k=Q(k)):(k=J(f),h=R.c(k,0,null),k=R.c(k,1,null),e.setAttribute(bc(h),k),f=N(f),h=null,k=0),l=0;else break;return e}a.m=1;a.i=function(a){var d=J(a);a=L(a);return b(d,a)};a.f=b;return a}();
function Ve(){var a=Re.w(),b=navigator.accelerometer.getCurrentAcceleration;b.b?b.b(function(a){return function(b){return Te.a(a,b)}}(a,b)):b.call(null,function(a){return function(b){return Te.a(a,b)}}(a,b));return a}function We(){navigator.accelerometer.watchAcceleration(function(){return null},function(){return null},{frequency:10})}var Xe=Ld.b(cd);
function Ye(a,b){var c=Mb(a)?Db.a(wd,a):a,d=S.a(c,Nd),e=S.a(c,Zd),f=S.a(c,ee),h=S.a(c,he),c=F.a(h,$)?new W(null,2,5,Y,[e,90],null):new W(null,2,5,Y,[90,e],null),e=R.c(c,0,null),c=R.c(c,1,null),k;k=new W(null,2,5,Y,[h,d],null);k=F.a(new W(null,2,5,Y,[Wd,1],null),k)?new W(null,2,5,Y,[0,f],null):F.a(new W(null,2,5,Y,[Wd,-1],null),k)?new W(null,2,5,Y,[0,f-e],null):F.a(new W(null,2,5,Y,[$,1],null),k)?new W(null,2,5,Y,[f,0],null):F.a(new W(null,2,5,Y,[$,-1],null),k)?new W(null,2,5,Y,[f-c,0],null):u?new W(null,
2,5,Y,[0,0],null):null;f=R.c(k,0,null);k=R.c(k,1,null);d=new W(null,2,5,Y,[h,d],null);d=F.a(new W(null,2,5,Y,[Wd,-1],null),d)?"yellow":F.a(new W(null,2,5,Y,[$,-1],null),d)?"blue":F.a(new W(null,2,5,Y,[$,1],null),d)?"green":u?"red":null;h=b.createLinearGradient(f,k,f+c,k+e);h.addColorStop(0,d);h.addColorStop(1,"transparent");b.fillStyle=h;b.fillRect(f,k,c,e)}
function Ze(a,b){return F.a(Xe,b)?null:requestAnimationFrame(function(){if(Xe instanceof Jd){var c=Xe.Kb;if(null!=c&&!s(c.b?c.b(b):c.call(null,b)))throw Error([x("Assert failed: "),x("Validator rejected reference state"),x("\n"),x(Gd.f(O([Zb(new G(null,"validate","validate",1233162959,null),new G(null,"new-value","new-value",972165309,null))],0)))].join(""));c=Xe.state;Xe.state=b;null!=Xe.sb&&$a(Xe,c,b)}else Id(Xe,b);a:{var c=a.getContext("2d"),d=b.b?b.b(Md):b.call(null,Md),e=d.b?d.b(Td):d.call(null,
Td);d.b?d.b(ie):d.call(null,ie);var f=$.b(Qd.b(d)),d=Wd.b(Qd.b(d));a.getContext("2d").clearRect(0,0,a.width,a.height);c.fillStyle="rgb(123,0,123)";c.fillRect(f-e/2,d-e/2,e,e);for(var e=I(b.b?b.b(Yd):b.call(null,Yd)),d=null,h=0,k=0;;)if(k<h){var l=d.K(null,k),f=R.c(l,0,null),l=R.c(l,1,null);-900<l-(b.b?b.b(Od):b.call(null,Od))&&Ye(f,c);k+=1}else if(e=I(e))Jb(e)?(d=gb(e),e=hb(e),f=d,h=Q(d),d=f):(d=J(e),f=R.c(d,0,null),l=R.c(d,1,null),-900<l-(b.b?b.b(Od):b.call(null,Od))&&Ye(f,c),e=N(e),d=null,h=0),
k=0;else break a}s(Xd.b(Md.b(b)))?(c=Ud.b(Xd.b(Md.b(b))),f=new W(null,2,5,Y,[0,1],null),e=R.c(f,0,null),f=R.c(f,1,null),c=Math.min(Math.max(c,e),f),e=Ue.f("audio",O([new q(null,1,[be,"squish.mp3"],null)],0)),e.volume=c,c=e.play()):c=null;return c})}function $e(a,b,c){var d=R.c(b,0,null),e=R.c(b,1,null);return xc.c(a,new W(null,1,5,Y,[Qd],null),function(a,b,d){return function(a){return zb.a?zb.a([$,Wd],[$.b(a)+c*b,Wd.b(a)+c*d]):zb.call(null,[$,Wd],[$.b(a)+c*b,Wd.b(a)+c*d])}}(b,d,e))}
function af(a,b){var c=$.b(de.b(a)),d=Wd.b(de.b(a)),e=$.b(Vd.b(a)),f=Wd.b(Vd.b(a)),h=e+b*c,k=f+b*d;return $e(xc.c(a,new W(null,1,5,Y,[Vd],null),function(a,b,c,d,e,f){return function(){return zb.a?zb.a([$,Wd],[e,f]):zb.call(null,[$,Wd],[e,f])}}(c,d,e,f,h,k)),new W(null,2,5,Y,[(e+h)/2,(f+k)/2],null),b)}function bf(a,b){var c=R.c(b,0,null),d=R.c(b,1,null);return c<a&&a<d||c>a&&a>d}
function cf(a,b,c){return ra.c(function(a,b){var c=R.c(b,0,null),h=Mb(c)?Db.a(wd,c):c,k=S.a(h,ee),l=S.a(h,he),m=R.c(b,1,null);return s(m)?xd.f(O([xc.c(xc.c(a,new W(null,2,5,Y,[Qd,l],null),function(a,b,c,d,e,f,h){return function(a){return a+h}}(b,c,h,h,k,l,m)),new W(null,2,5,Y,[Vd,l],null),function(){return function(a){return-(a/1.2)}}(b,c,h,h,k,l,m)),new q(null,1,[Xd,T.c(h,Ud,Math.abs(l.b?l.b(Vd.b(a)):l.call(null,Vd.b(a))))],null)],0)):a},a,function(){return function e(c){return new dc(null,function(){for(;;){var h=
I(c);if(h){if(Jb(h)){var k=gb(h),l=Q(k),m=new fc(Array(l),0);return function(){for(var c=0;;)if(c<l){var e=z.a(k,c),f=Mb(e)?Db.a(wd,e):e,e=f,h=S.a(f,ee),p=S.a(f,he),f=m,r=p.b?p.b(Qd.b(b)):p.call(null,Qd.b(b)),p=p.b?p.b(Qd.b(a)):p.call(null,Qd.b(a)),e=new W(null,2,5,Y,[e,bf(h,new W(null,2,5,Y,[r,p],null))?2*(h-p):null],null);f.add(e);c+=1}else return!0}()?jc(m.Y(),e(hb(h))):jc(m.Y(),null)}var p=J(h),r=p=Mb(p)?Db.a(wd,p):p,w=S.a(p,ee),B=S.a(p,he);return P(function(){var c=B.b?B.b(Qd.b(b)):B.call(null,
Qd.b(b)),e=B.b?B.b(Qd.b(a)):B.call(null,Qd.b(a));return new W(null,2,5,Y,[r,bf(w,new W(null,2,5,Y,[c,e],null))?2*(w-e):null],null)}(),e(L(h)))}return null}},null,null)}(c)}())}function df(a,b){var c=Xd.b(Md.b(a));return s(c)?xc.c(a,new W(null,1,5,Y,[Yd],null),function(c){return function(e){return xb.a(e,new W(null,2,5,Y,[c,(a.b?a.b(Od):a.call(null,Od))+b],null))}}(c)):a}
function ef(a){var b=Date.now(),c=b-Od.b(a);return T.c(df(xc.c(a,new W(null,1,5,Y,[Md],null),function(b,c){return function(b){var d=a.b?a.b(fe):a.call(null,fe),k=a.b?a.b(ge):a.call(null,ge),l=d.x/830,d=-d.y/830;return cf(af(wc(Ab.a(b,Xd),new W(null,1,5,Y,[de],null),zb.a?zb.a([$,Wd],[l,d]):zb.call(null,[$,Wd],[l,d])),c),b,k)}}(b,c)),c),Od,b)}
var ff=innerWidth,gf=innerHeight,hf=T.c(new q(null,2,[ge,new W(null,4,5,Y,[new q(null,4,[he,$,ee,0,Zd,gf,Nd,1],null),new q(null,4,[he,Wd,ee,0,Zd,ff,Nd,1],null),new q(null,4,[he,$,ee,ff,Zd,gf,Nd,-1],null),new q(null,4,[he,Wd,ee,gf,Zd,ff,Nd,-1],null)],null),Md,new q(null,4,[Td,40,ie,40,Qd,new q(null,2,[$,ff/2,Wd,gf/2],null),Vd,new q(null,2,[$,0,Wd,0],null)],null)],null),Yd,Nc);
function jf(a){var b=Re.b(1);He(function(b){return function(){var d=function(){return function(a){return function(){function b(c){for(;;){var d=function(){try{for(;;){var b=a(c);if(!ac(b,Pd))return b}}catch(d){if(d instanceof Object)return c[5]=d,te(c),Pd;if(u)throw d;return null}}();if(!ac(d,Pd))return d}}function c(){var a=[null,null,null,null,null,null,null,null,null,null];a[0]=d;a[1]=1;return a}var d=null,d=function(a){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,
a)}throw Error("Invalid arity: "+arguments.length);};d.w=c;d.b=b;return d}()}(function(){return function(b){var c=b[1];if(4===c){var c=b[7],d=b[8],e=[b[2]],c=zb.a?zb.a(c,e):zb.call(null,c,e),d=xd.f(O([d,c],0)),c=Ze(a,d),d=ef(d);b[9]=c;b[8]=d;b[2]=null;b[1]=2;return Pd}return 3===c?(c=b[2],se(b,c)):2===c?(c=[fe],d=Ve(),b[7]=c,re(b,d)):1===c?(d=xd.f(O([hf,new q(null,1,[Od,Date.now()],null)],0)),b[8]=d,b[2]=null,b[1]=2,Pd):null}}(b),b)}(),e=function(){var a=d.w?d.w():d.call(null);a[6]=b;return a}();
return qe(e)}}(b));return b}function kf(){Hd.f(O(["Starting..."],0));We();var a=Ue("canvas");a.width=innerWidth;a.height=innerHeight;document.body.appendChild(a);return jf(a)}var lf=["ball_roller","core","start"],mf=this;lf[0]in mf||!mf.execScript||mf.execScript("var "+lf[0]);for(var nf;lf.length&&(nf=lf.shift());)lf.length||void 0===kf?mf=mf[nf]?mf[nf]:mf[nf]={}:mf[nf]=kf;document.addEventListener("DOMContentLoaded",function(){return kf()});
})();
